import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { StaticPackCompileInput, StaticPackDefinition } from "../../authority/pack.js";
import { neonDatabaseMigrationAlias, neonDatabaseMigrationDefinitionDigest, neonDatabaseMigrationPackDigest, neonDatabaseMigrationPolicySchemaId, neonDatabaseMigrationProjectionSchemaId, neonDatabaseMigrationReadEndpointId, neonDatabaseMigrationRecipeId, neonDatabaseMigrationResolverId, neonDatabaseMigrationRiskClass, neonDatabaseMigrationWriteEndpointId } from "./manifest.js";
import type { NeonDatabaseMigrationProjection } from "./manifest.js";
export interface NeonDatabaseMigrationPolicy { readonly projectId: string; readonly branchId: string; readonly databaseId: string; readonly roleId: string; readonly migrationId: string; readonly expectedSchemaDigest: string; readonly sql: string; }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Neon ${label} is invalid`); return value; }
function digest(value: unknown): string { if (typeof value !== "string" || !/^sha256:[0-9a-f]{64}$/.test(value)) throw new TypeError("Neon expectedSchemaDigest is invalid"); return value; }
function validateSql(value: unknown): string { if (typeof value !== "string" || value.length === 0 || Buffer.byteLength(value, "utf8") > 1024 * 1024 || /[\0\r\n]/.test(value)) throw new TypeError("Neon migration SQL is invalid"); const ident = "[A-Za-z_][A-Za-z0-9_]{0,62}"; const type = "(?:text|integer|bigint|boolean|timestamp|timestamptz)"; const safe = new RegExp(`^(?:ALTER TABLE ${ident} ADD COLUMN IF NOT EXISTS ${ident} ${type}(?: NOT NULL)?|CREATE INDEX IF NOT EXISTS ${ident} ON ${ident} \(${ident}\));$`); if (!safe.test(value)) throw new TypeError("Neon migration SQL is outside the non-destructive subset"); return value; }
export function validateNeonDatabaseMigrationChoices(value: unknown): Record<string, never> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 0) throw new TypeError("Neon migration choices must be empty"); return Object.freeze({}); }
export function parseNeonDatabaseMigrationPolicy(value: unknown): NeonDatabaseMigrationPolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Neon migration policy must be an object"); const raw = value as Record<string, unknown>; const keys = ["projectId", "branchId", "databaseId", "roleId", "migrationId", "expectedSchemaDigest", "sql"]; if (Object.keys(raw).length !== keys.length || Object.keys(raw).some(key => !keys.includes(key))) throw new TypeError("Neon migration policy is closed"); return Object.freeze({ projectId: id(raw.projectId, "projectId"), branchId: id(raw.branchId, "branchId"), databaseId: id(raw.databaseId, "databaseId"), roleId: id(raw.roleId, "roleId"), migrationId: id(raw.migrationId, "migrationId"), expectedSchemaDigest: digest(raw.expectedSchemaDigest), sql: validateSql(raw.sql) }); }
export function compileNeonDatabaseMigration(input: Readonly<{ source: NeonDatabaseMigrationProjection; policy: NeonDatabaseMigrationPolicy }>): Readonly<{ v: "reelier.transport-effect/v1"; endpointId: string; method: "POST"; path: string; query: string; headers: Record<string, string>; bodyBase64: string; riskClass: string; idempotency: "native"; preconditions: { kind: string; digest: string }[]; reconciliation: { recipeId: string } }> { const { source, policy } = input; if (source.projectId !== policy.projectId || source.branchId !== policy.branchId || source.databaseId !== policy.databaseId || source.roleId !== policy.roleId) throw new TypeError("Neon database identity is outside the signed policy"); if (source.schemaDigest !== policy.expectedSchemaDigest) throw new TypeError("Neon schema drifted from the signed precondition"); if (source.lastMigrationId === policy.migrationId) throw new TypeError("Neon migration is already applied"); const body = authorityCanonicalBytes({ migrationId: policy.migrationId, roleId: policy.roleId, sql: policy.sql }); return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: neonDatabaseMigrationWriteEndpointId, method: "POST", path: `/api/v2/projects/${source.projectId}/branches/${source.branchId}/databases/${source.databaseId}/migrations`, query: "", headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: neonDatabaseMigrationRiskClass, idempotency: "native", preconditions: [{ kind: "neon-schema-digest", digest: authorityDigest({ v: "reelier.neon-schema/v1", projectId: source.projectId, branchId: source.branchId, databaseId: source.databaseId, schemaDigest: source.schemaDigest }) }, { kind: "neon-migration-id", digest: authorityDigest({ v: "reelier.neon-migration/v1", migrationId: policy.migrationId, sql: policy.sql }) }], reconciliation: { recipeId: neonDatabaseMigrationRecipeId } }); }
export const neonDatabaseMigrationDefinition: StaticPackDefinition = Object.freeze({ alias: neonDatabaseMigrationAlias, packDigest: neonDatabaseMigrationPackDigest, definitionDigest: neonDatabaseMigrationDefinitionDigest, resolverId: neonDatabaseMigrationResolverId, projectionSchemaId: neonDatabaseMigrationProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [neonDatabaseMigrationReadEndpointId], writeEndpointIds: [neonDatabaseMigrationWriteEndpointId], riskClasses: [neonDatabaseMigrationRiskClass], policySchemaId: neonDatabaseMigrationPolicySchemaId, requiredGroundedPointers: ["/projectId", "/branchId", "/databaseId", "/roleId", "/schemaDigest", "/catalogDigest", "/lastMigrationId"], validateChoices: validateNeonDatabaseMigrationChoices, parsePolicy: parseNeonDatabaseMigrationPolicy, compile: (input: StaticPackCompileInput) => compileNeonDatabaseMigration({ source: input.source.projection as NeonDatabaseMigrationProjection, policy: input.policy as NeonDatabaseMigrationPolicy }) });
