import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import { authorityDigest } from "../../authority/wire.js";
import { neonDatabaseMigrationDefinitionDigest, neonDatabaseMigrationProjectionSchemaId, neonDatabaseMigrationReadEndpointId, neonDatabaseMigrationResolverId } from "./manifest.js";
import type { NeonDatabaseMigrationProjection } from "./manifest.js";
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Neon catalog response must be an object"); return value as Record<string, unknown>; }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Neon ${label} is invalid`); return value; }
function digest(value: unknown, label: string): string { if (typeof value !== "string" || !/^sha256:[0-9a-f]{64}$/.test(value)) throw new TypeError(`Neon ${label} is invalid`); return value; }
function normalize(rawBytes: Uint8Array): NeonDatabaseMigrationProjection { let parsed: unknown; try { parsed = JSON.parse(Buffer.from(rawBytes).toString("utf8")); } catch { throw new TypeError("Neon catalog response is not JSON"); } const root = object(parsed); return Object.freeze({ projectId: id(root.projectId, "projectId"), branchId: id(root.branchId, "branchId"), databaseId: id(root.databaseId, "databaseId"), roleId: id(root.roleId, "roleId"), schemaDigest: digest(root.schemaDigest, "schemaDigest"), catalogDigest: digest(root.catalogDigest, "catalogDigest"), lastMigrationId: id(root.lastMigrationId ?? "migration_none", "lastMigrationId") }); }
export function createNeonDatabaseMigrationSourceResolver(tenant: string = "*"): RegisteredSourceResolver { return Object.freeze({ tenant, resolverId: neonDatabaseMigrationResolverId, definitionDigest: neonDatabaseMigrationDefinitionDigest, projectionSchemaId: neonDatabaseMigrationProjectionSchemaId, readEndpointIds: [neonDatabaseMigrationReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: neonDatabaseMigrationReadEndpointId, opaqueHandle: refs.database }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>) => { if (input.observations.length !== 1) throw new TypeError("Neon catalog source requires one observation"); const projection = normalize(Buffer.from(input.observations[0].bodyBase64, "base64")); const sourceIdentity = `neon.${projection.projectId}.${projection.branchId}.${projection.databaseId}`; const triggerIdentity = authorityDigest({ v: "reelier.neon-migration-trigger/v1", sourceIdentity, schemaDigest: projection.schemaDigest, lastMigrationId: projection.lastMigrationId }).replace(":", "."); const claims = Object.keys(projection).map(key => ({ claimId: `neon-${key}`, projectionPointer: `/${key}` })); return Object.freeze({ sourceIdentity, triggerIdentity, projection, claims: Object.freeze({ grounded: Object.freeze(claims), authored: Object.freeze([]), unresolved: Object.freeze([]) }) }) satisfies SourceProjection; } }); }
