import { authorityDigest } from "../../authority/wire.js";
import type { PackReconciliationResult } from "../types.js";
import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import type { StaticPackDefinition } from "../../authority/pack.js";
import type { TransportEffect } from "../../authority/types.js";

export const stripeRefundIssueAlias = "stripe_refund_issue_v1" as const;
export const stripeResolverId = "stripe_charge_source_v1" as const;
export const stripeProjectionSchemaId = "stripe_charge_projection_v1" as const;
export const stripePolicySchemaId = "stripe_refund_policy_v1" as const;
export const stripeReadEndpointId = "stripe.charges.get" as const;
export const stripeWriteEndpointId = "stripe.refunds.create" as const;
export const stripePackDigest = authorityDigest({ v: "reelier.outcome-pack/v1", packId: "stripe", definitions: [stripeRefundIssueAlias] });
export const stripeDefinitionDigest = authorityDigest({ v: "reelier.outcome-pack-definition/v1", alias: stripeRefundIssueAlias, packDigest: stripePackDigest });
export interface StripeRefundProjection extends Record<string, unknown> { readonly chargeId: string; readonly customerEmail: string; readonly gmailSender?: string; readonly currency: string; readonly amount: number; readonly amountRefunded: number; readonly paid: boolean; }
export interface StripeRefundPolicy { readonly currency: string; readonly maxRefund: number; readonly maxChargeAgeSeconds: number; }
export function parseStripeRefundPolicy(value: unknown): StripeRefundPolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Stripe refund policy must be an object"); const raw = value as Record<string, unknown>; if (Object.keys(raw).some(k => !["currency", "maxRefund", "maxChargeAgeSeconds"].includes(k)) || typeof raw.currency !== "string" || !/^[a-z]{3}$/.test(raw.currency) || typeof raw.maxRefund !== "number" || !Number.isSafeInteger(raw.maxRefund) || raw.maxRefund <= 0 || typeof raw.maxChargeAgeSeconds !== "number" || !Number.isSafeInteger(raw.maxChargeAgeSeconds) || raw.maxChargeAgeSeconds < 1) throw new TypeError("Stripe refund policy is closed and bounded"); return Object.freeze({ currency: raw.currency, maxRefund: raw.maxRefund, maxChargeAgeSeconds: raw.maxChargeAgeSeconds }); }
export function compileStripeRefund(input: Readonly<{ source: StripeRefundProjection; policy: StripeRefundPolicy; gmailSender: string; now: Date; tenant: string; definition: string; }>): Readonly<TransportEffect & { idempotencyKey: string }> {
  if (!input.source.paid || input.source.amount <= input.source.amountRefunded || input.source.currency !== input.policy.currency || input.source.amount - input.source.amountRefunded > input.policy.maxRefund) throw new TypeError("charge is not eligible for full refund");
  if (input.source.customerEmail.toLowerCase() !== input.gmailSender.toLowerCase()) throw new TypeError("Gmail sender does not match Stripe customer");
  const idempotencyKey = `reelier-${authorityDigest({ v: "reelier.stripe-refund-key/v1", tenant: input.tenant, definition: input.definition, chargeId: input.source.chargeId }).slice(7)}`;
  return withMetadata({ v: "reelier.transport-effect/v1", endpointId: "stripe.refunds.create", method: "POST", path: "/v1/refunds", query: "", headers: { "Content-Type": "application/x-www-form-urlencoded", "Idempotency-Key": idempotencyKey }, bodyBase64: Buffer.from(`charge=${encodeURIComponent(input.source.chargeId)}`, "utf8").toString("base64"), riskClass: "stripe_refund", idempotency: "native", preconditions: [], reconciliation: { recipeId: "stripe_refund_readback_v1" } }, "idempotencyKey", idempotencyKey);
}
export function reconcileStripeRefund(input: Readonly<{ chargeId: string; expectedAmount: number; response: unknown }>): PackReconciliationResult { const body = input.response && typeof input.response === "object" && "body" in input.response ? (input.response as { status?: number; body: unknown }) : { body: input.response }; if (body.status && body.status >= 500) return Object.freeze({ status: "unavailable", recipeId: "stripe_refund_readback_v1", projectionDigest: null, reasonCode: "stripe-provider-error" }); const value = body.body && typeof body.body === "object" ? body.body as Record<string, unknown> : {}; if (String(value.charge ?? "") !== input.chargeId) return Object.freeze({ status: "conflict", recipeId: "stripe_refund_readback_v1", projectionDigest: null, reasonCode: "charge-mismatch" }); const amount = Number(value.amount ?? 0); const digest = authorityDigest({ v: "reelier.stripe-refund/v1", charge: input.chargeId, amount }); return Object.freeze({ status: amount === input.expectedAmount ? "matched" : "conflict", recipeId: "stripe_refund_readback_v1", projectionDigest: digest, reasonCode: amount === input.expectedAmount ? "refund-match" : "refund-amount-conflict" }); }
export function createStripeSourceResolver(tenant = "*"): RegisteredSourceResolver { return Object.freeze({ tenant, resolverId: stripeResolverId, definitionDigest: stripeDefinitionDigest, projectionSchemaId: stripeProjectionSchemaId, readEndpointIds: [stripeReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: stripeReadEndpointId, opaqueHandle: refs.charge }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>): SourceProjection => { if (input.observations.length !== 1) throw new TypeError("Stripe source requires one charge observation"); const raw = JSON.parse(Buffer.from(input.observations[0].bodyBase64, "base64").toString("utf8")) as Record<string, unknown>; const projection = { chargeId: String(raw.chargeId ?? raw.id ?? ""), customerEmail: String(raw.customerEmail ?? ""), gmailSender: String(raw.gmailSender ?? ""), currency: String(raw.currency ?? ""), amount: Number(raw.amount ?? 0), amountRefunded: Number(raw.amountRefunded ?? 0), paid: raw.paid === true }; if (!projection.chargeId || !projection.customerEmail || !projection.gmailSender || !projection.currency || !Number.isSafeInteger(projection.amount) || !Number.isSafeInteger(projection.amountRefunded)) throw new TypeError("Stripe projection is incomplete"); return { sourceIdentity: `stripe.charge.${projection.chargeId}`, triggerIdentity: authorityDigest({ v: "reelier.stripe-trigger/v1", chargeId: projection.chargeId, amountRefunded: projection.amountRefunded }), projection, claims: { grounded: Object.keys(projection).map(key => ({ claimId: `stripe-${key}`, projectionPointer: `/${key}` })), authored: [], unresolved: [] } }; } }); }
export const stripeManifest = Object.freeze({ v: "reelier.outcome-pack-manifest/v1" as const, packId: "stripe", packDigest: stripePackDigest, definitions: [stripeRefundIssueAlias] });
const emptyChoices = (value: unknown): Record<string, never> => { if (!value || typeof value !== "object" || Object.keys(value as object).length) throw new TypeError("Stripe choices must be empty"); return {}; };
export const stripeRefundDefinition: StaticPackDefinition = Object.freeze({ alias: stripeRefundIssueAlias, packDigest: stripePackDigest, definitionDigest: stripeDefinitionDigest, resolverId: stripeResolverId, projectionSchemaId: stripeProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [stripeReadEndpointId], writeEndpointIds: [stripeWriteEndpointId], riskClasses: ["stripe_refund"], policySchemaId: stripePolicySchemaId, requiredGroundedPointers: ["/chargeId", "/customerEmail", "/gmailSender", "/currency", "/amount", "/amountRefunded", "/paid"], validateChoices: emptyChoices, parsePolicy: parseStripeRefundPolicy, compile: (input: import("../../authority/pack.js").StaticPackCompileInput) => compileStripeRefund({ source: input.source.projection as StripeRefundProjection, policy: input.policy as StripeRefundPolicy, gmailSender: String((input.source.projection as Record<string, unknown>).gmailSender ?? ""), now: input.now, tenant: input.contract.tenant, definition: stripeRefundIssueAlias }) });
function withMetadata<T extends object, K extends string, V>(effect: T, key: K, value: V): T & Record<K, V> { Object.defineProperty(effect, key, { value, enumerable: false, writable: false, configurable: false }); return Object.freeze(effect) as T & Record<K, V>; }
