import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { TransportEffect } from "../../authority/types.js";
import { vercelProjectEnvironmentSecretSetRecipeId, vercelProjectEnvironmentSecretSetRiskClass, vercelProjectEnvironmentSecretSetWriteEndpointId, type VercelProjectEnvironmentSecretSetPolicy } from "./manifest.js";
export type { VercelProjectEnvironmentSecretSetPolicy } from "./manifest.js";
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Vercel environment ${label} is invalid`); return value; }
function digest(value: unknown): string { if (typeof value !== "string" || !/^sha256:[0-9a-f]{64}$/.test(value)) throw new TypeError("Vercel environment secretDigest is invalid"); return value; }
export function parseVercelProjectEnvironmentSecretSetPolicy(value: unknown): VercelProjectEnvironmentSecretSetPolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Vercel environment secret policy must be an object"); const raw = value as Record<string, unknown>; const keys = ["teamId", "projectId", "environment", "key", "secretDigest"]; if (Object.keys(raw).length !== keys.length || Object.keys(raw).some(key => !keys.includes(key))) throw new TypeError("Vercel environment secret policy is closed"); const environment = raw.environment; if (environment !== "production" && environment !== "preview") throw new TypeError("Vercel sensitive environment must be production or preview"); const key = id(raw.key, "key"); if (!/^[A-Z][A-Z0-9_]{0,127}$/.test(key)) throw new TypeError("Vercel environment key is invalid"); return Object.freeze({ teamId: id(raw.teamId, "teamId"), projectId: id(raw.projectId, "projectId"), environment, key, secretDigest: digest(raw.secretDigest) }); }
export function compileVercelProjectEnvironmentSecretSet(input: Readonly<{ policy: VercelProjectEnvironmentSecretSetPolicy | Omit<VercelProjectEnvironmentSecretSetPolicy, "secretDigest">; secret?: Readonly<{ digest: string }> }>): TransportEffect { const raw = input.policy as VercelProjectEnvironmentSecretSetPolicy; const policy = raw.secretDigest ? parseVercelProjectEnvironmentSecretSetPolicy(raw) : parseVercelProjectEnvironmentSecretSetPolicy({ ...raw, secretDigest: input.secret?.digest }); const body = authorityCanonicalBytes({ teamId: policy.teamId, projectId: policy.projectId, environment: policy.environment, key: policy.key, secretDigest: policy.secretDigest }); return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: vercelProjectEnvironmentSecretSetWriteEndpointId, method: "POST", path: `/v10/projects/${policy.projectId}/env`, query: `teamId=${encodeURIComponent(policy.teamId)}`, headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: vercelProjectEnvironmentSecretSetRiskClass, idempotency: "native", preconditions: [{ kind: "vercel-environment-secret-policy", digest: authorityDigest({ v: "reelier.vercel-environment-secret-policy/v1", ...policy }) }], reconciliation: { recipeId: vercelProjectEnvironmentSecretSetRecipeId } }); }
export function parseVercelProjectEnvironmentSecretSetEffect(effect: unknown): VercelProjectEnvironmentSecretSetPolicy { if (!effect || typeof effect !== "object") throw new TypeError("Vercel environment secret effect is invalid"); const raw = effect as Record<string, unknown>; if (raw.endpointId !== vercelProjectEnvironmentSecretSetWriteEndpointId || typeof raw.bodyBase64 !== "string") throw new TypeError("Vercel environment secret effect is invalid"); let body: unknown; try { body = JSON.parse(Buffer.from(raw.bodyBase64, "base64").toString("utf8")); } catch { throw new TypeError("Vercel environment secret effect body is invalid"); } const record = body as Record<string, unknown>; return parseVercelProjectEnvironmentSecretSetPolicy(record); }
