import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { StaticPackCompileInput, StaticPackDefinition } from "../../authority/pack.js";
import { vercelDeploymentReleaseAlias, vercelDeploymentReleaseDefinitionDigest, vercelDeploymentReleasePackDigest, vercelDeploymentReleasePolicySchemaId, vercelDeploymentReleaseProjectionSchemaId, vercelDeploymentReleaseReadEndpointId, vercelDeploymentReleaseRecipeId, vercelDeploymentReleaseResolverId, vercelDeploymentReleaseRiskClass, vercelDeploymentReleaseWriteEndpointId } from "./manifest.js";
import type { VercelDeploymentReleaseProjection } from "./manifest.js";

export interface VercelDeploymentReleasePolicy { readonly teamId: string; readonly projectId: string; readonly allowedDomains: readonly string[] }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value) || value === "." || value === "..") throw new TypeError(`Vercel ${label} is invalid`); return value; }
function domains(value: unknown): readonly string[] { if (!Array.isArray(value) || value.length === 0 || value.length > 64 || value.some(item => typeof item !== "string" || !/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(item))) throw new TypeError("Vercel allowedDomains must be bounded DNS names"); const result = [...value] as string[]; if (new Set(result).size !== result.length) throw new TypeError("Vercel allowedDomains must be unique"); return Object.freeze(result.sort(compareText)); }
export function validateVercelDeploymentReleaseChoices(value: unknown): Record<string, never> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 0) throw new TypeError("Vercel deployment release choices must be empty"); return Object.freeze({}); }
export function parseVercelDeploymentReleasePolicy(value: unknown): VercelDeploymentReleasePolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Vercel deployment release policy must be an object"); const raw = value as Record<string, unknown>; if (Object.keys(raw).length !== 3 || Object.keys(raw).some(key => !["teamId", "projectId", "allowedDomains"].includes(key))) throw new TypeError("Vercel deployment release policy is closed"); return Object.freeze({ teamId: id(raw.teamId, "teamId"), projectId: id(raw.projectId, "projectId"), allowedDomains: domains(raw.allowedDomains) }); }
export function compileVercelDeploymentRelease(input: Readonly<{ source: VercelDeploymentReleaseProjection; policy: VercelDeploymentReleasePolicy }>): Readonly<{ v: "reelier.transport-effect/v1"; endpointId: string; method: "POST"; path: string; query: string; headers: Record<string, string>; bodyBase64: string; riskClass: string; idempotency: "native"; preconditions: { kind: string; digest: string }[]; reconciliation: { recipeId: string } }> { const { source, policy } = input; if (source.teamId !== policy.teamId || source.projectId !== policy.projectId) throw new TypeError("Vercel deployment account or project is outside the signed policy"); if (source.currentProductionDeploymentId === source.deploymentId) throw new TypeError("Vercel deployment is already production"); if (source.checks.some(check => check.status !== "passed")) throw new TypeError("Vercel deployment checks are not all passed"); if (!same(source.domains, policy.allowedDomains)) throw new TypeError("Vercel deployment domains are outside the signed policy"); const body = authorityCanonicalBytes({ projectId: source.projectId, target: "production" }); const query = `teamId=${encodeURIComponent(source.teamId)}`; return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: vercelDeploymentReleaseWriteEndpointId, method: "POST", path: `/v13/deployments/${source.deploymentId}/promote`, query, headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: vercelDeploymentReleaseRiskClass, idempotency: "native", preconditions: [{ kind: "vercel-production-deployment", digest: authorityDigest({ v: "reelier.vercel-production/v1", teamId: source.teamId, projectId: source.projectId, deploymentId: source.currentProductionDeploymentId }) }, { kind: "vercel-deployment-commit", digest: authorityDigest({ v: "reelier.vercel-commit/v1", deploymentId: source.deploymentId, commitSha: source.commitSha }) }, { kind: "vercel-deployment-checks", digest: authorityDigest({ v: "reelier.vercel-checks/v1", deploymentId: source.deploymentId, checks: source.checks }) }, { kind: "vercel-deployment-domains", digest: authorityDigest({ v: "reelier.vercel-domains/v1", deploymentId: source.deploymentId, domains: source.domains }) }], reconciliation: { recipeId: vercelDeploymentReleaseRecipeId } }); }
export const vercelDeploymentReleaseDefinition: StaticPackDefinition = Object.freeze({ alias: vercelDeploymentReleaseAlias, packDigest: vercelDeploymentReleasePackDigest, definitionDigest: vercelDeploymentReleaseDefinitionDigest, resolverId: vercelDeploymentReleaseResolverId, projectionSchemaId: vercelDeploymentReleaseProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [vercelDeploymentReleaseReadEndpointId], writeEndpointIds: [vercelDeploymentReleaseWriteEndpointId], riskClasses: [vercelDeploymentReleaseRiskClass], policySchemaId: vercelDeploymentReleasePolicySchemaId, requiredGroundedPointers: ["/teamId", "/projectId", "/deploymentId", "/deploymentUrl", "/commitSha", "/checks", "/domains", "/currentProductionDeploymentId"], validateChoices: validateVercelDeploymentReleaseChoices, parsePolicy: parseVercelDeploymentReleasePolicy, compile: (input: StaticPackCompileInput) => compileVercelDeploymentRelease({ source: input.source.projection as VercelDeploymentReleaseProjection, policy: input.policy as VercelDeploymentReleasePolicy }) });
function same(left: readonly string[], right: readonly string[]): boolean { return left.length === right.length && left.every((value, index) => value === right[index]); }
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
