import { authorityDigest } from "../../authority/wire.js";
import type { PackReconciliationResult, ProviderResponse } from "../types.js";
import type { VercelDeploymentReleaseProjection } from "./manifest.js";
import { vercelDeploymentReleaseRecipeId } from "./manifest.js";

export function reconcileVercelDeploymentRelease(input: Readonly<{ expected: VercelDeploymentReleaseProjection; response: ProviderResponse | unknown }>): PackReconciliationResult { const response = normalize(input.response); if (response.status === 404) return result("not-applied", "vercel-deployment-not-found", null); if (response.status !== undefined && response.status >= 500) return result("unavailable", "vercel-provider-error", null); if (response.status !== undefined && response.status >= 400) return result("unavailable", "vercel-provider-refused", null); try { const body = response.body && typeof response.body === "object" && !Array.isArray(response.body) ? response.body as Record<string, unknown> : {}; const actual = { teamId: String(body.teamId ?? ""), projectId: String(body.projectId ?? ""), deploymentId: String(body.deploymentId ?? body.id ?? body.uid ?? ""), commitSha: String(body.commitSha ?? ""), target: String(body.target ?? ""), domains: Array.isArray(body.domains) ? body.domains.map(item => typeof item === "string" ? item.toLowerCase() : "").sort(compareText) : [], currentProductionDeploymentId: String(body.currentProductionDeploymentId ?? body.productionDeploymentId ?? "") }; if (!actual.teamId || !actual.projectId || !actual.deploymentId || !/^[0-9a-f]{40}$/i.test(actual.commitSha) || actual.target !== "production" || !actual.currentProductionDeploymentId || actual.domains.some(item => !item)) return result("unavailable", "malformed-provider-state", null); const digest = authorityDigest({ v: "reelier.vercel-deployment-projection/v1", ...actual }); const matched = actual.teamId === input.expected.teamId && actual.projectId === input.expected.projectId && actual.deploymentId === input.expected.deploymentId && actual.commitSha === input.expected.commitSha && actual.currentProductionDeploymentId === input.expected.deploymentId && same(actual.domains, input.expected.domains); return result(matched ? "matched" : "conflict", matched ? "vercel-production-match" : "vercel-production-conflict", digest); } catch { return result("unavailable", "malformed-provider-state", null); } }
function normalize(value: ProviderResponse | unknown): ProviderResponse { return value && typeof value === "object" && "body" in value ? value as ProviderResponse : { body: value }; }
function result(status: PackReconciliationResult["status"], reasonCode: string, projectionDigest: string | null): PackReconciliationResult { return Object.freeze({ status, recipeId: vercelDeploymentReleaseRecipeId, projectionDigest, reasonCode }); }
function same(left: readonly string[], right: readonly string[]): boolean { return left.length === right.length && left.every((value, index) => value === right[index]); }
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
