import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import { authorityDigest } from "../../authority/wire.js";
import { vercelDeploymentReleaseDefinitionDigest, vercelDeploymentReleaseProjectionSchemaId, vercelDeploymentReleaseReadEndpointId, vercelDeploymentReleaseResolverId } from "./manifest.js";
import type { VercelDeploymentCheck, VercelDeploymentReleaseProjection } from "./manifest.js";

function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Vercel deployment response must be an object"); return value as Record<string, unknown>; }
function string(value: unknown, label: string): string { if (typeof value !== "string" || value.length === 0 || value.length > 256) throw new TypeError(`Vercel deployment ${label} is invalid`); return value; }
function id(value: unknown, label: string): string { const result = string(value, label); if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(result) || result === "." || result === "..") throw new TypeError(`Vercel deployment ${label} is not a safe identifier`); return result; }
function url(value: unknown): string { const result = string(value, "url"); let parsed: URL; try { parsed = new URL(result); } catch { throw new TypeError("Vercel deployment url is invalid"); } if (parsed.protocol !== "https:" || parsed.username || parsed.password || parsed.search || parsed.hash || parsed.pathname !== "/") throw new TypeError("Vercel deployment url must be a bare HTTPS origin"); return result; }
function domain(value: unknown): string { const result = string(value, "domain").toLowerCase(); if (result.length > 253 || !/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(result)) throw new TypeError("Vercel deployment domain is invalid"); return result; }
function checks(value: unknown): readonly VercelDeploymentCheck[] { if (!Array.isArray(value) || value.length === 0 || value.length > 128) throw new TypeError("Vercel deployment checks are invalid"); const result = value.map(item => { const check = object(item); const name = string(check.name, "check name"); if (name.length > 128 || !/^[A-Za-z0-9._:-]+$/.test(name)) throw new TypeError("Vercel check name is invalid"); const status = check.status; if (status !== "passed" && status !== "failed" && status !== "pending" && status !== "skipped") throw new TypeError("Vercel check status is invalid"); return Object.freeze({ name, status }); }); if (new Set(result.map(item => item.name)).size !== result.length) throw new TypeError("Vercel deployment checks must be unique"); return Object.freeze([...result].sort((left, right) => left.name < right.name ? -1 : left.name > right.name ? 1 : 0)); }
function normalize(rawBytes: Uint8Array): VercelDeploymentReleaseProjection { let parsed: unknown; try { parsed = JSON.parse(Buffer.from(rawBytes).toString("utf8")); } catch { throw new TypeError("Vercel deployment response is not JSON"); } const root = object(parsed); const rawDomains = root.domains; if (!Array.isArray(rawDomains) || rawDomains.length === 0 || rawDomains.length > 64) throw new TypeError("Vercel deployment domains are invalid"); const domains = [...new Set(rawDomains.map(domain))].sort(compareText); if (domains.length !== rawDomains.length) throw new TypeError("Vercel deployment domains must be unique"); const projection = Object.freeze({ teamId: id(root.teamId ?? object(root.team).id, "teamId"), projectId: id(root.projectId ?? object(root.project).id, "projectId"), deploymentId: id(root.deploymentId ?? root.id ?? root.uid, "deploymentId"), deploymentUrl: url(root.deploymentUrl ?? root.url), commitSha: string(root.commitSha ?? object(root.meta).githubCommitSha, "commitSha"), checks: checks(root.checks ?? root.deploymentChecks), domains: Object.freeze(domains), currentProductionDeploymentId: id(root.currentProductionDeploymentId ?? root.productionDeploymentId, "currentProductionDeploymentId") }); if (!/^[0-9a-f]{40}$/i.test(projection.commitSha)) throw new TypeError("Vercel deployment commitSha must be a 40-character SHA"); return projection; }

export function createVercelDeploymentReleaseSourceResolver(tenant: string = "*"): RegisteredSourceResolver { if (typeof tenant !== "string" || tenant.length === 0) throw new TypeError("tenant is required"); return Object.freeze({ tenant, resolverId: vercelDeploymentReleaseResolverId, definitionDigest: vercelDeploymentReleaseDefinitionDigest, projectionSchemaId: vercelDeploymentReleaseProjectionSchemaId, readEndpointIds: [vercelDeploymentReleaseReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: vercelDeploymentReleaseReadEndpointId, opaqueHandle: refs.deployment }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>) => { if (input.observations.length !== 1) throw new TypeError("Vercel deployment source requires one observation"); const projection = normalize(Buffer.from(input.observations[0].bodyBase64, "base64")); const sourceIdentity = `vercel.${projection.teamId}.${projection.projectId}.${projection.deploymentId}`; const triggerIdentity = safeDigest(authorityDigest({ v: "reelier.vercel-deployment-trigger/v1", sourceIdentity, commitSha: projection.commitSha, currentProductionDeploymentId: projection.currentProductionDeploymentId })); const claims = Object.keys(projection).map(key => ({ claimId: `vercel-${key}`, projectionPointer: `/${key}` })); return Object.freeze({ sourceIdentity, triggerIdentity, projection, claims: Object.freeze({ grounded: Object.freeze(claims), authored: Object.freeze([]), unresolved: Object.freeze([]) }) }) satisfies SourceProjection; } }); }
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
function safeDigest(value: string): string { return value.replace(":", "."); }
