import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { PackReconciliationResult } from "../types.js";
import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import type { StaticPackDefinition } from "../../authority/pack.js";

export const gmailReplySendAlias = "gmail_reply_send_v1" as const;
export const gmailThreadLabelsAlias = "gmail_thread_labels_set_v1" as const;
export const gmailResolverId = "gmail_thread_source_v1" as const;
export const gmailLabelsResolverId = "gmail_thread_labels_source_v1" as const;
export const gmailProjectionSchemaId = "gmail_thread_projection_v1" as const;
export const gmailPolicySchemaId = "gmail_policy_v1" as const;
export const gmailReadEndpointId = "gmail.threads.get" as const;
export const gmailReplyWriteEndpointId = "gmail.users.messages.send" as const;
export const gmailLabelsWriteEndpointId = "gmail.users.threads.modify" as const;
export const gmailPackDigest = authorityDigest({ v: "reelier.outcome-pack/v1", packId: "gmail", definitions: [gmailReplySendAlias, gmailThreadLabelsAlias] });
export const gmailReplyDefinitionDigest = authorityDigest({ v: "reelier.outcome-pack-definition/v1", alias: gmailReplySendAlias, packDigest: gmailPackDigest });
export const gmailLabelsDefinitionDigest = authorityDigest({ v: "reelier.outcome-pack-definition/v1", alias: gmailThreadLabelsAlias, packDigest: gmailPackDigest });
export interface GmailThreadProjection extends Record<string, unknown> { readonly threadId: string; readonly messageId: string; readonly recipient: string; readonly subject: string; readonly labelIds: readonly string[]; }
export interface GmailReplyPolicy { readonly text: string; }
export interface GmailLabelsPolicy { readonly addLabelIds: readonly string[]; readonly removeLabelIds: readonly string[]; }

export function parseGmailReplyPolicy(value: unknown): GmailReplyPolicy {
  if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 1 || typeof (value as Record<string, unknown>).text !== "string" || !(value as Record<string, string>).text.length || Buffer.byteLength((value as Record<string, string>).text, "utf8") > 256 * 1024) throw new TypeError("Gmail reply policy must contain bounded plain text");
  return Object.freeze({ text: (value as Record<string, string>).text });
}
export function parseGmailLabelsPolicy(value: unknown): GmailLabelsPolicy {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Gmail label policy must be an object");
  const raw = value as Record<string, unknown>; const valid = (v: unknown): readonly string[] => { if (!Array.isArray(v) || v.some(x => typeof x !== "string" || !x) || new Set(v).size !== v.length) throw new TypeError("label ids must be unique strings"); return Object.freeze([...v].sort()); };
  if (Object.keys(raw).some(k => k !== "addLabelIds" && k !== "removeLabelIds")) throw new TypeError("Gmail label policy is closed");
  return Object.freeze({ addLabelIds: valid(raw.addLabelIds ?? []), removeLabelIds: valid(raw.removeLabelIds ?? []) });
}
function encodeHeader(value: string): string { return value.replace(/[\r\n]/g, ""); }
export function compileGmailReply(input: Readonly<{ source: GmailThreadProjection; policy: GmailReplyPolicy; outcomeKey: string }>): Readonly<{ v: "reelier.transport-effect/v1"; endpointId: string; method: "POST"; path: string; query: string; headers: Record<string, string>; bodyBase64: string; messageId: string; }> {
  const messageId = `<reelier-${authorityDigest({ v: "reelier.gmail-message-id/v1", outcomeKey: input.outcomeKey, threadId: input.source.threadId }).slice(7)}@reelier.local>`;
  const mime = [`To: ${encodeHeader(input.source.recipient)}`, `Subject: ${encodeHeader(input.source.subject.startsWith("Re:") ? input.source.subject : `Re: ${input.source.subject}`)}`, `In-Reply-To: ${encodeHeader(input.source.messageId)}`, `References: ${encodeHeader(input.source.messageId)}`, `Message-ID: ${messageId}`, "Content-Type: text/plain; charset=utf-8", "MIME-Version: 1.0", "", input.policy.text].join("\r\n");
  const body = authorityCanonicalBytes({ raw: Buffer.from(mime, "utf8").toString("base64url") });
  return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: "gmail.users.messages.send", method: "POST", path: "/gmail/v1/users/me/messages/send", query: "", headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), messageId });
}
export function compileGmailLabels(input: Readonly<{ source: GmailThreadProjection; policy: GmailLabelsPolicy }>): unknown {
  return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: "gmail.users.threads.modify", method: "POST", path: `/gmail/v1/users/me/threads/${encodeURIComponent(input.source.threadId)}/modify`, query: "", headers: { "Content-Type": "application/json" }, bodyBase64: authorityCanonicalBytes({ addLabelIds: input.policy.addLabelIds, removeLabelIds: input.policy.removeLabelIds }).toString("base64"), riskClass: "gmail_thread_labels", idempotency: "reconcile-only", preconditions: [{ kind: "gmail-labels-digest", digest: authorityDigest({ v: "reelier.gmail-labels/v1", labelIds: [...input.source.labelIds].sort() }) }], reconciliation: { recipeId: "gmail_thread_labels_readback_v1" } });
}
export function reconcileGmailReply(input: Readonly<{ expectedMessageId: string; response: unknown }>): PackReconciliationResult {
  const body = normalizeBody(input.response); if (body.status && body.status >= 500) return result("unavailable", "gmail-provider-error", null, "gmail_reply_send_readback_v1");
  const messageId = typeof body.body === "object" && body.body !== null ? String((body.body as Record<string, unknown>).messageId ?? (body.body as Record<string, unknown>).rfc822msgid ?? "") : "";
  return messageId === input.expectedMessageId ? result("matched", "gmail-message-identity-matched", authorityDigest({ v: "reelier.gmail-message/v1", messageId }), "gmail_reply_send_readback_v1") : result("not-applied", "gmail-message-not-found", null, "gmail_reply_send_readback_v1");
}
export function reconcileGmailLabels(input: Readonly<{ expected: readonly string[]; response: unknown }>): PackReconciliationResult { const body = normalizeBody(input.response); if (body.status && body.status >= 500) return result("unavailable", "gmail-provider-error", null, "gmail_thread_labels_readback_v1"); const labels = body.body && typeof body.body === "object" && Array.isArray((body.body as Record<string, unknown>).labelIds) ? (body.body as { labelIds: unknown[] }).labelIds.filter((x): x is string => typeof x === "string").sort() : []; const expected = [...input.expected].sort(); const same = labels.length === expected.length && labels.every((x, i) => x === expected[i]); return result(same ? "matched" : "conflict", same ? "gmail-labels-match" : "gmail-labels-conflict", authorityDigest({ v: "reelier.gmail-labels/v1", labelIds: labels }), "gmail_thread_labels_readback_v1"); }
export function createGmailSourceResolver(tenant = "*", labels = false): RegisteredSourceResolver { return Object.freeze({ tenant, resolverId: labels ? gmailLabelsResolverId : gmailResolverId, definitionDigest: labels ? gmailLabelsDefinitionDigest : gmailReplyDefinitionDigest, projectionSchemaId: gmailProjectionSchemaId, readEndpointIds: [gmailReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: gmailReadEndpointId, opaqueHandle: refs.thread }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>): SourceProjection => { if (input.observations.length !== 1) throw new TypeError("Gmail source requires one thread observation"); const raw = JSON.parse(Buffer.from(input.observations[0].bodyBase64, "base64").toString("utf8")) as Record<string, unknown>; const projection = { threadId: String(raw.threadId ?? ""), messageId: String(raw.messageId ?? ""), recipient: String(raw.recipient ?? ""), subject: String(raw.subject ?? ""), labelIds: Array.isArray(raw.labelIds) ? raw.labelIds.filter((x): x is string => typeof x === "string").sort() : [] }; if (Object.values(projection).some(x => typeof x === "string" && !x)) throw new TypeError("Gmail projection missing required identity"); return { sourceIdentity: `gmail.thread.${projection.threadId}`, triggerIdentity: authorityDigest({ v: "reelier.gmail-trigger/v1", threadId: projection.threadId, messageId: projection.messageId }), projection, claims: { grounded: Object.keys(projection).map(key => ({ claimId: `gmail-${key}`, projectionPointer: `/${key}` })), authored: [], unresolved: [] } }; } }); }
export const gmailReplyManifest = Object.freeze({ v: "reelier.outcome-pack-manifest/v1" as const, packId: "gmail", packDigest: gmailPackDigest, definitions: [gmailReplySendAlias] });
export const gmailLabelsManifest = Object.freeze({ v: "reelier.outcome-pack-manifest/v1" as const, packId: "gmail_labels", packDigest: gmailPackDigest, definitions: [gmailThreadLabelsAlias] });
const emptyChoices = (value: unknown): Record<string, never> => { if (!value || typeof value !== "object" || Object.keys(value as object).length) throw new TypeError("Gmail choices must be empty"); return {}; };
export const gmailReplyDefinition: StaticPackDefinition = Object.freeze({ alias: gmailReplySendAlias, packDigest: gmailPackDigest, definitionDigest: gmailReplyDefinitionDigest, resolverId: gmailResolverId, projectionSchemaId: gmailProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [gmailReadEndpointId], writeEndpointIds: [gmailReplyWriteEndpointId], riskClasses: ["gmail_send"], policySchemaId: gmailPolicySchemaId, requiredGroundedPointers: ["/threadId", "/messageId", "/recipient", "/subject", "/labelIds"], validateChoices: emptyChoices, parsePolicy: parseGmailReplyPolicy, compile: (input: import("../../authority/pack.js").StaticPackCompileInput) => compileGmailReply({ source: input.source.projection as GmailThreadProjection, policy: input.policy as GmailReplyPolicy, outcomeKey: authorityDigest(input.source.projection) }) });
export const gmailLabelsDefinition: StaticPackDefinition = Object.freeze({ ...gmailReplyDefinition, alias: gmailThreadLabelsAlias, definitionDigest: gmailLabelsDefinitionDigest, resolverId: gmailLabelsResolverId, writeEndpointIds: [gmailLabelsWriteEndpointId], riskClasses: ["gmail_thread_labels"], parsePolicy: parseGmailLabelsPolicy, compile: (input: import("../../authority/pack.js").StaticPackCompileInput) => compileGmailLabels({ source: input.source.projection as GmailThreadProjection, policy: input.policy as GmailLabelsPolicy }) });
function normalizeBody(value: unknown): { status?: number; body: unknown } { return value && typeof value === "object" && "body" in value ? value as { status?: number; body: unknown } : { body: value }; }
function result(status: PackReconciliationResult["status"], reasonCode: string, projectionDigest: string | null, recipeId: string): PackReconciliationResult { return Object.freeze({ status, reasonCode, projectionDigest, recipeId }); }
