/** Portable Path C ABI: closed wire schemas, JCS digests, signatures, and offline bundle verification. */
export * from "./types.js";
export { authorityCanonicalBytes, authorityDigest, parseAuthorityWire, parseCanonicalAuthorityJson, parsePortableAuthorityEvidence, assertAcceptedDecisionContext, decisionContextPresence } from "./wire.js";
export { AUTHORITY_ADAPTER_CONTRACT_V1, AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST, verifyAuthorityAdapterContractV1, type AuthorityAdapterContractV1 } from "./adapter-contract.js";
export { signAuthorityDigest, verifyAuthoritySignature } from "./crypto.js";
export {
  parseToolEffectContractV1,
  digestToolEffectContractV1,
  parseGovernedOutcomeV1,
  digestGovernedOutcomeV1,
  parseEffectReservationV1,
  digestEffectReservationV1,
  parseAttemptV1,
  digestAttemptV1,
  parseObservationV1,
  digestObservationV1,
  parseProviderOutcomePackV1,
  digestProviderOutcomePackV1,
  parseMissionClaimV1,
  digestMissionClaimV1,
  parseGovernedReceiptV1,
  digestGovernedReceiptV1,
  verifyGovernedOutcomeTransitionV1,
  type EvidenceGradeV1,
  type GovernedEffectClassV1,
  type ToolEffectContractV1,
  type ProviderOutcomePackV1,
  type MissionClaimV1,
  type EffectReservationV1,
  type AttemptV1,
  type ObservationV1,
  type GovernedOutcomeV1,
  type GovernedOutcomeVerificationContextV1,
  type GovernedReceiptV1,
} from "./tool-effect-contract.js";
export {
  AGENT_MANDATE_CONTRACT_V1,
  AGENT_MANDATE_CONTRACT_V1_DIGEST,
  parseAgentMandateV1,
  parseAgentMandateV2,
  parseAgentMandate,
  parseAgentDocumentV1,
  digestAgentMandateV1,
  digestAgentMandateV2,
  parseMandateLockV1,
  createMandateLockV1,
  verifyMandateLockV1,
  deriveMandatedMissionV1,
  deriveMandatedMissionV2,
  parseReconciledOutcomeV1,
  type AgentHarnessV1,
  type AgentDestinationV1,
  type ReconciledOutcomeStatusV1,
  type AgentMandateV1,
  type AgentMandateV2,
  type AgentMandate,
  type AgentDocumentV1,
  type MandateLockV1,
  type VerifiedMandateLockV1,
  type MandatedMissionV1,
  type MandatedMissionV2,
  type ReconciledOutcomeV1,
} from "./agent-mandate.js";
export {
  createApprovalReplayProtectorV1,
  parseCustomerAuthorityPayloadV1,
  parseTrustDomainDescriptorV1,
  parseCustomerApprovalProofV1,
  parseStandingAuthorityEnvelopeV1,
  parseHostedAuthorityEnvelopeV1,
  parseMissionChildGrantV1,
  verifyCustomerRootedAuthorityV1,
  type AuthorityLimitsV1,
  type CustomerAuthorityPurposeV1,
  type CustomerAuthorityPayloadV1,
  type TrustDomainDescriptorV1,
  type CustomerApprovalProofV1,
  type StandingAuthorityEnvelopeV1,
  type HostedAuthorityEnvelopeV1,
  type MissionChildGrantV1,
  type ApprovalReplayProtectorV1,
  type TrustedCustomerCredentialV1,
  type TrustedCustomerCredentialResolverV1,
  type VerifiedCustomerRootedAuthorityV1,
} from "./ambient-authority.js";
export {
  createSignedReleaseVerifierEvidenceV1,
  parseSignedReleaseVerifierEvidenceV1,
  createSignedStagedCandidateManifestV1,
  createSignedReleasePolicyV1,
  createSignedReleaseAuthorizationBundleV1,
  createSignedReleaseReceiptGraphV1,
  parseSignedStagedCandidateManifestV1,
  parseSignedReleasePolicyV1,
  parseSignedReleaseAuthorizationBundleV1,
  parseSignedReleaseReceiptGraphV1,
  parseCanonicalSignedReleaseAuthorizationBundleV1,
  parseCanonicalSignedStagedCandidateManifestV1,
  parseCanonicalSignedReleasePolicyV1,
  parseCanonicalSignedReleaseReceiptGraphV1,
  verifyReleaseAuthorizationBundleV1,
  verifyReleaseReceiptGraphV1,
  type ReleaseDestinationV1,
  type ReleaseProviderEffectV1,
  type ReleaseEvidenceStatus,
  type ReleaseEvidenceLaneV1,
  type ReleaseVerifierEvidenceV1,
  type StagedCandidateManifestV1,
  type ReleasePolicyV1,
  type ReleaseEffectAllocationV1,
  type ReleaseAuthorizationBundleV1,
  type ReleaseReceiptGraphMakerBindingV1,
  type ReleaseEvidenceVerifierBindingV1,
  type ReleaseReceiptGraphV1,
  type SignedReleaseArtifactV1,
  type SignedStagedCandidateManifestV1,
  type SignedReleasePolicyV1,
  type SignedReleaseAuthorizationBundleV1,
  type SignedReleaseReceiptGraphV1,
  type SignedReleaseVerifierEvidenceV1,
  type ReleaseContractSignerV1,
  type ReleaseContractVerifierV1,
  type ReleaseEvidenceVerificationV1,
  type VerifiedReleaseAuthorizationV1,
  type VerifiedReleaseReceiptGraphV1,
} from "./release-contracts.js";
export { createAuthorityEvidence, createAuthorityReceipt, createAuthorityReceiptBundle, parseAuthorityReceiptBundle, digestAuthorityReceiptBundle, authorityEvidenceCanonicalBytes } from "./evidence.js";
export { verifyAuthorityReceiptBundle, verifyAuthorityReceipt, type AuthorityReceiptVerificationOptions, type VerifiedAuthorityReceiptBundle } from "./verify.js";
export {
  verifyCertificationTaskReceiptGraph,
  type VerifiedCertificationTaskReceiptGraphV1,
} from "./certification/task-receipt-graph.js";
export { verifyNativeCandidate, type NativeCandidateV1, type NativeCandidateVerificationInputs } from "./certification/native-candidate.js";
export { normalizeSignedJobCard, signJobCard, signedJobCardDigest, verifySignedJobCard, type SignedJobCardV1, type UnsignedJobCardV1, type OutcomeSemanticClass } from "./job.js";
export {
  parseAuthorityKeyDescriptor,
  parseTrustEvents,
  parseSignedCertificationReadiness,
  verifySignedCertificationReadiness,
  type AuthorityKeyDescriptorV1,
  type TrustEventV1,
  type SignedCertificationReadinessV1,
} from "./certification/authority.js";
export { OUTCOME_PROFILE_CONTRACT_V1_DIGEST } from "./outcome-profile-contract.js";
export {
  createProfileVerificationRoots,
  parseOutcomeProfileDraft,
  parseProfileConformanceReport,
  parseSignedOutcomeProfileConformance,
  parseSignedTenantProfileActivation,
  parseAuthorityRouteScope,
  parseAuthorityDeploymentSnapshot,
  parseSignedProfileAuthorityBinding,
  parseProfileTrustPin,
  parseProfileGovernanceManifest,
  verifyProfileGovernanceOffline,
  type OutcomeProfileDraftV1,
  type ProfileConformanceReportV1,
  type SignedOutcomeProfileConformanceV1,
  type SignedTenantProfileActivationV1,
  type AuthorityRouteScopeV1,
  type AuthorityDeploymentSnapshotV1,
  type SignedProfileAuthorityBindingV1,
  type ProfileTrustPinV1,
  type ProfileGovernanceManifestV1,
  type ProfileVerificationAnchorV1,
  type ProfileVerificationRootsV1,
  type ProfileGovernanceVerificationV1,
  type ProfileGovernanceVerificationInputV1,
} from "./outcome-profile.js";
