/** Generated by scripts/build-outcome-profile-contract.mjs. */
export interface OutcomeProfileContractV1 {
  readonly v: "reelier.outcome-profile-contract/v1";
  readonly domain: "reelier.outcome-profile-contract/v1\\0";
  readonly members: readonly Readonly<{ path: string; digest: string }>[];
  readonly digest: string;
}

const generatedContract: OutcomeProfileContractV1 = {
  "v": "reelier.outcome-profile-contract/v1",
  "domain": "reelier.outcome-profile-contract/v1\\0",
  "members": [
    {
      "path": "profile-activation.schema.json",
      "digest": "sha256:7dedd304f3544be0c44e41abaf6ec9f980ded985c2c429a49518125f9a9c06a4"
    },
    {
      "path": "profile-conformance-report.schema.json",
      "digest": "sha256:4fb7e762b21b8d476681991847c7cb0b44693c3596204abc090048d6159c5e01"
    },
    {
      "path": "profile-conformance.schema.json",
      "digest": "sha256:8cd0ef4941f9f62d8555dfaa24ddb546ff307acc595118894d3dfbc0b453673c"
    },
    {
      "path": "profile-draft.schema.json",
      "digest": "sha256:0f5fd709479dce9c5238c4e5903740272625551b7062ef88db25beecca8f0504"
    },
    {
      "path": "profile-governance-manifest.schema.json",
      "digest": "sha256:a371027dcbdd48c405f3c70bba88537ac752576828339b3a489fe7d5657c7652"
    },
    {
      "path": "profile-governed-receipt.schema.json",
      "digest": "sha256:1ce428b5ccf6c983325a1a531e90c3df3e76d30dd9da2f9e29c6c6d9a6ac32da"
    },
    {
      "path": "profile-trust-pin.schema.json",
      "digest": "sha256:59574f3408c4d8f77b6ddc9e8abe10463ab7aea20eae898e524159770d77523c"
    }
  ],
  "digest": "sha256:3c66eb15acade77fa257691d13d19dd0290a2f551afa915347fd266928930df4"
};
export const OUTCOME_PROFILE_CONTRACT_V1: OutcomeProfileContractV1 = Object.freeze({ ...generatedContract, members: Object.freeze(generatedContract.members.map(member => Object.freeze({ ...member }))) });
export const OUTCOME_PROFILE_CONTRACT_V1_DIGEST = OUTCOME_PROFILE_CONTRACT_V1.digest;
