import { isProxy } from "node:util/types";
import { authorityDigest } from "./wire.js";

export type EvidenceGradeV1 = "verified" | "partial" | "pending" | "absent" | "failed";
export type GovernedEffectClassV1 = "read" | "idempotent-write" | "destructive";
export interface ToolEffectContractV1 { readonly v: "reelier.tool-effect-contract/v1"; readonly contractId: string; readonly provider: string; readonly operation: string; readonly operationDigest: string; readonly schemaDigest: string; readonly policyDigest: string; readonly effectClass: GovernedEffectClassV1; readonly model: Readonly<{ fields: readonly string[]; maxBytes: number }>; readonly bindings: Readonly<{ credentialRef: string; accountRef: string; destinationRef: string; limitRef: string }>; readonly semanticIdentity: string; readonly idempotencyKey: string | null; readonly readback: Readonly<{ operation: string; projection: readonly string[] }> | null; readonly result: Readonly<{ success: readonly string[]; conflict: readonly string[]; definitiveFailure: readonly string[]; ambiguity: readonly string[] }>; readonly maximumEvidenceGrade: EvidenceGradeV1; }
export interface ProviderOutcomePackV1 { readonly v: "reelier.provider-outcome-pack/v1"; readonly packId: string; readonly provider: string; readonly contractDigest: string; readonly preflightOperation: string; readonly dispatchOperation: string; readonly readbackOperation: string | null; }
export interface MissionClaimV1 { readonly v: "reelier.mission-claim/v1"; readonly missionId: string; readonly mandateDigest: string; readonly promptDigest: string; readonly contractDigests: readonly string[]; readonly claimedAt: string; }
export interface EffectReservationV1 { readonly v: "reelier.effect-reservation/v1"; readonly reservationId: string; readonly semanticIdentity: string; readonly contractDigest: string; readonly reservedAt: string; }
export interface AttemptV1 { readonly v: "reelier.attempt/v1"; readonly attemptId: string; readonly reservationId: string; readonly semanticIdentity: string; readonly dispatchedAt: string; readonly crossedProviderBoundary: boolean; readonly result: "acknowledged" | "definitive-failure" | "ambiguous"; }
export interface ObservationV1 { readonly v: "reelier.observation/v1"; readonly observationId: string; readonly reservationId: string; readonly semanticIdentity: string; readonly observedAt: string; readonly authoritative: boolean; readonly verdict: "matched" | "not-applied" | "conflict" | "unavailable"; readonly projectionDigest: string | null; }
export interface GovernedOutcomeV1 { readonly v: "reelier.governed-outcome/v1"; readonly outcomeId: string; readonly contractDigest: string; readonly semanticIdentity: string; readonly reservation: EffectReservationV1; readonly attempts: readonly AttemptV1[]; readonly observation: ObservationV1 | null; readonly status: EvidenceGradeV1; readonly completedAt: string; }
export interface GovernedReceiptV1 { readonly v: "reelier.governed-receipt/v1"; readonly receiptId: string; readonly outcomeDigest: string; readonly missionDigest: string; readonly issuedAt: string; readonly status: EvidenceGradeV1; }
export interface GovernedOutcomeVerificationContextV1 { readonly contract: ToolEffectContractV1; readonly now: string; }

const sha = /^sha256:[0-9a-f]{64}$/;
const id = /^[A-Za-z0-9._:-]{1,256}$/;
/** Inertly copies a small JSON graph using descriptors only: no getter, clone, or proxy trap executes user code. */
function snapshot(value: unknown, depth = 0, seen = new WeakSet<object>(), budget = { nodes: 0 }): unknown {
  if (depth > 16 || ++budget.nodes > 1024) throw new TypeError("wire graph is too deeply nested or too large");
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") { if (!Number.isFinite(value)) throw new TypeError("wire graph contains a non-finite number"); return value; }
  if (typeof value !== "object" || isProxy(value)) throw new TypeError("wire graph is not a bounded inert JSON value");
  if (seen.has(value)) throw new TypeError("wire graph is cyclic or shares object identity"); seen.add(value);
  const array = Array.isArray(value);
  if (array && value.length > 64) throw new TypeError("wire graph contains a huge array");
  const prototype = Object.getPrototypeOf(value); if (prototype !== Object.prototype && prototype !== null && prototype !== Array.prototype) throw new TypeError("wire graph has an unsupported prototype");
  if (!array) { let enumerableKeys = 0; for (const ignored in value) { void ignored; if (++enumerableKeys > 64) throw new TypeError("wire graph contains too many properties"); } }
  const descriptors = Object.getOwnPropertyDescriptors(value); if (Object.getOwnPropertySymbols(value).length || Object.entries(descriptors).some(([key, descriptor]) => (!descriptor.enumerable && !(array && key === "length")) || !Object.hasOwn(descriptor, "value"))) throw new TypeError("wire graph contains hidden or accessor properties");
  if (array) { if (Object.keys(descriptors).length !== value.length + 1) throw new TypeError("wire graph contains a sparse array"); const result: unknown[] = []; for (let index = 0; index < value.length; index++) { const descriptor = descriptors[String(index)]; if (!descriptor || !Object.hasOwn(descriptor, "value")) throw new TypeError("wire graph contains a sparse array"); result.push(snapshot(descriptor.value, depth + 1, seen, budget)); } return result; }
  const keys = Object.keys(descriptors); const result: Record<string, unknown> = Object.create(null); for (const key of keys) result[key] = snapshot(descriptors[key]!.value, depth + 1, seen, budget); return result;
}
function own(value: unknown, fields: readonly string[], label: string): Record<string, unknown> { const item = snapshot(value); if (!item || typeof item !== "object" || Array.isArray(item)) throw new TypeError(`${label} must be a plain closed object`); const keys = Object.keys(item); if (keys.length !== fields.length || keys.some(key => !fields.includes(key))) throw new TypeError(`${label} has missing or unknown fields`); return item as Record<string, unknown>; }
function text(value: unknown, label: string): string { if (typeof value !== "string" || !id.test(value)) throw new TypeError(`${label} is invalid`); return value; }
function digest(value: unknown, label: string): string { if (typeof value !== "string" || !sha.test(value)) throw new TypeError(`${label} must be an exact digest`); return value; }
function at(value: unknown, label: string): string { if (typeof value !== "string" || new Date(value).toISOString() !== value) throw new TypeError(`${label} must be a canonical timestamp`); return value; }
function list(value: unknown, label: string, allowEmpty = false): readonly string[] { if (!Array.isArray(value) || (!allowEmpty && value.length === 0) || value.length > 64 || Object.keys(value).length !== value.length) throw new TypeError(`${label} must be a dense bounded array`); const parsed = value.map(x => text(x, label)); if (new Set(parsed).size !== parsed.length) throw new TypeError(`${label} must be unique`); return Object.freeze(parsed); }
/** Closed RFC 6901-style projection pointers: no root, empty segments, or malformed escapes. */
function projectionList(value: unknown): readonly string[] { if (!Array.isArray(value) || value.length === 0 || value.length > 64 || Object.keys(value).length !== value.length) throw new TypeError("readback projection must be a dense bounded array"); const parsed = value.map(item => { if (typeof item !== "string" || !/^\/(?:[^~/]|~[01])+(?:\/(?:[^~/]|~[01])+)*$/u.test(item)) throw new TypeError("readback projection is invalid"); return item; }); if (new Set(parsed).size !== parsed.length) throw new TypeError("readback projection must be unique"); return Object.freeze(parsed); }
function freeze<T>(value: T): T { if (value && typeof value === "object") { for (const child of Object.values(value as object)) freeze(child); Object.freeze(value); } return value; }

export function parseToolEffectContractV1(value: unknown): ToolEffectContractV1 { const x=own(value,["v","contractId","provider","operation","operationDigest","schemaDigest","policyDigest","effectClass","model","bindings","semanticIdentity","idempotencyKey","readback","result","maximumEvidenceGrade"],"tool effect contract"); if(x.v!=="reelier.tool-effect-contract/v1" || !["read","idempotent-write","destructive"].includes(x.effectClass as string) || !["verified","partial","pending","absent","failed"].includes(x.maximumEvidenceGrade as string)) throw new TypeError("tool effect contract version or enum is invalid"); const model=own(x.model,["fields","maxBytes"],"model"); const maxBytes = model.maxBytes; if(typeof maxBytes!=="number"||!Number.isSafeInteger(maxBytes)||maxBytes<0||maxBytes>1_073_741_824)throw new TypeError("model maxBytes is invalid"); const bindings=own(x.bindings,["credentialRef","accountRef","destinationRef","limitRef"],"bindings"); const result=own(x.result,["success","conflict","definitiveFailure","ambiguity"],"result"); const groups=[list(result.success,"success"),list(result.conflict,"conflict",true),list(result.definitiveFailure,"definitive failure",true),list(result.ambiguity,"ambiguity",true)]; if(new Set(groups.flat()).size!==groups.flat().length)throw new TypeError("result semantics overlap"); let readback:ToolEffectContractV1["readback"]=null; if(x.readback!==null){const r=own(x.readback,["operation","projection"],"readback");readback=freeze({operation:text(r.operation,"readback operation"),projection:projectionList(r.projection)});} if(x.maximumEvidenceGrade==="verified"&&!readback)throw new TypeError("verified evidence requires authoritative readback"); return freeze({v:"reelier.tool-effect-contract/v1",contractId:text(x.contractId,"contract ID"),provider:text(x.provider,"provider"),operation:text(x.operation,"operation"),operationDigest:digest(x.operationDigest,"operation digest"),schemaDigest:digest(x.schemaDigest,"schema digest"),policyDigest:digest(x.policyDigest,"policy digest"),effectClass:x.effectClass as GovernedEffectClassV1,model:freeze({fields:list(model.fields,"model fields"),maxBytes}),bindings:freeze({credentialRef:text(bindings.credentialRef,"credential ref"),accountRef:text(bindings.accountRef,"account ref"),destinationRef:text(bindings.destinationRef,"destination ref"),limitRef:text(bindings.limitRef,"limit ref")}),semanticIdentity:text(x.semanticIdentity,"semantic identity"),idempotencyKey:x.idempotencyKey===null?null:text(x.idempotencyKey,"idempotency key"),readback,result:freeze({success:groups[0],conflict:groups[1],definitiveFailure:groups[2],ambiguity:groups[3]}),maximumEvidenceGrade:x.maximumEvidenceGrade as EvidenceGradeV1}); }
export function digestToolEffectContractV1(value: unknown): string { return authorityDigest(parseToolEffectContractV1(value)); }
export function parseEffectReservationV1(value: unknown): EffectReservationV1 { const x=own(value,["v","reservationId","semanticIdentity","contractDigest","reservedAt"],"reservation"); if(x.v!=="reelier.effect-reservation/v1")throw new TypeError("reservation version is invalid"); return freeze({v:"reelier.effect-reservation/v1",reservationId:text(x.reservationId,"reservation ID"),semanticIdentity:text(x.semanticIdentity,"reservation identity"),contractDigest:digest(x.contractDigest,"reservation contract digest"),reservedAt:at(x.reservedAt,"reservation time")}); }
export function digestEffectReservationV1(value: unknown): string { return authorityDigest(parseEffectReservationV1(value)); }
export function parseAttemptV1(value: unknown): AttemptV1 { const x=own(value,["v","attemptId","reservationId","semanticIdentity","dispatchedAt","crossedProviderBoundary","result"],"attempt"); if(x.v!=="reelier.attempt/v1"||typeof x.crossedProviderBoundary!=="boolean"||!["acknowledged","definitive-failure","ambiguous"].includes(x.result as string)||(!x.crossedProviderBoundary&&x.result!=="definitive-failure"))throw new TypeError("attempt is invalid"); return freeze({v:"reelier.attempt/v1",attemptId:text(x.attemptId,"attempt ID"),reservationId:text(x.reservationId,"attempt reservation"),semanticIdentity:text(x.semanticIdentity,"attempt identity"),dispatchedAt:at(x.dispatchedAt,"attempt time"),crossedProviderBoundary:x.crossedProviderBoundary,result:x.result as AttemptV1["result"]}); }
export function digestAttemptV1(value: unknown): string { return authorityDigest(parseAttemptV1(value)); }
export function parseObservationV1(value: unknown): ObservationV1 { const x=own(value,["v","observationId","reservationId","semanticIdentity","observedAt","authoritative","verdict","projectionDigest"],"observation"); const projected=x.verdict==="matched"||x.verdict==="not-applied"||x.verdict==="conflict"; const unavailable=x.verdict==="unavailable"; if(x.v!=="reelier.observation/v1"||typeof x.authoritative!=="boolean"||(!projected&&!unavailable)||(x.projectionDigest!==null&&!sha.test(x.projectionDigest as string))||(projected&&(!x.authoritative||x.projectionDigest===null))||(unavailable&&(x.authoritative||x.projectionDigest!==null)))throw new TypeError("observation is invalid"); return freeze({v:"reelier.observation/v1",observationId:text(x.observationId,"observation ID"),reservationId:text(x.reservationId,"observation reservation"),semanticIdentity:text(x.semanticIdentity,"observation identity"),observedAt:at(x.observedAt,"observation time"),authoritative:x.authoritative,verdict:x.verdict as ObservationV1["verdict"],projectionDigest:x.projectionDigest===null?null:digest(x.projectionDigest,"observation projection digest")}); }
export function digestObservationV1(value: unknown): string { return authorityDigest(parseObservationV1(value)); }
export function parseProviderOutcomePackV1(value: unknown): ProviderOutcomePackV1 { const x=own(value,["v","packId","provider","contractDigest","preflightOperation","dispatchOperation","readbackOperation"],"provider outcome pack"); if(x.v!=="reelier.provider-outcome-pack/v1")throw new TypeError("provider outcome pack version is invalid"); return freeze({v:"reelier.provider-outcome-pack/v1",packId:text(x.packId,"pack ID"),provider:text(x.provider,"pack provider"),contractDigest:digest(x.contractDigest,"pack contract digest"),preflightOperation:text(x.preflightOperation,"preflight operation"),dispatchOperation:text(x.dispatchOperation,"dispatch operation"),readbackOperation:x.readbackOperation===null?null:text(x.readbackOperation,"readback operation")}); }
export function digestProviderOutcomePackV1(value: unknown): string { return authorityDigest(parseProviderOutcomePackV1(value)); }
export function parseMissionClaimV1(value: unknown): MissionClaimV1 { const x=own(value,["v","missionId","mandateDigest","promptDigest","contractDigests","claimedAt"],"mission claim"); if(x.v!=="reelier.mission-claim/v1")throw new TypeError("mission claim version is invalid"); const contractDigests=list(x.contractDigests,"mission contract digests").map(item=>digest(item,"mission contract digest")); return freeze({v:"reelier.mission-claim/v1",missionId:text(x.missionId,"mission ID"),mandateDigest:digest(x.mandateDigest,"mandate digest"),promptDigest:digest(x.promptDigest,"prompt digest"),contractDigests:Object.freeze(contractDigests),claimedAt:at(x.claimedAt,"claimed time")}); }
export function digestMissionClaimV1(value: unknown): string { return authorityDigest(parseMissionClaimV1(value)); }
export function parseGovernedReceiptV1(value: unknown): GovernedReceiptV1 { const x=own(value,["v","receiptId","outcomeDigest","missionDigest","issuedAt","status"],"governed receipt"); if(x.v!=="reelier.governed-receipt/v1"||!["verified","partial","pending","absent","failed"].includes(x.status as string))throw new TypeError("governed receipt is invalid"); return freeze({v:"reelier.governed-receipt/v1",receiptId:text(x.receiptId,"receipt ID"),outcomeDigest:digest(x.outcomeDigest,"outcome digest"),missionDigest:digest(x.missionDigest,"mission digest"),issuedAt:at(x.issuedAt,"receipt time"),status:x.status as EvidenceGradeV1}); }
export function digestGovernedReceiptV1(value: unknown): string { return authorityDigest(parseGovernedReceiptV1(value)); }
export function parseGovernedOutcomeV1(value: unknown): GovernedOutcomeV1 { const x=own(value,["v","outcomeId","contractDigest","semanticIdentity","reservation","attempts","observation","status","completedAt"],"governed outcome"); if(x.v!=="reelier.governed-outcome/v1"||!["verified","partial","pending","absent","failed"].includes(x.status as string))throw new TypeError("governed outcome version or status is invalid"); const reservation=parseEffectReservationV1(x.reservation); if(!Array.isArray(x.attempts)||Object.keys(x.attempts).length!==x.attempts.length||x.attempts.length>64)throw new TypeError("attempts must be a dense bounded array"); const attempts=Object.freeze(x.attempts.map(parseAttemptV1)); const observation=x.observation===null?null:parseObservationV1(x.observation); return verifyParsedOutcome(freeze({v:"reelier.governed-outcome/v1" as const,outcomeId:text(x.outcomeId,"outcome ID"),contractDigest:digest(x.contractDigest,"contract digest"),semanticIdentity:text(x.semanticIdentity,"semantic identity"),reservation,attempts,observation,status:x.status as EvidenceGradeV1,completedAt:at(x.completedAt,"completion time")})); }
function verifyParsedOutcome(o: GovernedOutcomeV1): GovernedOutcomeV1 { if(!o.reservation||o.reservation.semanticIdentity!==o.semanticIdentity||o.reservation.contractDigest!==o.contractDigest)throw new TypeError("outcome identity drift"); let previous=Date.parse(o.reservation.reservedAt); const ids=new Set<string>();let ambiguousCrossing=false;for(const a of o.attempts){if(ids.has(a.attemptId)||a.reservationId!==o.reservation.reservationId||a.semanticIdentity!==o.semanticIdentity||Date.parse(a.dispatchedAt)<previous || (ambiguousCrossing && a.crossedProviderBoundary))throw new TypeError("outcome attempt chronology or identity drift");ids.add(a.attemptId);if(a.crossedProviderBoundary&&a.result==="ambiguous")ambiguousCrossing=true;previous=Date.parse(a.dispatchedAt);} if(o.observation){if(o.observation.reservationId!==o.reservation.reservationId||o.observation.semanticIdentity!==o.semanticIdentity||Date.parse(o.observation.observedAt)<previous)throw new TypeError("outcome observation chronology or identity drift");previous=Date.parse(o.observation.observedAt);} if(Date.parse(o.completedAt)<previous)throw new TypeError("outcome completion precedes its evidence"); if(o.status==="verified"&&(!o.attempts.some(a=>a.crossedProviderBoundary)||!o.observation||!o.observation.authoritative||o.observation.verdict!=="matched"||o.observation.projectionDigest===null))throw new TypeError("verified outcome requires provider dispatch and authoritative matched observation"); return o; }
function parseVerificationContextV1(value: unknown): GovernedOutcomeVerificationContextV1 { const x=own(value,["contract","now"],"governed outcome verification context"); return freeze({contract:parseToolEffectContractV1(x.contract),now:at(x.now,"verification time")}); }
function maximumGradePermits(maximum: EvidenceGradeV1, actual: EvidenceGradeV1): boolean { const permitted: Readonly<Record<EvidenceGradeV1, readonly EvidenceGradeV1[]>>={verified:["verified","partial","pending","absent","failed"],partial:["partial","pending","absent","failed"],pending:["pending","absent","failed"],absent:["absent","failed"],failed:["failed"]};return permitted[maximum].includes(actual); }
export function verifyGovernedOutcomeTransitionV1(value: unknown, rawContext: unknown): GovernedOutcomeV1 {
  const outcome=parseGovernedOutcomeV1(value);const context=parseVerificationContextV1(rawContext);const contractDigest=digestToolEffectContractV1(context.contract);
  if(outcome.contractDigest!==contractDigest||outcome.reservation.contractDigest!==contractDigest||outcome.semanticIdentity!==context.contract.semanticIdentity||outcome.reservation.semanticIdentity!==context.contract.semanticIdentity)throw new TypeError("outcome does not bind the exact reviewed contract");
  if(!maximumGradePermits(context.contract.maximumEvidenceGrade,outcome.status))throw new TypeError("outcome exceeds the contract maximum evidence grade");
  const now=Date.parse(context.now);const times=[outcome.reservation.reservedAt,...outcome.attempts.map(attempt=>attempt.dispatchedAt),...(outcome.observation?[outcome.observation.observedAt]:[]),outcome.completedAt];if(times.some(value=>Date.parse(value)>now))throw new TypeError("outcome evidence cannot be from the future");
  const expectedProjectionDigest=context.contract.readback===null?null:authorityDigest(context.contract.readback.projection);const verifiedEvidence=outcome.attempts.some(attempt=>attempt.crossedProviderBoundary)&&outcome.observation!==null&&outcome.observation.authoritative&&outcome.observation.verdict==="matched"&&outcome.observation.projectionDigest===expectedProjectionDigest&&expectedProjectionDigest!==null;
  if(outcome.status==="verified"){if(context.contract.maximumEvidenceGrade!=="verified"||!verifiedEvidence)throw new TypeError("verified outcome is not permitted by exact authoritative evidence");}else if(verifiedEvidence)throw new TypeError("nonverified outcome cannot carry verified evidence");
  return outcome;
}
export function digestGovernedOutcomeV1(value: unknown): string { return authorityDigest(parseGovernedOutcomeV1(value)); }
