import { isProxy } from "node:util/types";
import { authorityDigest } from "./wire.js";

export type EvidenceGradeV1 = "verified" | "partial" | "pending" | "absent" | "failed";
export type GovernedEffectClassV1 = "read" | "idempotent-write" | "destructive";
export interface ToolEffectContractV1 { readonly v: "reelier.tool-effect-contract/v1"; readonly contractId: string; readonly provider: string; readonly operation: string; readonly operationDigest: string; readonly schemaDigest: string; readonly policyDigest: string; readonly effectClass: GovernedEffectClassV1; readonly model: Readonly<{ fields: readonly string[]; maxBytes: number }>; readonly bindings: Readonly<{ credentialRef: string; accountRef: string; destinationRef: string; limitRef: string }>; readonly semanticIdentity: string; readonly idempotencyKey: string | null; readonly readback: Readonly<{ operation: string; projection: readonly string[] }> | null; readonly result: Readonly<{ success: readonly string[]; conflict: readonly string[]; definitiveFailure: readonly string[]; ambiguity: readonly string[] }>; readonly maximumEvidenceGrade: EvidenceGradeV1; }
export interface ProviderOutcomePackV1 { readonly v: "reelier.provider-outcome-pack/v1"; readonly packId: string; readonly provider: string; readonly contractDigest: string; readonly preflightOperation: string; readonly dispatchOperation: string; readonly readbackOperation: string | null; }
export interface MissionClaimV1 { readonly v: "reelier.mission-claim/v1"; readonly missionId: string; readonly mandateDigest: string; readonly promptDigest: string; readonly contractDigests: readonly string[]; readonly claimedAt: string; }
export interface EffectReservationV1 { readonly v: "reelier.effect-reservation/v1"; readonly reservationId: string; readonly semanticIdentity: string; readonly contractDigest: string; readonly reservedAt: string; }
export interface AttemptV1 { readonly v: "reelier.attempt/v1"; readonly attemptId: string; readonly reservationId: string; readonly semanticIdentity: string; readonly dispatchedAt: string; readonly crossedProviderBoundary: boolean; readonly result: "acknowledged" | "definitive-failure" | "ambiguous"; }
export interface ObservationV1 { readonly v: "reelier.observation/v1"; readonly observationId: string; readonly reservationId: string; readonly semanticIdentity: string; readonly observedAt: string; readonly authoritative: boolean; readonly verdict: "matched" | "not-applied" | "conflict" | "unavailable"; readonly projectionDigest: string | null; }
export interface GovernedOutcomeV1 { readonly v: "reelier.governed-outcome/v1"; readonly outcomeId: string; readonly contractDigest: string; readonly semanticIdentity: string; readonly reservation: EffectReservationV1; readonly attempts: readonly AttemptV1[]; readonly observation: ObservationV1 | null; readonly status: EvidenceGradeV1; readonly completedAt: string; }
export interface GovernedReceiptV1 { readonly v: "reelier.governed-receipt/v1"; readonly receiptId: string; readonly outcomeDigest: string; readonly missionDigest: string; readonly issuedAt: string; readonly status: EvidenceGradeV1; }

const sha = /^sha256:[0-9a-f]{64}$/;
const id = /^[A-Za-z0-9._:-]{1,256}$/;
function own(value: unknown, fields: readonly string[], label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || isProxy(value)) throw new TypeError(`${label} must be a plain closed object`); const descriptors = Object.getOwnPropertyDescriptors(value); if (Object.values(descriptors).some(d => !Object.hasOwn(d, "value"))) throw new TypeError(`${label} must not contain accessors`); const keys = Object.keys(value); if (keys.length !== fields.length || keys.some(key => !fields.includes(key))) throw new TypeError(`${label} has missing or unknown fields`); return structuredClone(value) as Record<string, unknown>; }
function text(value: unknown, label: string): string { if (typeof value !== "string" || !id.test(value)) throw new TypeError(`${label} is invalid`); return value; }
function digest(value: unknown, label: string): string { if (typeof value !== "string" || !sha.test(value)) throw new TypeError(`${label} must be an exact digest`); return value; }
function at(value: unknown, label: string): string { if (typeof value !== "string" || new Date(value).toISOString() !== value) throw new TypeError(`${label} must be a canonical timestamp`); return value; }
function list(value: unknown, label: string, allowEmpty = false): readonly string[] { if (!Array.isArray(value) || (!allowEmpty && value.length === 0) || value.length > 64 || Object.keys(value).length !== value.length) throw new TypeError(`${label} must be a dense bounded array`); const parsed = value.map(x => text(x, label)); if (new Set(parsed).size !== parsed.length) throw new TypeError(`${label} must be unique`); return Object.freeze(parsed); }
/** Closed RFC 6901-style projection pointers: no root, empty segments, or malformed escapes. */
function projectionList(value: unknown): readonly string[] { if (!Array.isArray(value) || value.length === 0 || value.length > 64 || Object.keys(value).length !== value.length) throw new TypeError("readback projection must be a dense bounded array"); const parsed = value.map(item => { if (typeof item !== "string" || !/^\/(?:[^~/]|~[01])+(?:\/(?:[^~/]|~[01])+)*$/u.test(item)) throw new TypeError("readback projection is invalid"); return item; }); if (new Set(parsed).size !== parsed.length) throw new TypeError("readback projection must be unique"); return Object.freeze(parsed); }
function freeze<T>(value: T): T { if (value && typeof value === "object") { for (const child of Object.values(value as object)) freeze(child); Object.freeze(value); } return value; }

export function parseToolEffectContractV1(value: unknown): ToolEffectContractV1 { const x=own(value,["v","contractId","provider","operation","operationDigest","schemaDigest","policyDigest","effectClass","model","bindings","semanticIdentity","idempotencyKey","readback","result","maximumEvidenceGrade"],"tool effect contract"); if(x.v!=="reelier.tool-effect-contract/v1" || !["read","idempotent-write","destructive"].includes(x.effectClass as string) || !["verified","partial","pending","absent","failed"].includes(x.maximumEvidenceGrade as string)) throw new TypeError("tool effect contract version or enum is invalid"); const model=own(x.model,["fields","maxBytes"],"model"); const maxBytes = model.maxBytes; if(typeof maxBytes!=="number"||!Number.isSafeInteger(maxBytes)||maxBytes<0||maxBytes>1_073_741_824)throw new TypeError("model maxBytes is invalid"); const bindings=own(x.bindings,["credentialRef","accountRef","destinationRef","limitRef"],"bindings"); const result=own(x.result,["success","conflict","definitiveFailure","ambiguity"],"result"); const groups=[list(result.success,"success"),list(result.conflict,"conflict",true),list(result.definitiveFailure,"definitive failure",true),list(result.ambiguity,"ambiguity",true)]; if(new Set(groups.flat()).size!==groups.flat().length)throw new TypeError("result semantics overlap"); let readback:ToolEffectContractV1["readback"]=null; if(x.readback!==null){const r=own(x.readback,["operation","projection"],"readback");readback=freeze({operation:text(r.operation,"readback operation"),projection:projectionList(r.projection)});} if(x.maximumEvidenceGrade==="verified"&&!readback)throw new TypeError("verified evidence requires authoritative readback"); return freeze({v:"reelier.tool-effect-contract/v1",contractId:text(x.contractId,"contract ID"),provider:text(x.provider,"provider"),operation:text(x.operation,"operation"),operationDigest:digest(x.operationDigest,"operation digest"),schemaDigest:digest(x.schemaDigest,"schema digest"),policyDigest:digest(x.policyDigest,"policy digest"),effectClass:x.effectClass as GovernedEffectClassV1,model:freeze({fields:list(model.fields,"model fields"),maxBytes}),bindings:freeze({credentialRef:text(bindings.credentialRef,"credential ref"),accountRef:text(bindings.accountRef,"account ref"),destinationRef:text(bindings.destinationRef,"destination ref"),limitRef:text(bindings.limitRef,"limit ref")}),semanticIdentity:text(x.semanticIdentity,"semantic identity"),idempotencyKey:x.idempotencyKey===null?null:text(x.idempotencyKey,"idempotency key"),readback,result:freeze({success:groups[0],conflict:groups[1],definitiveFailure:groups[2],ambiguity:groups[3]}),maximumEvidenceGrade:x.maximumEvidenceGrade as EvidenceGradeV1}); }
export function digestToolEffectContractV1(value: unknown): string { return authorityDigest(parseToolEffectContractV1(value)); }
export function parseGovernedOutcomeV1(value: unknown): GovernedOutcomeV1 { const x=own(value,["v","outcomeId","contractDigest","semanticIdentity","reservation","attempts","observation","status","completedAt"],"governed outcome"); if(x.v!=="reelier.governed-outcome/v1"||!["verified","partial","pending","absent","failed"].includes(x.status as string))throw new TypeError("governed outcome version or status is invalid"); const r=own(x.reservation,["v","reservationId","semanticIdentity","contractDigest","reservedAt"],"reservation") as unknown as EffectReservationV1; if(r.v!=="reelier.effect-reservation/v1")throw new TypeError("reservation version is invalid"); const reservation=freeze({ ...r, reservationId:text(r.reservationId,"reservation ID"),semanticIdentity:text(r.semanticIdentity,"reservation identity"),contractDigest:digest(r.contractDigest,"reservation contract digest"),reservedAt:at(r.reservedAt,"reservation time")}); if(!Array.isArray(x.attempts)||Object.keys(x.attempts).length!==x.attempts.length||x.attempts.length>64)throw new TypeError("attempts must be a dense bounded array"); const attempts=x.attempts.map(item=>{const a=own(item,["v","attemptId","reservationId","semanticIdentity","dispatchedAt","crossedProviderBoundary","result"],"attempt") as unknown as AttemptV1;if(a.v!=="reelier.attempt/v1"||typeof a.crossedProviderBoundary!=="boolean"||!["acknowledged","definitive-failure","ambiguous"].includes(a.result))throw new TypeError("attempt is invalid");return freeze({...a,attemptId:text(a.attemptId,"attempt ID"),reservationId:text(a.reservationId,"attempt reservation"),semanticIdentity:text(a.semanticIdentity,"attempt identity"),dispatchedAt:at(a.dispatchedAt,"attempt time")});}); let observation:ObservationV1|null=null;if(x.observation!==null){const o=own(x.observation,["v","observationId","reservationId","semanticIdentity","observedAt","authoritative","verdict","projectionDigest"],"observation") as unknown as ObservationV1;if(o.v!=="reelier.observation/v1"||typeof o.authoritative!=="boolean"||!["matched","not-applied","conflict","unavailable"].includes(o.verdict)||!(o.projectionDigest===null||sha.test(o.projectionDigest)))throw new TypeError("observation is invalid");observation=freeze({...o,observationId:text(o.observationId,"observation ID"),reservationId:text(o.reservationId,"observation reservation"),semanticIdentity:text(o.semanticIdentity,"observation identity"),observedAt:at(o.observedAt,"observation time")});} const parsed=freeze({v:"reelier.governed-outcome/v1" as const,outcomeId:text(x.outcomeId,"outcome ID"),contractDigest:digest(x.contractDigest,"contract digest"),semanticIdentity:text(x.semanticIdentity,"semantic identity"),reservation,attempts:Object.freeze(attempts),observation,status:x.status as EvidenceGradeV1,completedAt:at(x.completedAt,"completion time")}); return verifyGovernedOutcomeTransitionV1(parsed); }
export function verifyGovernedOutcomeTransitionV1(value: unknown): GovernedOutcomeV1 { const o=value as GovernedOutcomeV1; if(!o.reservation||o.reservation.semanticIdentity!==o.semanticIdentity||o.reservation.contractDigest!==o.contractDigest)throw new TypeError("outcome identity drift"); let previous=Date.parse(o.reservation.reservedAt); const ids=new Set<string>();for(const a of o.attempts){if(ids.has(a.attemptId)||a.reservationId!==o.reservation.reservationId||a.semanticIdentity!==o.semanticIdentity||Date.parse(a.dispatchedAt)<previous)throw new TypeError("outcome attempt chronology or identity drift");ids.add(a.attemptId);previous=Date.parse(a.dispatchedAt);} if(o.observation){if(o.observation.reservationId!==o.reservation.reservationId||o.observation.semanticIdentity!==o.semanticIdentity||Date.parse(o.observation.observedAt)<previous)throw new TypeError("outcome observation chronology or identity drift");previous=Date.parse(o.observation.observedAt);} if(Date.parse(o.completedAt)<previous)throw new TypeError("outcome completion precedes its evidence"); if(o.status==="verified"&&(!o.observation||!o.observation.authoritative||o.observation.verdict!=="matched"))throw new TypeError("verified outcome requires authoritative matched observation"); if(o.status==="verified"&&o.observation?.projectionDigest===null)throw new TypeError("verified outcome requires projection evidence"); return o; }
export function digestGovernedOutcomeV1(value: unknown): string { return authorityDigest(parseGovernedOutcomeV1(value)); }
