import { mkdir, open, readFile, readdir, rename } from "node:fs/promises";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { authorityDigest } from "../wire.js";
import { createReservedDispatchHandle, type ReservedDispatchHandle } from "../gate.js";
import type { AuthorityLedger, LedgerState, ReservationSnapshot } from "../ledger.js";
import type { AuthorityExecutionContextV1 } from "../types.js";
import { createGitHubLinearOutcomePackV1, orderedGitHubLinearOperationsV1, type GitHubLinearOutcomeModeV1, type GitHubLinearOutcomePackV1, type GitHubLinearReviewedAuthorityV1 } from "../packs/github-linear-outcomes.js";
import { compileEffectTransportV1, mintTrustedEffectTransportExecutorV1, type CompiledEffectTransportV1, type EffectTransportHostBindingsV1, type McpEffectTransportBindingV1 } from "./effect-transports.js";
import { createDispatchCoordinator, type DispatchAdapter, type DispatchOutcome, type DispatchRequestState } from "./dispatch.js";
import { createOutcomeKernel } from "./outcome-kernel.js";
import { createFileOutcomeKernelStorage } from "./outcome-kernel-fs-storage.js";
import { createAuthorityAgentTools, type AuthorityAgentToolsV1, type AuthorityAgentToolContextV1 } from "./agent-tools.js";

export interface GitHubLinearMissionProviderV1 { dispatch(operation: string, input: unknown): Promise<Readonly<{ outcome: string; data: unknown }>>; readback(operation: string, input: unknown): Promise<Readonly<{ outcome: string; data: unknown }>>; }
type RequestPlan = Readonly<{ requestId:string; missionId:string; mode:GitHubLinearOutcomeModeV1; executionContext:AuthorityExecutionContextV1; reservationIds:readonly string[]; claimedAt:string; lifecycleState:string; receiptRef?:string }>;
type OutcomeReview = Readonly<{ reviewId:string;requestIds:readonly string[] }>;

export async function createGitHubLinearMissionRuntimeV1(input: Readonly<{ rootDir:string; authority:GitHubLinearReviewedAuthorityV1; provider:GitHubLinearMissionProviderV1; resolveHostBindings:(references:GitHubLinearOutcomePackV1["operations"][keyof GitHubLinearOutcomePackV1["operations"]]["contract"]["bindings"])=>Promise<EffectTransportHostBindingsV1>; now:()=>number }>): Promise<Readonly<{agentTools:AuthorityAgentToolsV1;reviewOutcomes(requestIds:readonly string[]):Promise<void>;inspectEvidence():Promise<Readonly<{activationConfirmations:number;routineApprovals:number;requests:readonly RequestPlan[];reviews:readonly OutcomeReview[]}>>}>> {
  if (!path.isAbsolute(input.rootDir) || typeof input.provider?.dispatch !== "function" || typeof input.provider?.readback !== "function" || typeof input.resolveHostBindings !== "function" || typeof input.now !== "function") throw new TypeError("reviewed mission runtime options are invalid");
  const pack = createGitHubLinearOutcomePackV1(input.authority), root = path.resolve(input.rootDir);
  await Promise.all(["kernel","requests","reservations","reviews"].map(name=>mkdir(path.join(root,name),{recursive:true})));
  await createOnce(path.join(root,"activation.json"),{v:"reelier.standing-activation/v1",confirmations:1,routineApprovals:0});
  const storage = await createFileOutcomeKernelStorage({rootDir:path.join(root,"kernel")});
  const ledger = new RuntimeLedger(path.join(root,"reservations"));
  const compiled = compilePack(pack,input.authority,input.provider,input.resolveHostBindings);
  const adapter: DispatchAdapter = {
    async dispatch(state,call){ const item=compiled.get(state.effectDigest); return item ? item.adapter.dispatch(state,call) : failure(state,"unknown-effect"); },
    async reconcile(state,prior){ const item=compiled.get(state.effectDigest); return item?.adapter.reconcile ? item.adapter.reconcile(state,prior) : failure(state,"readback-unavailable"); },
  };
  Object.freeze(adapter);
  const authorityLedger=ledger as unknown as AuthorityLedger;
  const coordinator=createDispatchCoordinator(authorityLedger,adapter);
  const kernel=createOutcomeKernel({storage,ledger:authorityLedger,coordinator,now:input.now,authorization:async()=>"active"});
  const backend={
    async jobsSearch(_value:unknown,context:AuthorityAgentToolContextV1){const execution=requiredContext(context);return {requestId:"",verdict:"accepted",reasonCode:"agent-ready",lifecycleState:"ready",jobs:["github-linear","linear-only"].map(mode=>({jobRef:opaqueRef(execution,mode as GitHubLinearOutcomeModeV1)}))};},
    async jobLoad(value:unknown,context:AuthorityAgentToolContextV1){const execution=requiredContext(context),ref=String((value as Record<string,unknown>).jobId),mode=resolveRef(execution,ref);return mode?{requestId:"",verdict:"accepted",reasonCode:"outcome-proposed",lifecycleState:"proposed",jobRef:ref}:{requestId:"",verdict:"refused",reasonCode:"unknown-outcome",lifecycleState:"refused"};},
    async invoke(value:unknown,context:AuthorityAgentToolContextV1){const execution=requiredContext(context),raw=value as Record<string,unknown>,requestId=String(raw.requestId),mode=resolveRef(execution,String(raw.jobRef));if(!mode)return refused(requestId,"unknown-outcome");const existing=await readPlan(root,requestId);if(existing&&authorityDigest(existing.executionContext)!==authorityDigest(execution))return refused(requestId,"request-context-conflict");const plan=existing??await createPlan(root,pack,execution,mode,requestId,input.now());return runPlan(plan,false);},
    async status(value:unknown,context:AuthorityAgentToolContextV1){const execution=requiredContext(context),requestId=String((value as Record<string,unknown>).requestId),plan=await readPlan(root,requestId);if(!plan||authorityDigest(plan.executionContext)!==authorityDigest(execution))return refused(requestId,"unknown-request");return runPlan(plan,true);},
  };
  async function runPlan(plan:RequestPlan,recovery:boolean){
    const operations=orderedGitHubLinearOperationsV1(pack,plan.mode),contracts=operations.map(item=>item.contract);
    await kernel.claimMission({v:"reelier.mission-claim/v1",missionId:plan.missionId,mandateDigest:pack.authorityDigest,promptDigest:authorityDigest({requestId:plan.requestId,source:"prompt-redacted"}),contractDigests:contracts.map(authorityDigest),claimedAt:plan.claimedAt});
    const effects=[];
    for(let index=0;index<operations.length;index++){const item=compiled.get(authorityDigest(operations[index]!.contract))!;if(recovery)effects.push({contract:operations[index]!.contract,reservationId:plan.reservationIds[index]!,verifier:item.verifier});else{const state=await ledger.reserveRuntime(plan.reservationIds[index]!,item,plan.executionContext);const handle=createReservedDispatchHandle(state) as ReservedDispatchHandle;effects.push({contract:operations[index]!.contract,handle,verifier:item.verifier});}}
    const outcome=await kernel.execute({missionId:plan.missionId,effects:effects as never});
    const reconciled=outcome.status==="verified",updated=Object.freeze({...plan,lifecycleState:reconciled?"reconciled":"pending",...(reconciled&&outcome.receiptRefs.length?{receiptRef:outcome.receiptRefs.at(-1)}:{})});await writePlan(root,updated);
    return {requestId:plan.requestId,verdict:"accepted" as const,reasonCode:updated.lifecycleState,lifecycleState:updated.lifecycleState,...(updated.receiptRef?{receiptRef:updated.receiptRef}:{})};
  }
  return Object.freeze({agentTools:createAuthorityAgentTools(backend),async reviewOutcomes(requestIds){if(!Array.isArray(requestIds)||requestIds.length<1||new Set(requestIds).size!==requestIds.length)throw new TypeError("Outcome review request IDs are invalid");for(const id of requestIds){const plan=await readPlan(root,id);if(!plan||plan.lifecycleState!=="reconciled"||!plan.receiptRef)throw new TypeError("Outcome review requires reconciled durable receipts");}const review:OutcomeReview=Object.freeze({reviewId:`review_${authorityDigest({requestIds}).slice(7)}`,requestIds:Object.freeze([...requestIds])});await createOnce(path.join(root,"reviews",`${review.reviewId}.json`),review);},async inspectEvidence(){const activation=JSON.parse(await readFile(path.join(root,"activation.json"),"utf8"));const files=(await readdir(path.join(root,"requests"))).filter(x=>x.endsWith(".json"));const requests=await Promise.all(files.map(async file=>JSON.parse(await readFile(path.join(root,"requests",file),"utf8")) as RequestPlan));const reviewFiles=(await readdir(path.join(root,"reviews"))).filter(x=>x.endsWith(".json"));const reviews=await Promise.all(reviewFiles.map(async file=>JSON.parse(await readFile(path.join(root,"reviews",file),"utf8")) as OutcomeReview));return Object.freeze({activationConfirmations:activation.confirmations,routineApprovals:activation.routineApprovals,requests:Object.freeze(requests),reviews:Object.freeze(reviews)});}});
}

function compilePack(pack:GitHubLinearOutcomePackV1,authority:GitHubLinearReviewedAuthorityV1,provider:GitHubLinearMissionProviderV1,resolveHostBindings:(references:GitHubLinearOutcomePackV1["operations"][keyof GitHubLinearOutcomePackV1["operations"]]["contract"]["bindings"])=>Promise<EffectTransportHostBindingsV1>):Map<string,CompiledEffectTransportV1>{const toolOperations=new Map<string,string>(),schemas=new Map<string,{serverSchemaDigest:string;toolSchemaDigest:string}>();for(const operation of Object.values(pack.operations)){const binding=operation.binding as McpEffectTransportBindingV1;toolOperations.set(binding.tool,binding.operation);schemas.set(binding.tool,{serverSchemaDigest:binding.serverSchemaDigest,toolSchemaDigest:binding.toolSchemaDigest});if(binding.readback){toolOperations.set(binding.readback.tool,binding.readback.operation);schemas.set(binding.readback.tool,{serverSchemaDigest:binding.serverSchemaDigest,toolSchemaDigest:binding.readback.toolSchemaDigest});}}const executor=mintTrustedEffectTransportExecutorV1({mcp:{inspectSchemas(request,sink){const schema=schemas.get(request.tool);if(schema)sink.success(JSON.stringify(schema));else sink.failure();},call(request,sink){const operation=toolOperations.get(request.tool)!;const read=operation.endsWith(".readback");void (read?provider.readback(operation,request.arguments):provider.dispatch(operation,request.arguments)).then(value=>sink.success(JSON.stringify(value)),()=>sink.failure());}}});const result=new Map<string,CompiledEffectTransportV1>();for(const [name,operation] of Object.entries(pack.operations)){const modelInput=name==="linearEvidenceComment"?{evidenceUrl:authority.linear.evidenceUrl}:name==="linearStatusTransition"?{requestId:"host-bound"}:{authorizationHandle:"host-bound",requestId:"host-bound"};const compiled=compileEffectTransportV1({contract:operation.contract,binding:operation.binding,modelInput,observationAuthKey:authorityDigest({contract:authorityDigest(operation.contract)}).slice(7),resolveHostBindings,executor});result.set(authorityDigest(operation.contract),compiled);}return result;}
function requiredContext(context:AuthorityAgentToolContextV1):AuthorityExecutionContextV1{if(!context.executionContext)throw new TypeError("authenticated execution context is required");return context.executionContext;}
function opaqueRef(context:AuthorityExecutionContextV1,mode:GitHubLinearOutcomeModeV1){return `outcomeref_${authorityDigest({v:"reelier.reviewed-outcome-ref/v1",context,mode}).slice(7)}`;}
function resolveRef(context:AuthorityExecutionContextV1,ref:string):GitHubLinearOutcomeModeV1|null{for(const mode of ["github-linear","linear-only"] as const)if(opaqueRef(context,mode)===ref)return mode;return null;}
function refused(requestId:string,reasonCode:string){return {requestId,verdict:"refused" as const,reasonCode,lifecycleState:"refused"};}
function failure(state:DispatchRequestState,reason:string):DispatchOutcome{return {kind:"definitive-failure",resultDigest:authorityDigest({reservationId:state.reservation.reservationId,reason})};}
function requestFile(root:string,id:string){return path.join(root,"requests",`${authorityDigest({id}).slice(7)}.json`);}
async function readPlan(root:string,id:string):Promise<RequestPlan|null>{try{return JSON.parse(await readFile(requestFile(root,id),"utf8"));}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error;}}
async function createPlan(root:string,pack:GitHubLinearOutcomePackV1,executionContext:AuthorityExecutionContextV1,mode:GitHubLinearOutcomeModeV1,requestId:string,now:number):Promise<RequestPlan>{const operations=orderedGitHubLinearOperationsV1(pack,mode),missionId=`mission_${authorityDigest({executionContext,requestId,mode}).slice(7)}`,plan=Object.freeze({requestId,missionId,mode,executionContext,reservationIds:Object.freeze(operations.map((_,index)=>`reservation_${authorityDigest({missionId,index}).slice(7)}`)),claimedAt:new Date(now).toISOString(),lifecycleState:"claimed"});await writePlan(root,plan);return plan;}
async function writePlan(root:string,plan:RequestPlan){await atomicWrite(requestFile(root,plan.requestId),plan);}
async function createOnce(file:string,value:unknown){try{const h=await open(file,"wx",0o600);try{await h.writeFile(JSON.stringify(value));await h.sync();}finally{await h.close();}}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;}}
async function atomicWrite(file:string,value:unknown){const temp=`${file}.${process.pid}.${randomBytes(6).toString("hex")}.tmp`,h=await open(temp,"wx",0o600);try{await h.writeFile(JSON.stringify(value));await h.sync();}finally{await h.close();}await rename(temp,file);}

class RuntimeLedger {
  constructor(private readonly root:string){}
  async reserveRuntime(id:string,compiled:CompiledEffectTransportV1,executionContext:AuthorityExecutionContextV1):Promise<DispatchRequestState>{const prior=await this.getReservation(id);const reservation=prior??({reservationId:id,state:"reserved",intent:{effectDigest:compiled.effect.contractDigest,effectCanonicalBase64:Buffer.from(JSON.stringify(compiled.effect)).toString("base64"),executionContext},limitAssignments:[],sequence:0,updatedAt:new Date().toISOString()} as unknown as ReservationSnapshot);if(!prior)await this.put(reservation);return {reservation,effect:compiled.effect,effectDigest:compiled.effect.contractDigest,effectCanonicalBase64:reservation.intent.effectCanonicalBase64!};}
  async getReservation(id:string){try{return JSON.parse(await readFile(this.file(id),"utf8")) as ReservationSnapshot;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;}}
  async transition(id:string,expected:LedgerState,event:{to:string;resultDigest?:string}){const state=await this.getReservation(id);if(!state||state.state!==expected)return {ok:false as const,reason:"state-conflict" as const};const next={...state,state:event.to,sequence:state.sequence+1,updatedAt:new Date().toISOString(),...(event.resultDigest?{resultDigest:event.resultDigest}:{})} as ReservationSnapshot;await this.put(next);return {ok:true as const,status:"transitioned" as const,reservation:next};}
  async recover(){const files=(await readdir(this.root)).filter(x=>x.endsWith(".json"));const reservations=[];for(const file of files){const state=JSON.parse(await readFile(path.join(this.root,file),"utf8")) as ReservationSnapshot;if(state.state==="dispatched"){const next={...state,state:"ambiguous" as const};await this.put(next);reservations.push(next);}else reservations.push(state);}return {ok:true as const,reservations,highWaterMark:null,topology:{directorySync:"best-effort" as const}};}
  private file(id:string){return path.join(this.root,`${authorityDigest({id}).slice(7)}.json`);}private async put(value:ReservationSnapshot){await atomicWrite(this.file(value.reservationId),value);}
}
