import os from "node:os";
import type { KeyObject } from "node:crypto";
import type { AuthorityHostConfig } from "./config.js";
import type { AuthorityHostServer } from "./server.js";
import { createAuthorityHostServer } from "./server.js";
import { createAdmittedLocalAuthorityRuntime } from "./local.js";
import { loadProfileGovernanceFromOperatorTrust } from "./profile-governance-loader.js";
import { assertExactDataRecord } from "./profile-governance.js";
import { assertLinuxAuthorityCellHost } from "./platform.js";
import type { PrincipalRegistry } from "./principal-registry.js";
import type { DispatchAdapter, CertifiedDispatchOptions, CertifiedIdentityVerifier, DispatchPublication } from "./dispatch.js";
import type { DelegationAuthority } from "./delegation-service.js";
import type { SignedTopologyEvidenceV1 } from "./topology.js";
import type { SignedAuthorityLeaseV1 } from "../types.js";
import type { SourceReadAdapter } from "./source-read-adapter.js";
import type { OpaqueConnectionRouteRegistry } from "../../connections.js";
import type { SecretResolver } from "./secret-resolver.js";
import type { RouteAuthoritySnapshotV1 } from "../ledger.js";
import type { AuthenticatedProviderIdentityV1 } from "./github-account-identity.js";
import type { AuthorityLatencyRecorder } from "./latency.js";
import type { AuthorityReceiptSigningAuthorityV1 } from "./receipt-authority.js";
import { validateAuthorityReceiptSigningAuthority } from "./receipt-authority.js";
import { loadAuthorityDeployment, type JobCardTrustPinV1 } from "./deployment.js";
import { loadExistingLocalGateSigner } from "./gate-signer.js";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { authorityDigest, parseAuthorityWire, parseCanonicalAuthorityJson } from "../wire.js";
import { createCurrentAuthorityTrustView, currentAuthorityTrustViewState, createTrustRoots, trustRootSetDigest, type TrustRootEntry } from "../trust.js";
import { createProfileVerificationRoots, parseAuthorityDeploymentSnapshot, parseAuthorityRouteScope } from "../outcome-profile.js";
import { admittedProfileGovernanceState } from "./profile-governance.js";
import { createFirstPartyPackRegistry, createFirstPartySourceRegistry } from "../../packs/index.js";
import { createProfileGovernedAuthorityReceiptPublication } from "./profile-governed-receipt.js";
import { signedJobCardDigest } from "../job.js";
import { connectorRegistrationDigest } from "../connector.js";
import { selectEligibleAuthorityContract } from "../gate.js";
import { jsonHttpsRouteDigest } from "./json-https-route.js";

export interface GovernedAuthorityCellReferenceV1 { readonly v: "reelier.governed-authority-cell-reference/v1"; readonly tenant: string; readonly governanceRef: string; readonly expectedManifestDigest: string; readonly expectedTrustHeadDigest: string }
export interface GovernedAuthorityCellOptionsV1 {
  readonly principalRegistry?: PrincipalRegistry; readonly dispatchAdapter?: DispatchAdapter; readonly delegation?: DelegationAuthority;
  readonly signedTopologyEvidence?: SignedTopologyEvidenceV1; readonly topologySigner?: Readonly<{ signerId: string; publicKey: KeyObject }>;
  readonly signedLease?: SignedAuthorityLeaseV1; readonly leaseSigner?: Readonly<{ signerId: string; publicKey: KeyObject }>;
  readonly sourceReadAdapter?: SourceReadAdapter; readonly connectionRoutes?: OpaqueConnectionRouteRegistry; readonly secretResolver?: SecretResolver;
  readonly routeAuthority?: (input: Readonly<{ tenant: string; requester: string; definitionAlias: string; connectorId: string; accountId: string; endpointId: string; authorityGeneration: string; authorityExpiresAt: string }>) => RouteAuthoritySnapshotV1 | undefined;
  readonly authenticatedProviderIdentity?: () => Promise<AuthenticatedProviderIdentityV1>; readonly verifyAuthenticatedProviderIdentity?: CertifiedIdentityVerifier;
  readonly certifiedDispatch?: CertifiedDispatchOptions; readonly portableReceiptPublication?: DispatchPublication; readonly latencyRecorder?: AuthorityLatencyRecorder;
  readonly receiptSigningAuthority?: AuthorityReceiptSigningAuthorityV1;
}

const REFERENCE_FIELDS = ["v", "tenant", "governanceRef", "expectedManifestDigest", "expectedTrustHeadDigest"] as const;
const OPTION_FIELDS = ["principalRegistry", "dispatchAdapter", "delegation", "signedTopologyEvidence", "topologySigner", "signedLease", "leaseSigner", "sourceReadAdapter", "connectionRoutes", "secretResolver", "routeAuthority", "authenticatedProviderIdentity", "verifyAuthenticatedProviderIdentity", "certifiedDispatch", "portableReceiptPublication", "latencyRecorder", "receiptSigningAuthority"] as const;
const ID = /^[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$/;
const DIGEST = /^sha256:[0-9a-f]{64}$/;

export async function createGovernedAuthorityCell(config: AuthorityHostConfig, reference: GovernedAuthorityCellReferenceV1, options: GovernedAuthorityCellOptionsV1): Promise<AuthorityHostServer> {
  assertLinuxAuthorityCellHost();
  assertExactDataRecord(reference, REFERENCE_FIELDS, "governed Authority Cell reference");
  assertExactDataRecord(options, Reflect.ownKeys(options).filter((key): key is string => typeof key === "string"), "governed Authority Cell options");
  const optionKeys = Reflect.ownKeys(options);
  if (optionKeys.some(key => typeof key !== "string" || !OPTION_FIELDS.includes(key as typeof OPTION_FIELDS[number]))) throw new TypeError("governed Authority Cell options contain an unknown field");
  const read = <T>(record: object, key: PropertyKey): T => Object.getOwnPropertyDescriptor(record, key)!.value as T;
  const ref = Object.fromEntries(REFERENCE_FIELDS.map(key => [key, read(reference, key)])) as unknown as GovernedAuthorityCellReferenceV1;
  if (ref.v !== "reelier.governed-authority-cell-reference/v1" || typeof ref.tenant !== "string" || !ID.test(ref.tenant) || typeof ref.governanceRef !== "string" || !ID.test(ref.governanceRef) || typeof ref.expectedManifestDigest !== "string" || !DIGEST.test(ref.expectedManifestDigest) || typeof ref.expectedTrustHeadDigest !== "string" || !DIGEST.test(ref.expectedTrustHeadDigest)) throw new TypeError("governed Authority Cell reference is invalid");
  if (ref.tenant !== config.tenant) throw new TypeError("governed Authority Cell tenant mismatch");
  const values = Object.fromEntries(optionKeys.map(key => [key, read(options, key)])) as GovernedAuthorityCellOptionsV1;
  if (!!values.signedTopologyEvidence !== !!values.topologySigner) throw new TypeError("signed topology evidence and topology signer must be paired");
  if (!!values.signedLease !== !!values.leaseSigner) throw new TypeError("signed lease and lease signer must be paired");
  if (config.nativeHttpsRoutes?.length && (!values.routeAuthority || !values.authenticatedProviderIdentity || !values.verifyAuthenticatedProviderIdentity || !values.certifiedDispatch)) throw new TypeError("native route authority, provider identity, identity verifier, and certified dispatch must be paired");
  const governance = await loadProfileGovernanceFromOperatorTrust({ tenant: ref.tenant, governanceRef: ref.governanceRef, expectedManifestDigest: ref.expectedManifestDigest, expectedTrustHeadDigest: ref.expectedTrustHeadDigest, homedir: os.homedir(), verificationTime: new Date() });
  if(!values.receiptSigningAuthority)throw new TypeError("governed Authority Cell requires receipt signing authority");
  if(!config.deploymentPath||!config.jobCardTrustPinPath)throw new TypeError("governed Authority Cell requires an actual deployment and external Job Card trust pin");
  const jobCardTrustPin=JSON.parse(await readFile(config.jobCardTrustPinPath,"utf8")) as JobCardTrustPinV1,deployment=await loadAuthorityDeployment(config.deploymentPath,{jobCardTrustPin});if(!deployment.jobCard||!deployment.jobCardAuthority)throw new TypeError("governed deployment lacks signed Job Card authority");
  const identifiers=jobCardTrustPin.signedReadiness.identifiers,observedAt=new Date(),trustView=createCurrentAuthorityTrustView({tenant:ref.tenant,authorityCellId:identifiers.authorityCellId,taskId:identifiers.taskId,observedAt,jobCardTrustPin}),gateSigner=await loadExistingLocalGateSigner(config.gateKeyFile??path.join(config.receiptDir,"..","keys","local-gate.pem")),governanceState=admittedProfileGovernanceState(governance),human=jobCardTrustPin.keyDescriptors.find(item=>item.keyId===jobCardTrustPin.signedReadiness.signerKeyId);if(!human)throw new TypeError("governed Job Card human signer is absent");
  const segregation={mode:"governed" as const,profileCertifier:governanceState.certifier,profileOperator:governanceState.operator,jobCardHuman:{signerId:human.keyId,publicKeySpkiBase64:human.publicKeySpkiBase64},localGate:{signerId:"local-gate",publicKeySpkiBase64:gateSigner.publicKey.export({type:"spki",format:"der"}).toString("base64")},...(values.topologySigner?{topology:{signerId:values.topologySigner.signerId,publicKeySpkiBase64:values.topologySigner.publicKey.export({type:"spki",format:"der"}).toString("base64")}}:{}),...(values.leaseSigner?{lease:{signerId:values.leaseSigner.signerId,publicKeySpkiBase64:values.leaseSigner.publicKey.export({type:"spki",format:"der"}).toString("base64")}}:{}),...(values.verifyAuthenticatedProviderIdentity?{providerIdentity:{signerId:values.verifyAuthenticatedProviderIdentity.signerId,publicKeySpkiBase64:values.verifyAuthenticatedProviderIdentity.publicKey.export({type:"spki",format:"der"}).toString("base64")}}:{})},signingAuthority=validateAuthorityReceiptSigningAuthority({trustView,signingAuthority:values.receiptSigningAuthority,segregation});
  const alias=deployment.jobCard.definitionAliases[0];if(!alias||deployment.jobCard.definitionAliases.length!==1)throw new TypeError("governed deployment must select one definition");const snapshot=deployment.states.find(item=>item.definitionAlias===alias);if(!snapshot)throw new TypeError("governed deployment lacks the selected Authority state");
  const packs=createFirstPartyPackRegistry(),sources=createFirstPartySourceRegistry(ref.tenant);let candidate:typeof snapshot.candidates[number]|undefined;for(const requester of deployment.jobCard.audiences){const selected=selectEligibleAuthorityContract({snapshot,tenant:ref.tenant,requester,definitionAlias:alias,now:observedAt,trustRoots:deployment.trustRoots,packs,sources,connectors:deployment.connectorRegistry});if(!selected.selected||selected.contractDigest!==governanceState.activation.contractDigest)throw new TypeError("governed deployment has no unique activation contract for every Job Card audience");if(candidate&&authorityDigest(candidate)!==authorityDigest(selected.selected.candidate))throw new TypeError("governed audiences selected different contract foundations");candidate=selected.selected.candidate;}if(!candidate)throw new TypeError("governed deployment has no exact selected contract foundation");
  const contractValue=parseCanonicalAuthorityJson("outcome-contract",Buffer.from(candidate.contractEnvelope.canonicalBase64,"base64").toString("utf8")),contract=Object.freeze({kind:"outcome-contract" as const,value:contractValue,digest:candidate.contractEnvelope.advertisedDigest,signerId:candidate.contractEnvelope.signerId,signature:candidate.contractEnvelope.signature}),delegation=Object.freeze(candidate.delegationEnvelopes.map(item=>Object.freeze({kind:"delegation-grant" as const,value:parseCanonicalAuthorityJson("delegation-grant",Buffer.from(item.canonicalBase64,"base64").toString("utf8")),digest:item.advertisedDigest,signerId:item.signerId,signature:item.signature}))),packManifest=parseAuthorityWire("pack-manifest",{v:"reelier.outcome-pack-manifest/v1",packId:governanceState.draft.packAlias,packDigest:(contractValue as any).packDigest,definitions:[alias]});
  const purposes=["outcome-contract","delegation-grant","gate-event","authority-evidence","authority-receipt"] as const,directRoots=purposes.map(purpose=>{const entry=deployment.trustEntries.find(root=>root.purposes.includes(purpose));if(!entry)throw new TypeError(`governed deployment lacks ${purpose} trust root`);return Object.freeze({...entry,purposes:Object.freeze([purpose])}) as TrustRootEntry;});if(new Set(directRoots.map(item=>item.signerId)).size!==directRoots.length)throw new TypeError("governed direct trust purposes must use unique signers");
  const parsedContract=contractValue as Readonly<{connectorId:string;accountId:string;sourceAuthority:Readonly<{allowedReadEndpointIds:readonly string[]}>}>,registration=deployment.connectors.find(item=>item.tenant===ref.tenant&&item.connectorId===parsedContract.connectorId&&item.accountId===parsedContract.accountId),routes=config.nativeHttpsRoutes??[];if(!registration)throw new TypeError("governed deployment lacks the selected connector registration");const writes=routes.filter(route=>route.connectorId===registration.connectorId&&route.accountId===registration.accountId&&route.providerAccountIdentity===registration.providerAccountIdentity&&route.allowedMethods.some(method=>method!=="GET"));if(writes.length!==1)throw new TypeError("governed route substrate must have exactly one selected write endpoint");const writeRoute=writes[0]!,readRoute=routes.find(route=>route.endpointId===writeRoute.readEndpointId);if(!readRoute||!readRoute.allowedMethods.includes("GET")||!parsedContract.sourceAuthority.allowedReadEndpointIds.includes(readRoute.endpointId)||writeRoute.projectionSchemaDigest!==readRoute.projectionSchemaDigest)throw new TypeError("governed write/read route authority join is invalid");const routeScope=parseAuthorityRouteScope({v:"reelier.authority-route-scope/v1",tenant:ref.tenant,definitionAlias:alias,connectorRegistrationDigest:connectorRegistrationDigest(deployment.connectorRegistry,ref.tenant,registration.connectorId,registration.accountId),operatorConfigurationDigest:registration.operatorConfigurationDigest,routeDigest:jsonHttpsRouteDigest(writeRoute),providerId:writeRoute.providerId,connectorId:writeRoute.connectorId,accountId:writeRoute.accountId,providerAccountIdentity:writeRoute.providerAccountIdentity,endpointId:writeRoute.endpointId,credentialSlotId:writeRoute.credentialSlotId,sourceReadRouteDigest:jsonHttpsRouteDigest(readRoute),projectionSchemaDigest:writeRoute.projectionSchemaDigest}),routeScopeDigest=authorityDigest(routeScope),jobDigest=signedJobCardDigest(deployment.jobCard),authorityHead=currentAuthorityTrustViewState(trustView).trustHeadDigest;if(jobDigest!==governanceState.activation.jobCardDigest||routeScopeDigest!==governanceState.activation.routeScopeDigest||authorityHead!==governanceState.activation.authorityTrustHeadDigest)throw new TypeError("governed activation does not match actual Job Card, route scope, or Authority trust head");
  const deploymentSnapshot=parseAuthorityDeploymentSnapshot({v:"reelier.authority-deployment-snapshot/v1",tenant:ref.tenant,jobCardDigest:jobDigest,jobCardAuthorityDigest:authorityDigest(deployment.jobCardAuthority),authorityStateDigest:authorityDigest(snapshot),connectorRegistryDigest:authorityDigest(deployment.connectors.map(item=>connectorRegistrationDigest(deployment.connectorRegistry,item.tenant,item.connectorId,item.accountId)).sort()),trustRootSetDigest:trustRootSetDigest(createTrustRoots(directRoots),ref.tenant),connectionDescriptorsDigest:authorityDigest(deployment.connectionDescriptors),connectionAdoptionsDigest:authorityDigest(deployment.connectionAdoptions),enforcementDigest:authorityDigest(deployment.enforcement),routeScopeDigest});if(authorityDigest(deploymentSnapshot)!==governanceState.activation.deploymentDigest)throw new TypeError("governed deployment snapshot does not match activation");
  const profileTrustRoots=createProfileVerificationRoots([{tenant:governanceState.trustPin.tenant,governanceRef:governanceState.trustPin.governanceRef,signerId:governanceState.trustPin.certifier.signerId,purpose:governanceState.trustPin.certifier.purpose,publicKeySpkiBase64:governanceState.trustPin.certifier.publicKeySpkiBase64,currentTrustEvents:governanceState.trustPin.currentTrustEvents,currentTrustEventsDigest:governanceState.trustPin.currentTrustEventsDigest,trustHeadDigest:governanceState.trustPin.trustHeadDigest},{tenant:governanceState.trustPin.tenant,governanceRef:governanceState.trustPin.governanceRef,signerId:governanceState.trustPin.operator.signerId,purpose:governanceState.trustPin.operator.purpose,publicKeySpkiBase64:governanceState.trustPin.operator.publicKeySpkiBase64,currentTrustEvents:governanceState.trustPin.currentTrustEvents,currentTrustEventsDigest:governanceState.trustPin.currentTrustEventsDigest,trustHeadDigest:governanceState.trustPin.trustHeadDigest}]);
  const reserveAuthorities=new Map<string,Readonly<{signingAuthority:typeof signingAuthority;jobCardTrustPin:JobCardTrustPinV1;observedAt:string}>>(),governedPublication=createProfileGovernedAuthorityReceiptPublication({rootDir:config.receiptDir,governance,signedJobCard:deployment.jobCard,deploymentSnapshot,expectedRouteScopeDigest:governanceState.activation.routeScopeDigest,foundations:{contract,delegation,packManifest},signingAuthority,currentAuthority:capabilityDigest=>{const current=reserveAuthorities.get(capabilityDigest);if(!current)throw new TypeError("fresh reserve-time receipt authority is absent or already consumed");reserveAuthorities.delete(capabilityDigest);return current;},verification:{profileTrustRoots,profilePacks:packs,jobCardTrustPin,currentAuthorityTrustEvents:jobCardTrustPin.currentTrustEvents,directAuthorityRoots:directRoots,expectedTenant:ref.tenant,expectedAuthorityCellId:identifiers.authorityCellId,expectedTaskId:identifiers.taskId},...(values.portableReceiptPublication?{portablePublication:values.portableReceiptPublication}:{})});
  const externalRevalidate=async(intent?:Readonly<import("../ledger.js").ReservationIntent>)=>{const freshPin=JSON.parse(await readFile(config.jobCardTrustPinPath!,"utf8")) as JobCardTrustPinV1;if(authorityDigest(freshPin.signedReadiness)!==authorityDigest(jobCardTrustPin.signedReadiness)||authorityDigest(freshPin.keyDescriptors)!==authorityDigest(jobCardTrustPin.keyDescriptors))throw new TypeError("governed Authority immutable readiness changed");const freshObservedAt=new Date(),freshView=createCurrentAuthorityTrustView({tenant:ref.tenant,authorityCellId:identifiers.authorityCellId,taskId:identifiers.taskId,observedAt:freshObservedAt,jobCardTrustPin:freshPin}),freshSigningAuthority=validateAuthorityReceiptSigningAuthority({trustView:freshView,signingAuthority:values.receiptSigningAuthority!,segregation});if(intent){const route=intent.routeAuthority;if(!route||authorityDigest({v:"reelier.authority-route-scope/v1",tenant:ref.tenant,definitionAlias:alias,connectorRegistrationDigest:route.connectorRegistrationDigest,operatorConfigurationDigest:route.operatorConfigurationDigest,routeDigest:route.routeDigest,providerId:route.providerId,connectorId:route.connectorId,accountId:route.accountId,providerAccountIdentity:route.providerAccountIdentity,endpointId:route.endpointId,credentialSlotId:route.credentialSlotId,sourceReadRouteDigest:route.sourceReadRouteDigest,projectionSchemaDigest:route.projectionSchemaDigest})!==routeScopeDigest)throw new TypeError("governed reservation route scope changed");reserveAuthorities.set(intent.capabilityDigest,Object.freeze({signingAuthority:freshSigningAuthority,jobCardTrustPin:freshPin,observedAt:freshObservedAt.toISOString()}));}};
  const runtime = await createAdmittedLocalAuthorityRuntime(config, governance, values,{gateSigner,deployment,governedPublication,externalRevalidate});
  return createAuthorityHostServer(config, runtime, values.principalRegistry ? { principalRegistry: values.principalRegistry } : {});
}
