import { createPublicKey, type KeyObject } from "node:crypto";
import type { AuthoritySignature, AuthorityReceipt, AuthorityReceiptBundle, AuthorityWireByKind, SignedAuthorityArtifact } from "../types.js";
import { authorityDigest, parseAuthorityWire } from "../wire.js";
import { signAuthorityDigest, verifyAuthoritySignature } from "../crypto.js";
import { createAuthorityEvidence, createAuthorityReceipt, createAuthorityReceiptBundle } from "../evidence.js";
import type { DispatchOutcome, DispatchRequestState } from "./dispatch.js";
import { currentAuthorityTrustViewState, type CurrentAuthorityTrustViewV1 } from "../trust.js";
import { assertCertificationLifecycleTrustContext, verifyCertificationArtifactKeyBinding, type CertificationArtifactKeyBindingCommitmentV1, type CertificationArtifactKeyBindingV1, type CertificationLifecycleAuthorityMaterial } from "../certification/lifecycle-authority.js";

export type ProducedReceiptKindV1="source-bundle"|"compiled-capability"|"transport-effect"|"authority-evidence"|"authority-receipt"|"pack-manifest";
type SignerPurpose={sourceBundle:"source-bundle";compiledCapability:"compiled-capability";transportEffect:"transport-effect";evidence:"authority-evidence";receipt:"authority-receipt";packManifest:"pack-manifest"};
export type PurposeBoundReceiptSignerV1<K extends keyof SignerPurpose>=Readonly<{purpose:SignerPurpose[K];signerId:string;publicKey:KeyObject;sign(input:Readonly<{purpose:SignerPurpose[K];digest:string}>):Promise<AuthoritySignature>}>;
export interface AuthorityReceiptSigningAuthorityV1{readonly artifactAuthorization:Readonly<{binding:CertificationArtifactKeyBindingV1;commitment:CertificationArtifactKeyBindingCommitmentV1}>;readonly sourceBundle:PurposeBoundReceiptSignerV1<"sourceBundle">;readonly compiledCapability:PurposeBoundReceiptSignerV1<"compiledCapability">;readonly transportEffect:PurposeBoundReceiptSignerV1<"transportEffect">;readonly evidence:PurposeBoundReceiptSignerV1<"evidence">;readonly receipt:PurposeBoundReceiptSignerV1<"receipt">;readonly packManifest:PurposeBoundReceiptSignerV1<"packManifest">}
export type ReceiptSigningSegregationV1=Readonly<{mode:"lifecycle";lifecycleContext:object}>|Readonly<{mode:"governed";profileCertifier:Readonly<{signerId:string;publicKeySpkiBase64:string}>;profileOperator:Readonly<{signerId:string;publicKeySpkiBase64:string}>;jobCardHuman:Readonly<{signerId:string;publicKeySpkiBase64:string}>;localGate:Readonly<{signerId:string;publicKeySpkiBase64:string}>;topology?:Readonly<{signerId:string;publicKeySpkiBase64:string}>;lease?:Readonly<{signerId:string;publicKeySpkiBase64:string}>;providerIdentity?:Readonly<{signerId:string;publicKeySpkiBase64:string}>}>;
declare const validatedSigningAuthorityBrand:unique symbol;
export type ValidatedAuthorityReceiptSigningAuthorityV1=Readonly<{readonly[validatedSigningAuthorityBrand]:true}>;
type ValidatedState=Readonly<{trustView?:CurrentAuthorityTrustViewV1;signingAuthority:AuthorityReceiptSigningAuthorityV1;segregation:ReceiptSigningSegregationV1}>;
const validatedStates=new WeakMap<object,ValidatedState>();

export function validateAuthorityReceiptSigningAuthority(input:Readonly<{trustView:CurrentAuthorityTrustViewV1;signingAuthority:AuthorityReceiptSigningAuthorityV1;segregation:ReceiptSigningSegregationV1}>):ValidatedAuthorityReceiptSigningAuthorityV1{
  exact(input,["trustView","signingAuthority","segregation"],"receipt signing validation input");
  const trust=currentAuthorityTrustViewState(input.trustView),authority=input.signingAuthority;exact(authority,["artifactAuthorization","sourceBundle","compiledCapability","transportEffect","evidence","receipt","packManifest"],"receipt signing authority");exact(authority.artifactAuthorization,["binding","commitment"],"artifact authorization");
  verifyCertificationArtifactKeyBinding(authority.artifactAuthorization.binding,authority.artifactAuthorization.commitment,{descriptors:trust.descriptors,signedReadiness:trust.pin.signedReadiness,now:new Date(trust.observedAt)});
  const signers=[authority.sourceBundle,authority.compiledCapability,authority.transportEffect,authority.evidence,authority.receipt,authority.packManifest] as readonly PurposeBoundReceiptSignerV1<any>[];
  const expected:SignerPurpose[keyof SignerPurpose][]=["source-bundle","compiled-capability","transport-effect","authority-evidence","authority-receipt","pack-manifest"];
  for(let index=0;index<signers.length;index++){const signer=signers[index]!;exact(signer,["purpose","signerId","publicKey","sign"],`receipt signer ${expected[index]}`);if(signer.purpose!==expected[index]||signer.publicKey.type!=="public"||signer.publicKey.asymmetricKeyType!=="ed25519"||typeof signer.sign!=="function")throw new TypeError("receipt signer purpose or Ed25519 key is invalid");}
  if(new Set(signers.map(item=>item.signerId)).size!==signers.length||new Set(signers.map(item=>spki(item.publicKey))).size!==signers.length)throw new TypeError("receipt signer purposes must use unique keys");
  const entries=authority.artifactAuthorization.binding.entries;
  for(const [purpose,signer] of [["source-bundle",authority.sourceBundle],["compiled-capability",authority.compiledCapability],["transport-effect",authority.transportEffect],["pack-manifest",authority.packManifest]] as const){const entry=entries.find(item=>item.artifactPurpose===purpose);if(!entry||entry.keyId!==signer.signerId||entry.publicKeySpkiBase64!==spki(signer.publicKey))throw new TypeError("artifact receipt signer does not match external binding");}
  for(const signer of [authority.evidence,authority.receipt]){const descriptor=trust.descriptors.find(item=>item.keyId===signer.signerId&&item.purpose===signer.purpose&&item.publicKeySpkiBase64===spki(signer.publicKey));if(!descriptor||!trust.activeDescriptorDigests.has(authorityDigest(descriptor)))throw new TypeError("direct receipt signer is not active under current Authority trust");}
  if(input.segregation.mode==="governed"){const anchors=[input.segregation.profileCertifier,input.segregation.profileOperator,input.segregation.jobCardHuman,input.segregation.localGate,input.segregation.topology,input.segregation.lease,input.segregation.providerIdentity].filter((item):item is Readonly<{signerId:string;publicKeySpkiBase64:string}>=>Boolean(item));for(const signer of signers)if(anchors.some(anchor=>anchor.signerId===signer.signerId||anchor.publicKeySpkiBase64===spki(signer.publicKey)))throw new TypeError("receipt signing authority violates governed role segregation");}
  const handle=Object.freeze(new Proxy(Object.freeze(Object.create(null)),{})) as ValidatedAuthorityReceiptSigningAuthorityV1;validatedStates.set(handle,Object.freeze({trustView:input.trustView,signingAuthority:authority,segregation:input.segregation}));return handle;
}

export function validateLifecycleAuthorityReceiptSigningAuthority(material:CertificationLifecycleAuthorityMaterial):ValidatedAuthorityReceiptSigningAuthorityV1{
  assertCertificationLifecycleTrustContext(material);if(!material.artifactAuthorization)throw new TypeError("lifecycle artifact authorization is absent");
  const signer=(purpose:any,key:any)=>Object.freeze({purpose,signerId:key.descriptor.keyId,publicKey:createPublicKey(key.privateKey),async sign(input:any){return signAuthorityDigest(key.privateKey,input.purpose,input.digest);}});
  const authority:AuthorityReceiptSigningAuthorityV1=Object.freeze({artifactAuthorization:material.artifactAuthorization,sourceBundle:signer("source-bundle",material.artifacts.get("source-bundle")!),compiledCapability:signer("compiled-capability",material.artifacts.get("compiled-capability")!),transportEffect:signer("transport-effect",material.artifacts.get("transport-effect")!),evidence:signer("authority-evidence",material.direct.get("authority-evidence")!),receipt:signer("authority-receipt",material.direct.get("authority-receipt")!),packManifest:signer("pack-manifest",material.artifacts.get("pack-manifest")!)});
  const handle=Object.freeze(new Proxy(Object.freeze(Object.create(null)),{})) as ValidatedAuthorityReceiptSigningAuthorityV1;validatedStates.set(handle,Object.freeze({signingAuthority:authority,segregation:Object.freeze({mode:"lifecycle",lifecycleContext:material})}));return handle;
}

export interface AuthorityReceiptFoundationsV1{readonly contract:SignedAuthorityArtifact<"outcome-contract">;readonly delegation:readonly SignedAuthorityArtifact<"delegation-grant">[];readonly gateEvent:SignedAuthorityArtifact<"gate-event">;readonly packManifest:AuthorityWireByKind["pack-manifest"]}
export interface AuthorityReceiptBundleConstructionInputV1{readonly phase:"reservation"|"dispatch"|"cancelled"|"ambiguous"|"reconcile";readonly state:DispatchRequestState;readonly outcome:DispatchOutcome;readonly observedAt:string;readonly foundations:AuthorityReceiptFoundationsV1;readonly signingAuthority:ValidatedAuthorityReceiptSigningAuthorityV1;readonly priorReceipt?:AuthorityReceipt;readonly recovered?:AuthorityReceiptBundle}

export async function constructAuthorityReceiptBundle(input:AuthorityReceiptBundleConstructionInputV1):Promise<AuthorityReceiptBundle>{
  const validated=validatedStates.get(input?.signingAuthority as object);if(!validated)throw new TypeError("validated signing authority is required");
  exact(input,["phase","state","outcome","observedAt","foundations","signingAuthority",...(Object.hasOwn(input,"priorReceipt")?["priorReceipt"]:[]),...(Object.hasOwn(input,"recovered")?["recovered"]:[])],"receipt construction input");
  const raw=input.state as any,decision=raw.signedDecision??(input.recovered?{decisionContext:input.recovered.receipt.value.decisionContext,decisionContextDigest:input.recovered.receipt.value.decisionContextDigest,gateEvent:input.recovered.gateEvent.value,gateEventDigest:input.recovered.gateEvent.digest}:undefined);if(!decision)throw new TypeError("receipt construction requires exact gate foundations");
  const contract=input.recovered?.contract??input.foundations.contract,delegation=input.recovered?.delegation??input.foundations.delegation,gateEvent=input.recovered?.gateEvent??input.foundations.gateEvent;
  const source=parseAuthorityWire("source-bundle",raw.source?.bundle??input.recovered?.sourceBundle.value),capability=parseAuthorityWire("compiled-capability",raw.capability??input.recovered?.capability.value),effect=parseAuthorityWire("transport-effect",raw.effect??input.recovered?.transportEffect.value);
  const resultDigest=input.phase==="reservation"?authorityDigest({reservationId:input.state.reservation.reservationId,phase:"reservation"}):input.outcome.resultDigest,receiptId=`receipt_${authorityDigest({reservationId:input.state.reservation.reservationId,phase:input.phase,result:resultDigest}).slice(7,31)}`,at=canonicalTime(input.observedAt);
  const timeline:any[]=[{state:"reserved",at,eventDigest:authorityDigest({state:"reserved",reservationId:input.state.reservation.reservationId})}];if(input.phase!=="reservation"&&input.phase!=="cancelled")timeline.push({state:"dispatched",at,eventDigest:authorityDigest({state:"dispatched",reservationId:input.state.reservation.reservationId})});if(input.phase!=="reservation"){const terminal=input.phase==="cancelled"?"cancelled":input.outcome.kind;timeline.push({state:terminal,at,eventDigest:authorityDigest({state:terminal,result:resultDigest})});}if(input.phase==="reconcile")timeline.push({state:"reconciled",at,eventDigest:authorityDigest({state:"reconciled",verdict:input.outcome.reconciliationStatus})});
  const evidence=createAuthorityEvidence({evidenceId:`evidence_${receiptId.slice(8)}`,receiptId,decisionContextDigest:decision.decisionContextDigest,gateEventDigest:gateEvent.digest,effectDigest:authorityDigest(effect),reservationId:`reservation_${authorityDigest(input.state.reservation.reservationId).slice(7,31)}`,timeline,dispatchedRequestDigest:input.phase==="reservation"||input.phase==="cancelled"?null:authorityDigest({v:"reelier.dispatched-request/v1",reservationId:input.state.reservation.reservationId,effectDigest:input.state.effectDigest,effect:input.state.effect}),providerResponseDigest:input.outcome.kind==="acknowledged"?input.outcome.providerResultDigest??input.outcome.resultDigest:null,reconciliation:{recipeId:(effect as any).reconciliation.recipeId,verdict:input.phase==="reservation"?"not-attempted":input.outcome.reconciliationStatus??"not-attempted",normalizedProjectionDigest:input.phase==="reservation"?null:input.outcome.normalizedProjectionDigest??null},topology:{egress:"unchecked",secretIsolation:"verified",ingressAuthentication:"verified",notes:"Hermetic in-Cell provider; production topology not asserted."}});
  const receipt=createAuthorityReceipt({receiptId,gateEventDigest:gateEvent.digest,decisionContextDigest:decision.decisionContextDigest,decisionContext:decision.decisionContext,evidence,priorReceiptDigest:input.priorReceipt?authorityDigest(input.priorReceipt):null,claims:{authorization:"verified",sourceCompleteness:"verified",dispatch:input.phase==="reservation"||input.phase==="cancelled"?"absent":"verified",providerAcknowledgment:input.outcome.kind==="acknowledged"?"verified":"unchecked",reconciliation:input.outcome.reconciliationStatus==="matched"?"verified":"unchecked",topology:"unchecked",completeness:"unchecked"}});
  const authority=validated.signingAuthority;
  return createAuthorityReceiptBundle({v:"reelier.authority-receipt-bundle/v1",contract,delegation,sourceBundle:await signed("source-bundle",source,authority.sourceBundle),capability:await signed("compiled-capability",capability,authority.compiledCapability),transportEffect:await signed("transport-effect",effect,authority.transportEffect),gateEvent,evidence:await signed("authority-evidence",evidence,authority.evidence),receipt:await signed("authority-receipt",receipt,authority.receipt),packManifest:input.recovered?.packManifest??await signed("pack-manifest",input.foundations.packManifest,authority.packManifest)});
}
export function validatedAuthorityReceiptSigningState(handle:ValidatedAuthorityReceiptSigningAuthorityV1):ValidatedState{const state=validatedStates.get(handle as object);if(!state)throw new TypeError("validated signing authority is required");return state;}
async function signed<K extends SignerPurpose[keyof SignerPurpose]>(kind:K,value:unknown,signer:PurposeBoundReceiptSignerV1<any>):Promise<any>{const parsed=parseAuthorityWire(kind,value),digest=authorityDigest(parsed),signature=await signer.sign({purpose:kind,digest});if(!verifyAuthoritySignature(signer.publicKey,kind,digest,signature))throw new TypeError(`returned ${kind} signature is invalid`);return Object.freeze({kind,signerId:signer.signerId,digest,value:parsed,signature});}
function exact(value:unknown,keys:readonly string[],label:string):asserts value is Record<string,any>{if(!value||typeof value!=="object"||Object.getPrototypeOf(value)!==Object.prototype)throw new TypeError(`${label} must be a plain record`);const d=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(value).length!==keys.length||keys.some(key=>!d[key]||!("value" in d[key]!)||!d[key]!.enumerable))throw new TypeError(`${label} must contain exact own data fields`);}
function spki(key:KeyObject):string{return key.export({type:"spki",format:"der"}).toString("base64");}
function canonicalTime(value:string):string{const epoch=Date.parse(value);if(!Number.isFinite(epoch)||new Date(epoch).toISOString()!==value)throw new TypeError("receipt observedAt is invalid");return value;}
