import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { StaticPackDefinition, StaticPackCompileInput } from "../../authority/pack.js";
import { slackChannelTopicAlias, slackChannelTopicDefinitionDigest, slackChannelTopicManifest, slackChannelTopicPackDigest, slackChannelTopicPolicySchemaId, slackChannelTopicProjectionSchemaId, slackChannelTopicReadEndpointId, slackChannelTopicRecipeId, slackChannelTopicResolverId, slackChannelTopicRiskClass, slackChannelTopicWriteEndpointId } from "./manifest.js";
import type { SlackChannelTopicProjection } from "./manifest.js";

export function validateSlackChannelTopicChoices(value: unknown): Record<string, never> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 0) throw new TypeError("Slack channel topic choices must be empty"); return Object.freeze({}); }
export function parseSlackChannelTopicPolicy(value: unknown): Readonly<{ topic: string }> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Slack channel topic policy must be an object"); const policy = value as Record<string, unknown>; if (Object.keys(policy).length !== 1 || typeof policy.topic !== "string" || policy.topic.length > 250) throw new TypeError("Slack channel topic policy is closed and bounded"); return Object.freeze({ topic: policy.topic }); }
export function compileSlackChannelTopic(input: Readonly<{ source: { projection: Record<string, unknown> }; policy: unknown }>): unknown { const source = input.source.projection as unknown as SlackChannelTopicProjection; if (!source.isPrivate) throw new TypeError("Slack channel topic pack requires a private channel"); const policy = input.policy as { topic: string }; const body = authorityCanonicalBytes({ channel: source.channelId, topic: policy.topic }); return { v: "reelier.transport-effect/v1", endpointId: slackChannelTopicWriteEndpointId, method: "POST", path: "/api/conversations.setTopic", query: "", headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: slackChannelTopicRiskClass, idempotency: "reconcile-only", preconditions: [{ kind: "slack-topic-digest", digest: authorityDigest({ v: "reelier.slack-topic/v1", topic: source.topic }) }], reconciliation: { recipeId: slackChannelTopicRecipeId } }; }
export const slackChannelTopicDefinition: StaticPackDefinition = Object.freeze({ alias: slackChannelTopicAlias, packDigest: slackChannelTopicPackDigest, definitionDigest: slackChannelTopicDefinitionDigest, resolverId: slackChannelTopicResolverId, projectionSchemaId: slackChannelTopicProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [slackChannelTopicReadEndpointId], writeEndpointIds: [slackChannelTopicWriteEndpointId], riskClasses: [slackChannelTopicRiskClass], policySchemaId: slackChannelTopicPolicySchemaId, requiredGroundedPointers: ["/teamId", "/channelId", "/channelName", "/isPrivate", "/topic"], validateChoices: validateSlackChannelTopicChoices, parsePolicy: parseSlackChannelTopicPolicy, compile: (input: StaticPackCompileInput) => compileSlackChannelTopic({ source: input.source, policy: input.policy }) });
