import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { StaticPackCompileInput, StaticPackDefinition } from "../../authority/pack.js";
import { cloudflareDnsRecordSetAlias, cloudflareDnsRecordSetDefinitionDigest, cloudflareDnsRecordSetPackDigest, cloudflareDnsRecordSetPolicySchemaId, cloudflareDnsRecordSetProjectionSchemaId, cloudflareDnsRecordSetReadEndpointId, cloudflareDnsRecordSetRecipeId, cloudflareDnsRecordSetResolverId, cloudflareDnsRecordSetRiskClass, cloudflareDnsRecordSetWriteEndpointId } from "./manifest.js";
import type { CloudflareDnsRecordProjection, CloudflareDnsRecordType } from "./manifest.js";
export interface CloudflareDnsRecordPolicy { readonly accountId: string; readonly zoneId: string; readonly name: string; readonly type: CloudflareDnsRecordType; readonly desiredContent: string; readonly desiredTtl: number; readonly desiredProxied: boolean }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Cloudflare ${label} is invalid`); return value; }
function dns(value: unknown): string { if (typeof value !== "string" || !/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(value.toLowerCase())) throw new TypeError("Cloudflare policy name is invalid"); return value.toLowerCase(); }
function ttl(value: unknown): number { if (!Number.isSafeInteger(value) || (value as number) !== 1 && ((value as number) < 60 || (value as number) > 86400)) throw new TypeError("Cloudflare policy ttl is invalid"); return value as number; }
export function validateCloudflareDnsRecordChoices(value: unknown): Record<string, never> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 0) throw new TypeError("Cloudflare DNS choices must be empty"); return Object.freeze({}); }
export function parseCloudflareDnsRecordPolicy(value: unknown): CloudflareDnsRecordPolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Cloudflare DNS policy must be an object"); const raw = value as Record<string, unknown>; const keys = ["accountId", "zoneId", "name", "type", "desiredContent", "desiredTtl", "desiredProxied"]; if (Object.keys(raw).length !== keys.length || Object.keys(raw).some(key => !keys.includes(key))) throw new TypeError("Cloudflare DNS policy is closed"); if (raw.type !== "A" && raw.type !== "AAAA" && raw.type !== "CNAME" && raw.type !== "TXT") throw new TypeError("Cloudflare DNS policy type is unsupported"); if (typeof raw.desiredContent !== "string" || raw.desiredContent.length === 0 || raw.desiredContent.length > 2048 || /[\r\n]/.test(raw.desiredContent)) throw new TypeError("Cloudflare DNS desired content is invalid"); if (typeof raw.desiredProxied !== "boolean") throw new TypeError("Cloudflare DNS desired proxied is invalid"); return Object.freeze({ accountId: id(raw.accountId, "accountId"), zoneId: id(raw.zoneId, "zoneId"), name: dns(raw.name), type: raw.type, desiredContent: raw.desiredContent, desiredTtl: ttl(raw.desiredTtl), desiredProxied: raw.desiredProxied }); }
export function compileCloudflareDnsRecordSet(input: Readonly<{ source: CloudflareDnsRecordProjection; policy: CloudflareDnsRecordPolicy }>): Readonly<{ v: "reelier.transport-effect/v1"; endpointId: string; method: "PUT"; path: string; query: string; headers: Record<string, string>; bodyBase64: string; riskClass: string; idempotency: "native"; preconditions: { kind: string; digest: string }[]; reconciliation: { recipeId: string } }> { const { source, policy } = input; if (source.accountId !== policy.accountId || source.zoneId !== policy.zoneId || source.name !== policy.name || source.type !== policy.type) throw new TypeError("Cloudflare DNS account or resource is outside the signed policy"); if (source.content === policy.desiredContent && source.ttl === policy.desiredTtl && source.proxied === policy.desiredProxied) throw new TypeError("Cloudflare DNS record already has the desired state"); const body = authorityCanonicalBytes({ type: source.type, name: source.name, content: policy.desiredContent, ttl: policy.desiredTtl, proxied: policy.desiredProxied }); return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: cloudflareDnsRecordSetWriteEndpointId, method: "PUT", path: `/client/v4/zones/${source.zoneId}/dns_records/${source.recordId}`, query: "", headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: cloudflareDnsRecordSetRiskClass, idempotency: "native", preconditions: [{ kind: "cloudflare-dns-record", digest: authorityDigest({ v: "reelier.cloudflare-dns-record/v1", accountId: source.accountId, zoneId: source.zoneId, recordId: source.recordId, name: source.name, type: source.type, content: source.content, ttl: source.ttl, proxied: source.proxied }) }], reconciliation: { recipeId: cloudflareDnsRecordSetRecipeId } }); }
export const cloudflareDnsRecordSetDefinition: StaticPackDefinition = Object.freeze({ alias: cloudflareDnsRecordSetAlias, packDigest: cloudflareDnsRecordSetPackDigest, definitionDigest: cloudflareDnsRecordSetDefinitionDigest, resolverId: cloudflareDnsRecordSetResolverId, projectionSchemaId: cloudflareDnsRecordSetProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [cloudflareDnsRecordSetReadEndpointId], writeEndpointIds: [cloudflareDnsRecordSetWriteEndpointId], riskClasses: [cloudflareDnsRecordSetRiskClass], policySchemaId: cloudflareDnsRecordSetPolicySchemaId, requiredGroundedPointers: ["/accountId", "/zoneId", "/recordId", "/name", "/type", "/content", "/ttl", "/proxied"], validateChoices: validateCloudflareDnsRecordChoices, parsePolicy: parseCloudflareDnsRecordPolicy, compile: (input: StaticPackCompileInput) => compileCloudflareDnsRecordSet({ source: input.source.projection as CloudflareDnsRecordProjection, policy: input.policy as CloudflareDnsRecordPolicy }) });
