import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import { authorityDigest } from "../../authority/wire.js";
import { cloudflareDnsRecordSetDefinitionDigest, cloudflareDnsRecordSetProjectionSchemaId, cloudflareDnsRecordSetReadEndpointId, cloudflareDnsRecordSetResolverId } from "./manifest.js";
import type { CloudflareDnsRecordProjection, CloudflareDnsRecordType } from "./manifest.js";
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Cloudflare DNS response must be an object"); return value as Record<string, unknown>; }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Cloudflare ${label} is invalid`); return value; }
function dns(value: unknown, label: string): string { if (typeof value !== "string" || value.length > 253 || !/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(value.toLowerCase())) throw new TypeError(`Cloudflare ${label} is invalid`); return value.toLowerCase(); }
function normalize(rawBytes: Uint8Array): CloudflareDnsRecordProjection { let parsed: unknown; try { parsed = JSON.parse(Buffer.from(rawBytes).toString("utf8")); } catch { throw new TypeError("Cloudflare DNS response is not JSON"); } const root = object(parsed); const record = root.result && typeof root.result === "object" && !Array.isArray(root.result) ? object(root.result) : root; const type = record.type; if (type !== "A" && type !== "AAAA" && type !== "CNAME" && type !== "TXT") throw new TypeError("Cloudflare DNS type is unsupported"); const rawTtl = record.ttl; if (!Number.isSafeInteger(rawTtl) || (rawTtl as number) !== 1 && ((rawTtl as number) < 60 || (rawTtl as number) > 86400)) throw new TypeError("Cloudflare DNS ttl is invalid"); const ttl = rawTtl as number; if (typeof record.content !== "string" || record.content.length === 0 || record.content.length > 2048 || /[\r\n]/.test(record.content)) throw new TypeError("Cloudflare DNS content is invalid"); return Object.freeze({ accountId: id(root.accountId ?? record.accountId, "accountId"), zoneId: id(root.zoneId ?? record.zoneId, "zoneId"), recordId: id(record.id, "recordId"), name: dns(record.name, "name"), type, content: record.content, ttl, proxied: record.proxied === true }); }
export function createCloudflareDnsRecordSourceResolver(tenant: string = "*"): RegisteredSourceResolver { return Object.freeze({ tenant, resolverId: cloudflareDnsRecordSetResolverId, definitionDigest: cloudflareDnsRecordSetDefinitionDigest, projectionSchemaId: cloudflareDnsRecordSetProjectionSchemaId, readEndpointIds: [cloudflareDnsRecordSetReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: cloudflareDnsRecordSetReadEndpointId, opaqueHandle: refs.record }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>) => { if (input.observations.length !== 1) throw new TypeError("Cloudflare DNS source requires one observation"); const projection = normalize(Buffer.from(input.observations[0].bodyBase64, "base64")); const sourceIdentity = `cloudflare.${projection.accountId}.${projection.zoneId}.${projection.recordId}`; const triggerIdentity = authorityDigest({ v: "reelier.cloudflare-dns-trigger/v1", sourceIdentity, content: projection.content, ttl: projection.ttl, proxied: projection.proxied }).replace(":", "."); const claims = Object.keys(projection).map(key => ({ claimId: `cloudflare-${key}`, projectionPointer: `/${key}` })); return Object.freeze({ sourceIdentity, triggerIdentity, projection, claims: Object.freeze({ grounded: Object.freeze(claims), authored: Object.freeze([]), unresolved: Object.freeze([]) }) }) satisfies SourceProjection; } }); }
