import { createPublicKey } from "node:crypto";
import type { AuthorityReceiptBundle } from "../types.js";
import { authorityDigest } from "../wire.js";
import { verifyAuthorityReceiptBundle } from "../verify.js";
import { AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST } from "../adapter-contract.js";
import { verifyCertificationArtifactKeyBinding, type CertificationArtifactKeyBindingCommitmentV1, type CertificationArtifactKeyBindingV1 } from "./lifecycle-authority.js";
import type { AuthorityKeyDescriptorV1 } from "./authority.js";

export interface CertificationTaskReceiptGraphV1 { readonly v: "reelier.certification-task-receipt-graph/v1"; readonly adapterContractDigest: string; readonly taskId: string; readonly authorityCellId: string; readonly rootGrant: any; readonly grants: readonly any[]; readonly principals: readonly any[]; readonly allocations: readonly any[]; readonly budgetEvents: readonly any[]; readonly outcomes: readonly any[]; readonly exceptions: readonly any[]; readonly topology: Readonly<{ status: "unchecked" }>; readonly leases: Readonly<{ status: "absent"; entries: readonly never[] }>; readonly receipts: readonly AuthorityReceiptBundle[]; readonly priorReceiptLinks: readonly Readonly<{ receiptDigest: string; priorReceiptDigest: string | null }>[]; readonly binding: CertificationArtifactKeyBindingV1; readonly commitment: CertificationArtifactKeyBindingCommitmentV1; readonly keyDescriptors: readonly AuthorityKeyDescriptorV1[]; readonly signedReadiness: unknown }

export function createCertificationTaskReceiptGraph(input: Omit<CertificationTaskReceiptGraphV1, "v" | "adapterContractDigest" | "topology" | "leases" | "priorReceiptLinks">): CertificationTaskReceiptGraphV1 { const links = input.receipts.map(bundle => Object.freeze({ receiptDigest: authorityDigest(bundle.receipt.value), priorReceiptDigest: bundle.receipt.value.priorReceiptDigest })); return Object.freeze({ v: "reelier.certification-task-receipt-graph/v1", adapterContractDigest: AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST, ...input, topology: Object.freeze({ status: "unchecked" as const }), leases: Object.freeze({ status: "absent" as const, entries: Object.freeze([]) }), priorReceiptLinks: Object.freeze(links) }); }

export function verifyCertificationTaskReceiptGraph(value: unknown): Readonly<{ status: "verified"; digest: string }> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("receipt graph must be an object"); const g = value as any;
  const fields = ["v","adapterContractDigest","taskId","authorityCellId","rootGrant","grants","principals","allocations","budgetEvents","outcomes","exceptions","topology","leases","receipts","priorReceiptLinks","binding","commitment","keyDescriptors","signedReadiness"];
  if (Object.keys(g).length !== fields.length || Object.keys(g).some(key => !fields.includes(key)) || g.v !== "reelier.certification-task-receipt-graph/v1" || g.adapterContractDigest !== AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST) throw new TypeError("receipt graph is closed or contract mismatched");
  if (containsConfidential(g)) throw new TypeError("receipt graph contains confidential fields");
  if (!Array.isArray(g.receipts) || !Array.isArray(g.priorReceiptLinks) || g.receipts.length === 0 || g.receipts.length !== g.priorReceiptLinks.length || new Set(g.receipts.map((b: any) => b.receipt.value.receiptId)).size !== g.receipts.length) throw new TypeError("receipt graph receipt nodes are omitted or duplicated");
  verifyCertificationArtifactKeyBinding(g.binding, g.commitment, { descriptors: g.keyDescriptors, signedReadiness: g.signedReadiness });
  if (g.binding.taskId !== g.taskId || g.binding.authorityCellId !== g.authorityCellId || authorityDigest(g.rootGrant.grant) !== g.rootGrant.digest || g.rootGrant.grant.parentDigest !== null || g.grants.length !== 1 || g.grants[0].digest !== g.rootGrant.digest) throw new TypeError("receipt graph grant lineage is broken");
  if (g.allocations.length !== 1 || g.allocations[0].taskId !== g.taskId || g.allocations[0].effects !== g.allocations[0].consumed + g.allocations[0].remaining) throw new TypeError("receipt graph budget is imbalanced");
  const direct = g.keyDescriptors.filter((item: any) => item.role === "authority-cell").map((item: any) => ({ tenant: g.authorityCellId, signerId: item.keyId, principalId: item.purpose === "delegation-grant" ? g.rootGrant.grant.grantor : g.rootGrant.grant.grantee, publicKey: createPublicKey({ key: Buffer.from(item.publicKeySpkiBase64, "base64"), format: "der", type: "spki" }), purposes: [item.purpose] }));
  const delegated = g.binding.entries.map((item: any) => ({ tenant: g.authorityCellId, signerId: item.keyId, principalId: g.rootGrant.grant.grantee, publicKey: createPublicKey({ key: Buffer.from(item.publicKeySpkiBase64, "base64"), format: "der", type: "spki" }), purposes: [item.artifactPurpose] }));
  let prior: any; const remaining = [...g.receipts]; while (remaining.length) { const index = remaining.findIndex(bundle => bundle.receipt.value.priorReceiptDigest === (prior ? authorityDigest(prior) : null)); if (index < 0) throw new TypeError("receipt graph chain fork or broken prior link"); const [bundle] = remaining.splice(index, 1); verifyAuthorityReceiptBundle(bundle, { tenant: g.authorityCellId, trustRoots: [...direct, ...delegated], ...(prior ? { priorReceipt: prior } : {}) }); prior = bundle.receipt.value; }
  const expectedLinks = g.receipts.map((bundle: any) => ({ receiptDigest: authorityDigest(bundle.receipt.value), priorReceiptDigest: bundle.receipt.value.priorReceiptDigest })); if (authorityDigest(expectedLinks) !== authorityDigest(g.priorReceiptLinks)) throw new TypeError("receipt graph prior links mismatch");
  return Object.freeze({ status: "verified", digest: authorityDigest(g) });
}
function containsConfidential(value: unknown): boolean { if (!value || typeof value !== "object") return typeof value === "string" && /canary-private-token/i.test(value); for (const [key, child] of Object.entries(value as Record<string, unknown>)) { if (/^(bearerToken|credential|credentials|privateKey|secretToken|token)$/i.test(key) || containsConfidential(child)) return true; } return false; }
