import { createPublicKey } from "node:crypto";
import type { AuthorityReceiptBundle } from "../types.js";
import { authorityDigest } from "../wire.js";
import { verifyAuthorityReceiptBundle } from "../verify.js";
import { AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST } from "../adapter-contract.js";
import { verifyCertificationArtifactKeyBinding, type CertificationArtifactKeyBindingCommitmentV1, type CertificationArtifactKeyBindingV1 } from "./lifecycle-authority.js";
import type { AuthorityKeyDescriptorV1 } from "./authority.js";
import { verifySignedCertificationReadiness } from "./authority.js";
import type { JobCardTrustPinV1 } from "../host/deployment.js";
import type { AuthoritySignature } from "../types.js";
import { verifyAuthoritySignature } from "../crypto.js";

export interface CertificationTaskReceiptGraphV1 { readonly v: "reelier.certification-task-receipt-graph/v1"; readonly adapterContractDigest: string; readonly taskId: string; readonly authorityCellId: string; readonly rootGrant: any; readonly grants: readonly any[]; readonly principals: readonly any[]; readonly allocations: readonly any[]; readonly budgetEvents: readonly any[]; readonly outcomes: readonly any[]; readonly exceptions: readonly any[]; readonly topology: Readonly<{ status: "unchecked" }>; readonly leases: Readonly<{ status: "absent"; entries: readonly never[] }>; readonly receipts: readonly AuthorityReceiptBundle[]; readonly priorReceiptLinks: readonly Readonly<{ receiptDigest: string; priorReceiptDigest: string | null }>[]; readonly binding: CertificationArtifactKeyBindingV1; readonly commitment: CertificationArtifactKeyBindingCommitmentV1; readonly keyDescriptors: readonly AuthorityKeyDescriptorV1[]; readonly signedReadiness: unknown; readonly terminalCommitment: Readonly<{ v: "reelier.certification-task-graph-terminal/v1"; rootGrantDigest: string; contentDigest: string; counts: Readonly<Record<string, number>>; signerId: string; signature: AuthoritySignature }> }

export function createCertificationTaskReceiptGraph(input: Omit<CertificationTaskReceiptGraphV1, "v" | "adapterContractDigest" | "topology" | "leases" | "priorReceiptLinks" | "terminalCommitment"> & Readonly<{ terminalSigner: Readonly<{ signerId: string; sign(digest: string): AuthoritySignature }> }>): CertificationTaskReceiptGraphV1 { const { terminalSigner, ...nodes } = input, links = input.receipts.map(bundle => Object.freeze({ receiptDigest: authorityDigest(bundle.receipt.value), priorReceiptDigest: bundle.receipt.value.priorReceiptDigest })), topology = Object.freeze({ status: "unchecked" as const }), leases = Object.freeze({ status: "absent" as const, entries: Object.freeze([]) }), content = { v: "reelier.certification-task-receipt-graph/v1" as const, adapterContractDigest: AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST, ...nodes, topology, leases, priorReceiptLinks: links }, counts = Object.freeze({ grants: input.grants.length, principals: input.principals.length, allocations: input.allocations.length, budgetEvents: input.budgetEvents.length, outcomes: input.outcomes.length, exceptions: input.exceptions.length, receipts: input.receipts.length, priorReceiptLinks: links.length }), terminalBody = { v: "reelier.certification-task-graph-terminal/v1" as const, rootGrantDigest: input.rootGrant.digest, contentDigest: authorityDigest(content), counts, signerId: terminalSigner.signerId }, terminalCommitment = Object.freeze({ ...terminalBody, signature: terminalSigner.sign(authorityDigest(terminalBody)) }); return Object.freeze({ ...content, terminalCommitment }); }

export function verifyCertificationTaskReceiptGraph(value: unknown, options?: Readonly<{ trustPin: JobCardTrustPinV1 }>): Readonly<{ status: "verified"; digest: string }> {
  if (!options?.trustPin) throw new TypeError("external operator trust pin is required for graph verification");
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("receipt graph must be an object"); const g = value as any;
  const fields = ["v","adapterContractDigest","taskId","authorityCellId","rootGrant","grants","principals","allocations","budgetEvents","outcomes","exceptions","topology","leases","receipts","priorReceiptLinks","binding","commitment","keyDescriptors","signedReadiness","terminalCommitment"];
  if (Object.keys(g).length !== fields.length || Object.keys(g).some(key => !fields.includes(key)) || g.v !== "reelier.certification-task-receipt-graph/v1" || g.adapterContractDigest !== AUTHORITY_ADAPTER_CONTRACT_V1_DIGEST) throw new TypeError("receipt graph is closed or contract mismatched");
  if (containsConfidential(g)) throw new TypeError("receipt graph contains confidential fields");
  if (!Array.isArray(g.receipts) || !Array.isArray(g.priorReceiptLinks) || g.receipts.length === 0 || g.receipts.length !== g.priorReceiptLinks.length || new Set(g.receipts.map((b: any) => b.receipt.value.receiptId)).size !== g.receipts.length) throw new TypeError("receipt graph receipt nodes are omitted or duplicated");
  const pin = options.trustPin;
  verifySignedCertificationReadiness({ signed: pin.signedReadiness, readinessCandidate: pin.readinessCandidate, preflight: pin.preflight, humanTrustRoot: pin.humanTrustRoot, keyDescriptors: pin.keyDescriptors, trustEvents: pin.readinessTrustEvents });
  if (authorityDigest(g.keyDescriptors) !== authorityDigest(pin.keyDescriptors) || authorityDigest(g.signedReadiness) !== authorityDigest(pin.signedReadiness)) throw new TypeError("graph authority descriptors are not the external activated trust set");
  verifyCertificationArtifactKeyBinding(g.binding, g.commitment, { descriptors: pin.keyDescriptors, signedReadiness: pin.signedReadiness });
  const terminal = g.terminalCommitment, evidenceRoot = pin.keyDescriptors.find(item => item.role === "authority-cell" && item.purpose === "authority-evidence"), { terminalCommitment: _terminal, ...content } = g, { signature: terminalSignature, ...terminalBody } = terminal;
  const counts = { grants: g.grants.length, principals: g.principals.length, allocations: g.allocations.length, budgetEvents: g.budgetEvents.length, outcomes: g.outcomes.length, exceptions: g.exceptions.length, receipts: g.receipts.length, priorReceiptLinks: g.priorReceiptLinks.length };
  if (!evidenceRoot || terminal.signerId !== evidenceRoot.keyId || terminal.rootGrantDigest !== g.rootGrant.digest || terminal.contentDigest !== authorityDigest(content) || authorityDigest(terminal.counts) !== authorityDigest(counts) || !verifyAuthoritySignature(createPublicKey({ key: Buffer.from(evidenceRoot.publicKeySpkiBase64, "base64"), format: "der", type: "spki" }), "authority-evidence", authorityDigest(terminalBody), terminalSignature)) throw new TypeError("receipt graph signed terminal commitment is invalid");
  if (g.binding.taskId !== g.taskId || g.binding.authorityCellId !== g.authorityCellId || authorityDigest(g.rootGrant.grant) !== g.rootGrant.digest || g.rootGrant.grant.parentDigest !== null || g.grants.length !== 1 || g.grants[0].digest !== g.rootGrant.digest) throw new TypeError("receipt graph grant lineage is broken");
  if (g.allocations.length !== 1 || g.allocations[0].taskId !== g.taskId || g.allocations[0].effects !== g.allocations[0].consumed + g.allocations[0].remaining) throw new TypeError("receipt graph budget is imbalanced");
  const direct = pin.keyDescriptors.filter((item: any) => item.role === "authority-cell").map((item: any) => ({ tenant: g.authorityCellId, signerId: item.keyId, principalId: item.purpose === "delegation-grant" ? g.rootGrant.grant.grantor : g.rootGrant.grant.grantee, publicKey: createPublicKey({ key: Buffer.from(item.publicKeySpkiBase64, "base64"), format: "der", type: "spki" }), purposes: [item.purpose] }));
  const delegated = g.binding.entries.map((item: any) => ({ tenant: g.authorityCellId, signerId: item.keyId, principalId: g.rootGrant.grant.grantee, publicKey: createPublicKey({ key: Buffer.from(item.publicKeySpkiBase64, "base64"), format: "der", type: "spki" }), purposes: [item.artifactPurpose] }));
  const requests = new Set(g.receipts.map((bundle: any) => bundle.receipt.value.decisionContext.requestId)); for (const requestId of requests) { let prior: any; const remaining = g.receipts.filter((bundle: any) => bundle.receipt.value.decisionContext.requestId === requestId); while (remaining.length) { const index = remaining.findIndex((bundle: any) => bundle.receipt.value.priorReceiptDigest === (prior ? authorityDigest(prior) : null)); if (index < 0) throw new TypeError("receipt graph chain fork or broken prior link"); const [bundle] = remaining.splice(index, 1); verifyAuthorityReceiptBundle(bundle, { tenant: g.authorityCellId, trustRoots: [...direct, ...delegated], ...(prior ? { priorReceipt: prior } : {}) }); prior = bundle.receipt.value; } }
  const expectedLinks = g.receipts.map((bundle: any) => ({ receiptDigest: authorityDigest(bundle.receipt.value), priorReceiptDigest: bundle.receipt.value.priorReceiptDigest })); if (authorityDigest(expectedLinks) !== authorityDigest(g.priorReceiptLinks)) throw new TypeError("receipt graph prior links mismatch");
  return Object.freeze({ status: "verified", digest: authorityDigest(g) });
}
function containsConfidential(value: unknown): boolean { if (!value || typeof value !== "object") return typeof value === "string" && /canary-private-token/i.test(value); for (const [key, child] of Object.entries(value as Record<string, unknown>)) { if (/^(bearerToken|credential|credentials|privateKey|secretToken|token)$/i.test(key) || containsConfidential(child)) return true; } return false; }
