import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { StaticPackCompileInput, StaticPackDefinition } from "../../authority/pack.js";
import { informationFlowCommitAlias, informationFlowDefinitionDigest, informationFlowPackDigest, informationFlowPolicySchemaId, informationFlowProjectionSchemaId, informationFlowReadEndpointId, informationFlowRecipeId, informationFlowResolverId, informationFlowRiskClass, informationFlowWriteEndpointId } from "./manifest.js";
import type { InformationFlowField, InformationFlowProjection } from "./manifest.js";
export interface InformationFlowPolicy { readonly hubspotAccountId: string; readonly slackTeamId: string; readonly slackChannelId: string; readonly authorizedFields: readonly InformationFlowField[]; readonly transformation: "selected_fields_only"; readonly stagedText: string; }
const ALLOWED_FIELDS: readonly InformationFlowField[] = ["priority", "status", "subject", "ticketId"];
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Information-flow ${label} is invalid`); return value; }
function fields(value: unknown): readonly InformationFlowField[] { if (!Array.isArray(value) || value.length === 0 || value.length > ALLOWED_FIELDS.length || value.some(item => !ALLOWED_FIELDS.includes(item as InformationFlowField))) throw new TypeError("Information-flow authorizedFields are invalid"); const result = [...value] as InformationFlowField[]; if (new Set(result).size !== result.length) throw new TypeError("Information-flow authorizedFields must be unique"); return Object.freeze(result.sort(compareText)); }
function stagedText(value: unknown): string { if (typeof value !== "string" || value.length === 0 || Buffer.byteLength(value, "utf8") > 64 * 1024 || /[\0\r\n]/.test(value)) throw new TypeError("Information-flow stagedText must be bounded plain text"); return value; }
export function validateInformationFlowChoices(value: unknown): Record<string, never> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 0) throw new TypeError("Information-flow choices must be empty"); return Object.freeze({}); }
export function parseInformationFlowPolicy(value: unknown): InformationFlowPolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Information-flow policy must be an object"); const raw = value as Record<string, unknown>; const keys = ["hubspotAccountId", "slackTeamId", "slackChannelId", "authorizedFields", "transformation", "stagedText"]; if (Object.keys(raw).length !== keys.length || Object.keys(raw).some(key => !keys.includes(key))) throw new TypeError("Information-flow policy is closed"); if (raw.transformation !== "selected_fields_only") throw new TypeError("Information-flow transformation is unsupported"); return Object.freeze({ hubspotAccountId: id(raw.hubspotAccountId, "HubSpot account"), slackTeamId: id(raw.slackTeamId, "Slack team"), slackChannelId: id(raw.slackChannelId, "Slack channel"), authorizedFields: fields(raw.authorizedFields), transformation: "selected_fields_only", stagedText: stagedText(raw.stagedText) }); }
export function compileInformationFlowCommit(input: Readonly<{ source: InformationFlowProjection; policy: InformationFlowPolicy }>): Readonly<{ v: "reelier.transport-effect/v1"; endpointId: string; method: "POST"; path: string; query: string; headers: Record<string, string>; bodyBase64: string; riskClass: string; idempotency: "reconcile-only"; preconditions: { kind: string; digest: string }[]; reconciliation: { recipeId: string } }> { const { source, policy } = input; if (source.hubspotAccountId !== policy.hubspotAccountId) throw new TypeError("Information-flow source account is outside the signed policy"); const selected = Object.fromEntries(policy.authorizedFields.map(field => [field, source[field]])); const body = authorityCanonicalBytes({ channel: policy.slackChannelId, text: policy.stagedText }); return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: informationFlowWriteEndpointId, method: "POST", path: "/api/chat.postMessage", query: "", headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: informationFlowRiskClass, idempotency: "reconcile-only", preconditions: [{ kind: "hubspot-authorized-field-projection", digest: authorityDigest({ v: "reelier.information-flow-fields/v1", accountId: source.hubspotAccountId, ticketId: source.ticketId, fields: selected }) }, { kind: "slack-private-destination", digest: authorityDigest({ v: "reelier.slack-destination/v1", teamId: policy.slackTeamId, channelId: policy.slackChannelId }) }], reconciliation: { recipeId: informationFlowRecipeId } }); }
export const informationFlowDefinition: StaticPackDefinition = Object.freeze({ alias: informationFlowCommitAlias, packDigest: informationFlowPackDigest, definitionDigest: informationFlowDefinitionDigest, resolverId: informationFlowResolverId, projectionSchemaId: informationFlowProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [informationFlowReadEndpointId], writeEndpointIds: [informationFlowWriteEndpointId], riskClasses: [informationFlowRiskClass], policySchemaId: informationFlowPolicySchemaId, requiredGroundedPointers: ["/hubspotAccountId", "/ticketId", "/contactId", "/customerEmail", "/subject", "/status", "/priority"], validateChoices: validateInformationFlowChoices, parsePolicy: parseInformationFlowPolicy, compile: (input: StaticPackCompileInput) => compileInformationFlowCommit({ source: input.source.projection as InformationFlowProjection, policy: input.policy as InformationFlowPolicy }) });
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
