import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import { authorityDigest } from "../../authority/wire.js";
import { informationFlowDefinitionDigest, informationFlowProjectionSchemaId, informationFlowReadEndpointId, informationFlowResolverId } from "./manifest.js";
import type { InformationFlowProjection } from "./manifest.js";
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("HubSpot ticket response must be an object"); return value as Record<string, unknown>; }
function text(value: unknown, label: string, max = 256): string { if (typeof value !== "string" || value.length === 0 || value.length > max || /[\0\r\n]/.test(value)) throw new TypeError(`HubSpot ${label} is invalid`); return value; }
function id(value: unknown, label: string): string { return text(value, label).match(/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/) ? value as string : (() => { throw new TypeError(`HubSpot ${label} is invalid`); })(); }
function normalize(rawBytes: Uint8Array): InformationFlowProjection { let parsed: unknown; try { parsed = JSON.parse(Buffer.from(rawBytes).toString("utf8")); } catch { throw new TypeError("HubSpot ticket response is not JSON"); } const root = object(parsed); const properties = root.properties && typeof root.properties === "object" && !Array.isArray(root.properties) ? object(root.properties) : root; return Object.freeze({ hubspotAccountId: id(root.hubspotAccountId ?? root.accountId, "accountId"), ticketId: id(root.ticketId ?? root.id, "ticketId"), contactId: id(root.contactId, "contactId"), customerEmail: text(root.customerEmail, "customerEmail", 320).toLowerCase(), subject: text(properties.subject ?? root.subject, "subject"), status: text(properties.status ?? root.status, "status"), priority: text(properties.priority ?? root.priority, "priority") }); }
export function createInformationFlowSourceResolver(tenant: string = "*"): RegisteredSourceResolver { return Object.freeze({ tenant, resolverId: informationFlowResolverId, definitionDigest: informationFlowDefinitionDigest, projectionSchemaId: informationFlowProjectionSchemaId, readEndpointIds: [informationFlowReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: informationFlowReadEndpointId, opaqueHandle: refs.ticket }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>) => { if (input.observations.length !== 1) throw new TypeError("HubSpot ticket source requires one observation"); const projection = normalize(Buffer.from(input.observations[0].bodyBase64, "base64")); const sourceIdentity = `hubspot.ticket.${projection.hubspotAccountId}.${projection.ticketId}`; const triggerIdentity = authorityDigest({ v: "reelier.hubspot-ticket-trigger/v1", sourceIdentity, status: projection.status, priority: projection.priority }).replace(":", "."); const claims = Object.keys(projection).map(key => ({ claimId: `hubspot-${key}`, projectionPointer: `/${key}` })); return Object.freeze({ sourceIdentity, triggerIdentity, projection, claims: Object.freeze({ grounded: Object.freeze(claims), authored: Object.freeze([]), unresolved: Object.freeze([]) }) }) satisfies SourceProjection; } }); }
