import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync, randomUUID, sign } from "node:crypto";
import { mkdir, open, readFile, realpath, rename, rm, stat } from "node:fs/promises";
import path from "node:path";
import canonicalize from "canonicalize";
import { createManagedUpgradeIntentV1, type ReviewedConsequentialOperationV1 } from "./managed-upgrade-intent.js";

export type ManagedUpgradeTargetManifestV1 = Readonly<{ version: "reelier.managed-upgrade-target-manifest/v1"; missionRef: string; repository: string; githubActions: readonly ReviewedConsequentialOperationV1[]; linearTarget: string; linearActions: readonly ReviewedConsequentialOperationV1[]; maximumWrites: number; expiresAt: string }>;
type FetchLike = (url: string, init?: RequestInit) => Promise<Response>;
const DIGEST = /^sha256:[0-9a-f]{64}$/u, ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$/u, REPO = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/u;
const OPERATIONS = new Set<ReviewedConsequentialOperationV1>(["github_release_candidate_publish_v1", "github_release_pr_ensure_v1", "github_release_pr_merge_v1", "linear_evidence_comment_v1", "linear_status_transition_v1", "linear_only_evidence_comment_v1", "linear_only_status_transition_v1"]);
const sha = (value: string | Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`;

function exactManifest(value: ManagedUpgradeTargetManifestV1): ManagedUpgradeTargetManifestV1 { if (!value || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype || Object.keys(value).sort().join(",") !== ["version", "missionRef", "repository", "githubActions", "linearTarget", "linearActions", "maximumWrites", "expiresAt"].sort().join(",")) throw new TypeError("Autopilot target manifest shape is invalid"); if (value.version !== "reelier.managed-upgrade-target-manifest/v1" || !ID.test(value.missionRef) || !REPO.test(value.repository) || typeof value.linearTarget !== "string" || value.linearTarget.length < 1 || value.linearTarget.length > 256 || !Number.isSafeInteger(value.maximumWrites) || value.maximumWrites < 1 || value.maximumWrites > 100 || Number.isNaN(Date.parse(value.expiresAt))) throw new TypeError("Autopilot target manifest is invalid"); for (const list of [value.githubActions, value.linearActions]) if (!Array.isArray(list) || list.length === 0 || list.length > 7 || list.some(item => !OPERATIONS.has(item)) || new Set(list).size !== list.length) throw new TypeError("Autopilot target operations are invalid"); return Object.freeze({ ...value, githubActions: Object.freeze([...value.githubActions]), linearActions: Object.freeze([...value.linearActions]) }); }

async function localSigningKey(root: string) { const resolved = path.resolve(root), canonical = await realpath(resolved); if (resolved !== canonical || !(await stat(canonical)).isDirectory()) throw new TypeError("Autopilot workspace root is linked or invalid"); const directory = path.join(canonical, ".reelier", "operator", "keys"); await mkdir(directory, { recursive: true, mode: 0o700 }); if (await realpath(directory) !== path.resolve(directory)) throw new TypeError("Autopilot key directory is linked"); const target = path.join(directory, "autopilot-ed25519.pem"); let privatePem: string; try { privatePem = await readFile(target, "utf8"); } catch (error: unknown) { if ((error as { code?: string }).code !== "ENOENT") throw error; const pair = generateKeyPairSync("ed25519"); privatePem = pair.privateKey.export({ type: "pkcs8", format: "pem" }).toString(); const handle = await open(target, "wx", 0o600); try { await handle.writeFile(privatePem, "utf8"); await handle.sync(); } finally { await handle.close(); } } const privateKey = createPrivateKey(privatePem); if (privateKey.asymmetricKeyType !== "ed25519") throw new TypeError("Autopilot signing key is invalid"); const publicKey = createPublicKey(privateKey), publicKeyPem = publicKey.export({ type: "spki", format: "pem" }).toString(); return { privateKey, publicKeyPem, returnChannelRef: sha(publicKey.export({ type: "spki", format: "der" })) }; }

export async function createAutopilotHandoffV1(input: Readonly<{ root: string; cloudBaseUrl: string; missionRef: string; localEvidenceRefs: readonly string[]; targetManifest: ManagedUpgradeTargetManifestV1; now?: () => Date; fetch?: FetchLike }>) {
  const base = new URL(input.cloudBaseUrl); if (base.protocol !== "https:" || base.username || base.password) throw new TypeError("Autopilot Cloud URL is invalid"); const target = exactManifest(input.targetManifest); if (target.missionRef !== input.missionRef) throw new TypeError("Autopilot mission binding mismatch"); if (!Array.isArray(input.localEvidenceRefs) || input.localEvidenceRefs.some(ref => !DIGEST.test(ref))) throw new TypeError("Autopilot local evidence is invalid"); const now = (input.now ?? (() => new Date()))(); if (Date.parse(target.expiresAt) <= now.getTime() || Date.parse(target.expiresAt) - now.getTime() > 900_000) throw new TypeError("Autopilot target expiry is invalid"); const keys = await localSigningKey(input.root), requestedOperations = Object.freeze([...target.githubActions, ...target.linearActions]); const targetBytes = canonicalize(target); if (!targetBytes) throw new TypeError("Autopilot target is not canonicalizable"); const intent = createManagedUpgradeIntentV1({ missionRef: input.missionRef, localEvidenceDigest: sha(canonicalize([...input.localEvidenceRefs].sort()) ?? "[]"), requestedOperations, targetSummaryDigest: sha(targetBytes), returnChannelRef: keys.returnChannelRef, issuedAt: now.toISOString(), expiresAt: target.expiresAt, nonce: createHash("sha256").update(`${input.missionRef}\0${now.toISOString()}\0${randomUUID()}`).digest("hex"), sign: digest => sign(null, Buffer.from(digest, "utf8"), keys.privateKey).toString("base64url") }); const response = await (input.fetch ?? fetch)(new URL("/api/v1/autopilot/handoffs", base).toString(), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ intent, targetManifest: target, publicKeyPem: keys.publicKeyPem }) }); if (!response.ok) throw new Error(`Autopilot handoff refused (${response.status})`); const result: unknown = await response.json(); if (!result || typeof result !== "object" || Array.isArray(result) || Object.keys(result).sort().join(",") !== "browserPath,pollSecret" || typeof (result as { browserPath?: unknown }).browserPath !== "string" || typeof (result as { pollSecret?: unknown }).pollSecret !== "string" || !/^\/autopilot\?mission=[A-Za-z0-9._:%-]+#init=[A-Za-z0-9_-]{32,256}$/u.test((result as { browserPath: string }).browserPath) || !/^[A-Za-z0-9_-]{32,256}$/u.test((result as { pollSecret: string }).pollSecret)) throw new TypeError("Autopilot handoff response is invalid");
  const handoffDirectory = path.join(path.resolve(input.root), ".reelier", "operator", "handoffs"); await mkdir(handoffDirectory, { recursive: true, mode: 0o700 }); if (await realpath(handoffDirectory) !== path.resolve(handoffDirectory)) throw new TypeError("Autopilot handoff directory is linked"); const handoffPath = path.join(handoffDirectory, `${input.missionRef}.json`), temporary = `${handoffPath}.${process.pid}.${randomUUID()}.tmp`; const pollSecret = (result as { pollSecret: string }).pollSecret; try { const handle = await open(temporary, "wx", 0o600); try { await handle.writeFile(`${JSON.stringify({ version: "reelier.autopilot-poll/v1", missionRef: input.missionRef, cloudBaseUrl: base.toString(), pollSecret, createdAt: now.toISOString() })}\n`, "utf8"); await handle.sync(); } finally { await handle.close(); } await rename(temporary, handoffPath); } finally { await rm(temporary, { force: true }); }
  return Object.freeze({ browserUrl: new URL((result as { browserPath: string }).browserPath, base).toString(), pollSecret, intent });
}
