// `reelier ci` — writes `.github/workflows/reelier-replay.yml` so a repo
// gets drift-CI (replay every skill on every PR, plus a daily schedule) and
// the sticky PR receipt comment (action.yml's `pr-comment` input) in one
// command. This module is pure discovery + rendering — no console output,
// no process.exit — so it's unit-testable directly; src/cli.ts's cmdCi
// does the argv parsing and printing.

import { readdir, readFile, mkdir, access } from "node:fs/promises";
import path from "node:path";
import { writeFileAtomic } from "./writeback.js";

/** Depth-capped recursive walk, same shape as scan.ts's findTranscriptFiles — a symlink loop or an unrelated huge tree (node_modules) must never hang the scan. */
const MAX_DEPTH = 3;
const SKIP_DIRS = new Set(["node_modules", ".git"]);

/**
 * Every `*.skill.md` file under `rootDir`, found by a depth-capped recursive
 * walk (node_modules/.git excluded). Returns POSIX-style paths relative to
 * `rootDir` (forward slashes always, even on Windows — these are written
 * verbatim into a YAML file GitHub Actions runs on Linux runners), sorted
 * for a stable, diffable workflow file across re-runs. A missing/unreadable
 * directory yields an empty list rather than throwing.
 */
export async function discoverSkillFiles(rootDir: string): Promise<string[]> {
  const out: string[] = [];

  async function walk(dir: string, depth: number): Promise<void> {
    if (depth > MAX_DEPTH) return;
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        await walk(path.join(dir, entry.name), depth + 1);
      } else if (entry.isFile() && entry.name.endsWith(".skill.md")) {
        const rel = path.relative(rootDir, path.join(dir, entry.name)).split(path.sep).join("/");
        out.push(rel);
      }
    }
  }

  await walk(rootDir, 0);
  return out.sort();
}

/** The clearly-marked placeholder used when discovery finds zero skills — never a silently-invented real-looking path (see cmdCi's accompanying stderr message). */
export const PLACEHOLDER_SKILL_PATH = "REPLACE-ME/your-skill.skill.md";

/**
 * Render `.github/workflows/reelier-replay.yml`. `skillPaths` empty means
 * "no skills discovered" — the workflow still gets written (so the user has
 * something to edit and commit) but with the placeholder path plus a
 * comment telling them to record one first, never a fabricated real-looking
 * path.
 */
export function renderCiWorkflow(skillPaths: string[]): string {
  const skills = skillPaths.length > 0 ? skillPaths : [PLACEHOLDER_SKILL_PATH];
  const placeholderNote =
    skillPaths.length === 0
      ? [
          "# No *.skill.md files were found in this repo yet — the path below is a",
          "# placeholder. Record one first (`reelier init`), then replace `skill:` with",
          "# its real path (see the matrix below).",
        ].join("\n") + "\n"
      : "";

  const matrixLines = skills.map((s) => `          - "${s}"`).join("\n");

  return `# Generated by \`reelier ci\` — drift-CI + PR receipts in one workflow.
# Re-run \`reelier ci --force\` to regenerate after adding/removing skills.
${placeholderNote}
name: Reelier replay

on:
  pull_request: {}
  schedule:
    # Daily at 07:23 UTC — off-peak minute, avoids the top-of-hour scheduled-job stampede.
    - cron: "23 7 * * *"
  workflow_dispatch: {} # manual "Run workflow" button in the Actions tab

permissions:
  contents: read # actions/checkout@v4's own minimum requirement
  # Lets the action upsert its sticky PR receipt comment on pull_request runs.
  # Omit this (or drop it to read) and the action just logs "no
  # pull-requests: write permission" and skips the comment — the replay
  # itself still passes/fails exactly the same either way.
  pull-requests: write
  # Lets \`reelier push\` request GitHub's own OIDC token and attach it as a
  # CI attestation (trust-ladder spec §5) — only used if you enable the push
  # block below. Omit this (or drop it to read) and a push simply carries no
  # ciAttestation — never a failure, never required for the replay to pass.
  id-token: write

jobs:
  replay:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        skill:
${matrixLines}
    steps:
      - uses: actions/checkout@v4

      - name: Replay skill
        uses: seldonframe/reelier@v1
        with:
          skill: \${{ matrix.skill }}
          max-level: "0" # 0 tokens — pure deterministic replay.

          # Optional: sync this run's receipt to your ledger after a passing
          # replay (see README.md "Push"). Uncomment and add the
          # REELIER_API_KEY secret in this repo's Settings > Secrets first.
          # cloud-key: \${{ secrets.REELIER_API_KEY }}
`;
}

/** Absolute path this repo's `reelier ci` writes to — always under the current working directory's `.github/workflows/`, regardless of `--path` (which only overrides the skill-discovery root). */
export function ciWorkflowPath(cwd: string): string {
  return path.join(cwd, ".github", "workflows", "reelier-replay.yml");
}

export async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

export interface WriteCiWorkflowResult {
  path: string;
  skillPaths: string[];
  wrote: boolean;
  /** True iff the file already existed and `--force` wasn't passed — nothing was written. */
  refused: boolean;
}

/**
 * Discover skills under `scanRoot` and write the workflow to
 * `<cwd>/.github/workflows/reelier-replay.yml`. Refuses to overwrite an
 * existing file unless `force` is true — the caller (cmdCi) reports the
 * refusal; this function never throws for that case, it just reports
 * `refused: true` so cmdCi can decide the exit code and message.
 */
export async function writeCiWorkflow(cwd: string, scanRoot: string, force: boolean): Promise<WriteCiWorkflowResult> {
  const outPath = ciWorkflowPath(cwd);
  if (!force && (await fileExists(outPath))) {
    return { path: outPath, skillPaths: [], wrote: false, refused: true };
  }

  const skillPaths = await discoverSkillFiles(scanRoot);
  const rendered = renderCiWorkflow(skillPaths);

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFileAtomic(outPath, rendered);

  return { path: outPath, skillPaths, wrote: true, refused: false };
}

// Re-exported only so tests can sanity-check the file is readable JSON-free
// YAML text without pulling in a YAML parser dependency (none exists in this
// package — see package.json).
export async function readWrittenWorkflow(p: string): Promise<string> {
  return readFile(p, "utf8");
}
