import type { Effect } from "./skill.js";

/**
 * Tool-name tokens recognized by the compiler's effect classifier.
 *
 * Keep additions conservative: destructive tokens take precedence over
 * idempotent writes, which take precedence over reads.
 */
export const EFFECT_VERBS = {
  read: [
    "get",
    "list",
    "read",
    "search",
    "fetch",
    "query",
    "describe",
    "find",
    "check",
    "status",
    "show",
    "view",
    "lookup",
    "inspect",
  ],
  "idempotent-write": [
    "create",
    "update",
    "set",
    "upsert",
    "put",
    "write",
    "save",
    "add",
    "modify",
    "move",
    "insert",
    "label",
  ],
  destructive: [
    "delete",
    "remove",
    "cancel",
    "refund",
    "pay",
    "send",
    "publish",
    "post",
    "charge",
    "drop",
    "destroy",
    "purge",
    "wipe",
    "forward",
    "reply",
    "execute",
    "run",
    "transfer",
    "approve",
    "revoke",
    "terminate",
    "kill",
    "grant",
    "deploy",
    "merge",
    "submit",
    "trash",
    "expire",
    "disable",
    "deactivate",
    "suspend",
    "reset",
    "overwrite",
    "replace",
    "truncate",
  ],
} as const satisfies Record<Effect, readonly string[]>;
