/** Generated by scripts/build-bootstrap-contract.mjs. */
import canonicalize from "canonicalize";
import { createHash } from "node:crypto";
import { assertOwnDataTree } from "./normalize.js";

export interface BootstrapContractV1 {
  readonly v: "reelier.bootstrap-contract/v1";
  readonly domain: "reelier.bootstrap-contract/v1\\0";
  readonly members: readonly Readonly<{ path: string; digest: string }>[];
  readonly digest: string;
}

const generatedContract: BootstrapContractV1 = {
  "v": "reelier.bootstrap-contract/v1",
  "domain": "reelier.bootstrap-contract/v1\\0",
  "members": [
    {
      "path": "agent-project.schema.json",
      "digest": "sha256:cdf8092df8c1d56be63fefb18722302376a967d3e9fc1a10a74d81ef6e28dd9c"
    },
    {
      "path": "authority-cell-session-binding.schema.json",
      "digest": "sha256:ba74a8325d870b8d805a3e50e8dd2b4bbb26d7aee2f286b637697dff35834079"
    },
    {
      "path": "bootstrap-report.schema.json",
      "digest": "sha256:f24ca25ef9e374b002bc32f890cf7ad09f2f515fab8ceff447ea91c2712c47b2"
    },
    {
      "path": "route-coverage.schema.json",
      "digest": "sha256:2aff854dbc8984b313d7ef1e0fd6e566eb52c88a455c0543863433bb3ac716c3"
    },
    {
      "path": "runtime-descriptor.schema.json",
      "digest": "sha256:e533b0e13dcec9ec02ce334f48a594274761e7b567cfa5579daeb43a93467600"
    },
    {
      "path": "supervisor-status.schema.json",
      "digest": "sha256:619ac0abee08e7997df3fd2df54082e149e421cc90394e94603e72db43b8dac2"
    }
  ],
  "digest": "sha256:3b161491c1a8c0edb69e58b5d6c97713aa481778c30843127360e5188ebb20b6"
};
export const BOOTSTRAP_CONTRACT_V1: BootstrapContractV1 = freezeContract(generatedContract);
export const BOOTSTRAP_CONTRACT_V1_DIGEST = BOOTSTRAP_CONTRACT_V1.digest;

export function verifyBootstrapContractV1(value: unknown, files: ReadonlyMap<string, Uint8Array>): BootstrapContractV1 {
  assertOwnDataTree(value, "bootstrap contract descriptor");
  if (!value || typeof value !== "object") throw new TypeError("invalid bootstrap contract descriptor");
  const descriptor = value as { v?: unknown; domain?: unknown; members?: unknown; digest?: unknown };
  if (descriptor.v !== "reelier.bootstrap-contract/v1" || descriptor.domain !== "reelier.bootstrap-contract/v1\\0" || !Array.isArray(descriptor.members) || typeof descriptor.digest !== "string") throw new TypeError("invalid bootstrap contract shape");
  const members = descriptor.members.map(member => {
    if (!member || typeof member !== "object" || typeof (member as { path?: unknown }).path !== "string" || typeof (member as { digest?: unknown }).digest !== "string") throw new TypeError("invalid bootstrap contract member");
    return member as { path: string; digest: string };
  });
  const paths = members.map(member => member.path);
  if (paths.join("\0") !== [...paths].sort().join("\0") || new Set(paths).size !== paths.length || paths.join("\0") !== BOOTSTRAP_CONTRACT_V1.members.map(member => member.path).join("\0")) throw new TypeError("invalid bootstrap contract membership");
  for (const member of members) {
    const bytes = files.get(member.path);
    if (!bytes || `sha256:${createHash("sha256").update(normalizeBytes(bytes)).digest("hex")}` !== member.digest) throw new TypeError(`invalid bootstrap contract member digest: ${member.path}`);
  }
  const unsigned = { v: descriptor.v, domain: descriptor.domain, members: members.map(member => ({ path: member.path, digest: member.digest })) };
  const canonical = canonicalize(unsigned);
  if (canonical === undefined) throw new TypeError("invalid bootstrap contract canonical form");
  const expected = `sha256:${createHash("sha256").update(canonical, "utf8").digest("hex")}`;
  if (descriptor.digest !== expected || /^sha256:0{64}$/.test(descriptor.digest)) throw new TypeError("invalid bootstrap contract aggregate digest");
  return freezeContract({ ...unsigned, digest: descriptor.digest } as BootstrapContractV1);
}

function freezeContract(value: BootstrapContractV1): BootstrapContractV1 { return Object.freeze({ ...value, members: Object.freeze(value.members.map(member => Object.freeze({ ...member }))) }); }
function normalizeBytes(bytes: Uint8Array): Buffer { return Buffer.from(Buffer.from(bytes).toString("utf8").replace(/\r\n/g, "\n"), "utf8"); }
