/** Generated by scripts/build-bootstrap-contract.mjs. */
import canonicalize from "canonicalize";
import { createHash } from "node:crypto";
import { assertOwnDataTree } from "./normalize.js";

export interface BootstrapContractV1 {
  readonly v: "reelier.bootstrap-contract/v1";
  readonly domain: "reelier.bootstrap-contract/v1\\0";
  readonly members: readonly Readonly<{ path: string; digest: string }>[];
  readonly digest: string;
}

const generatedContract: BootstrapContractV1 = {
  "v": "reelier.bootstrap-contract/v1",
  "domain": "reelier.bootstrap-contract/v1\\0",
  "members": [
    {
      "path": "agent-project.schema.json",
      "digest": "sha256:cdf8092df8c1d56be63fefb18722302376a967d3e9fc1a10a74d81ef6e28dd9c"
    },
    {
      "path": "authority-cell-session-binding.schema.json",
      "digest": "sha256:ba74a8325d870b8d805a3e50e8dd2b4bbb26d7aee2f286b637697dff35834079"
    },
    {
      "path": "bootstrap-report.schema.json",
      "digest": "sha256:f24ca25ef9e374b002bc32f890cf7ad09f2f515fab8ceff447ea91c2712c47b2"
    },
    {
      "path": "route-coverage.schema.json",
      "digest": "sha256:777c3b4f9f34ca3b3924536bddb0b44ccd995958b51e01773a4a930f90c33cbf"
    },
    {
      "path": "runtime-descriptor.schema.json",
      "digest": "sha256:086701c02d45986c5c5ee9e2c0e57e1c01536bd4baaa0d6dd336bcde7ca9dcd8"
    },
    {
      "path": "supervisor-status.schema.json",
      "digest": "sha256:be84bfcb0ce711402ccd427c06556c81c28a1708fccb2a311d81fa6da2956afc"
    }
  ],
  "digest": "sha256:8be3d4307c6cc265a3d1b6702b71f0ff4d09687a72e3813c5fb3df36abb9fb24"
};
export const BOOTSTRAP_CONTRACT_V1: BootstrapContractV1 = freezeContract(generatedContract);
export const BOOTSTRAP_CONTRACT_V1_DIGEST = BOOTSTRAP_CONTRACT_V1.digest;

export function verifyBootstrapContractV1(value: unknown, files: ReadonlyMap<string, Uint8Array>): BootstrapContractV1 {
  assertOwnDataTree(value, "bootstrap contract descriptor");
  if (!value || typeof value !== "object") throw new TypeError("invalid bootstrap contract descriptor");
  const descriptor = value as { v?: unknown; domain?: unknown; members?: unknown; digest?: unknown };
  if (descriptor.v !== "reelier.bootstrap-contract/v1" || descriptor.domain !== "reelier.bootstrap-contract/v1\\0" || !Array.isArray(descriptor.members) || typeof descriptor.digest !== "string") throw new TypeError("invalid bootstrap contract shape");
  const members = descriptor.members.map(member => {
    if (!member || typeof member !== "object" || typeof (member as { path?: unknown }).path !== "string" || typeof (member as { digest?: unknown }).digest !== "string") throw new TypeError("invalid bootstrap contract member");
    return member as { path: string; digest: string };
  });
  const paths = members.map(member => member.path);
  if (paths.join("\0") !== [...paths].sort().join("\0") || new Set(paths).size !== paths.length || paths.join("\0") !== BOOTSTRAP_CONTRACT_V1.members.map(member => member.path).join("\0")) throw new TypeError("invalid bootstrap contract membership");
  for (const member of members) {
    const bytes = files.get(member.path);
    if (!bytes || `sha256:${createHash("sha256").update(normalizeBytes(bytes)).digest("hex")}` !== member.digest) throw new TypeError(`invalid bootstrap contract member digest: ${member.path}`);
  }
  const unsigned = { v: descriptor.v, domain: descriptor.domain, members: members.map(member => ({ path: member.path, digest: member.digest })) };
  const canonical = canonicalize(unsigned);
  if (canonical === undefined) throw new TypeError("invalid bootstrap contract canonical form");
  const expected = `sha256:${createHash("sha256").update(canonical, "utf8").digest("hex")}`;
  if (descriptor.digest !== expected || /^sha256:0{64}$/.test(descriptor.digest)) throw new TypeError("invalid bootstrap contract aggregate digest");
  return freezeContract({ ...unsigned, digest: descriptor.digest } as BootstrapContractV1);
}

function freezeContract(value: BootstrapContractV1): BootstrapContractV1 { return Object.freeze({ ...value, members: Object.freeze(value.members.map(member => Object.freeze({ ...member }))) }); }
function normalizeBytes(bytes: Uint8Array): Buffer { return Buffer.from(Buffer.from(bytes).toString("utf8").replace(/\r\n/g, "\n"), "utf8"); }
