import { authorityCanonicalBytes, authorityDigest } from "../../authority/wire.js";
import type { StaticPackCompileInput, StaticPackDefinition } from "../../authority/pack.js";
import { cloudflareTokenRollAlias, cloudflareTokenRollDefinitionDigest, cloudflareTokenRollPackDigest, cloudflareTokenRollPolicySchemaId, cloudflareTokenRollProjectionSchemaId, cloudflareTokenRollReadEndpointId, cloudflareTokenRollRecipeId, cloudflareTokenRollResolverId, cloudflareTokenRollRiskClass, cloudflareTokenRollWriteEndpointId } from "./manifest.js";
import type { CloudflareTokenProjection } from "./manifest.js";
export interface CloudflareTokenRollPolicy { readonly accountId: string; readonly tokenId: string; readonly tokenName: string; readonly scopes: readonly string[]; readonly resources: readonly string[]; readonly expiresAt: string; }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Cloudflare token ${label} is invalid`); return value; }
function list(value: unknown, label: string): readonly string[] { if (!Array.isArray(value) || value.length === 0 || value.length > 128 || value.some(item => typeof item !== "string" || item.length === 0 || item.length > 256)) throw new TypeError(`Cloudflare token ${label} is invalid`); const result = [...value] as string[]; if (new Set(result).size !== result.length) throw new TypeError(`Cloudflare token ${label} must be unique`); return Object.freeze(result.sort(compareText)); }
function expires(value: unknown): string { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) || !Number.isFinite(Date.parse(value))) throw new TypeError("Cloudflare token expiry is invalid"); return value; }
export function validateCloudflareTokenRollChoices(value: unknown): Record<string, never> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value as object).length !== 0) throw new TypeError("Cloudflare token choices must be empty"); return Object.freeze({}); }
export function parseCloudflareTokenRollPolicy(value: unknown): CloudflareTokenRollPolicy { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Cloudflare token policy must be an object"); const raw = value as Record<string, unknown>; const keys = ["accountId", "tokenId", "tokenName", "scopes", "resources", "expiresAt"]; if (Object.keys(raw).length !== keys.length || Object.keys(raw).some(key => !keys.includes(key))) throw new TypeError("Cloudflare token policy is closed"); return Object.freeze({ accountId: id(raw.accountId, "accountId"), tokenId: id(raw.tokenId, "tokenId"), tokenName: id(raw.tokenName, "tokenName"), scopes: list(raw.scopes, "scopes"), resources: list(raw.resources, "resources"), expiresAt: expires(raw.expiresAt) }); }
export function compileCloudflareTokenRoll(input: Readonly<{ source: CloudflareTokenProjection; policy: CloudflareTokenRollPolicy }>): Readonly<{ v: "reelier.transport-effect/v1"; endpointId: string; method: "POST"; path: string; query: string; headers: Record<string, string>; bodyBase64: string; riskClass: string; idempotency: "native"; preconditions: { kind: string; digest: string }[]; reconciliation: { recipeId: string } }> { const { source, policy } = input; if (source.accountId !== policy.accountId || source.tokenId !== policy.tokenId) throw new TypeError("Cloudflare token identity is outside the signed policy"); if (source.tokenName !== policy.tokenName || !subset(policy.scopes, source.scopes) || !subset(policy.resources, source.resources)) throw new TypeError("Cloudflare token scope or resource widening requires a new human signature"); if (source.status !== "active") throw new TypeError("Cloudflare token is not active"); if (source.expiresAt === policy.expiresAt) throw new TypeError("Cloudflare token already has the desired expiry"); const body = authorityCanonicalBytes({ name: policy.tokenName, scopes: policy.scopes, resources: policy.resources, expiresAt: policy.expiresAt }); return Object.freeze({ v: "reelier.transport-effect/v1", endpointId: cloudflareTokenRollWriteEndpointId, method: "POST", path: `/client/v4/accounts/${source.accountId}/tokens/${source.tokenId}/roll`, query: "", headers: { "Content-Type": "application/json" }, bodyBase64: body.toString("base64"), riskClass: cloudflareTokenRollRiskClass, idempotency: "native", preconditions: [{ kind: "cloudflare-token-metadata", digest: authorityDigest({ v: "reelier.cloudflare-token-metadata/v1", accountId: source.accountId, tokenId: source.tokenId, tokenName: source.tokenName, scopes: source.scopes, resources: source.resources, expiresAt: source.expiresAt, status: source.status }) }], reconciliation: { recipeId: cloudflareTokenRollRecipeId } }); }
export const cloudflareTokenRollDefinition: StaticPackDefinition = Object.freeze({ alias: cloudflareTokenRollAlias, packDigest: cloudflareTokenRollPackDigest, definitionDigest: cloudflareTokenRollDefinitionDigest, resolverId: cloudflareTokenRollResolverId, projectionSchemaId: cloudflareTokenRollProjectionSchemaId, maxFreshnessSeconds: 60, readEndpointIds: [cloudflareTokenRollReadEndpointId], writeEndpointIds: [cloudflareTokenRollWriteEndpointId], riskClasses: [cloudflareTokenRollRiskClass], policySchemaId: cloudflareTokenRollPolicySchemaId, requiredGroundedPointers: ["/accountId", "/tokenId", "/tokenName", "/scopes", "/resources", "/expiresAt", "/status"], validateChoices: validateCloudflareTokenRollChoices, parsePolicy: parseCloudflareTokenRollPolicy, compile: (input: StaticPackCompileInput) => compileCloudflareTokenRoll({ source: input.source.projection as CloudflareTokenProjection, policy: input.policy as CloudflareTokenRollPolicy }) });
function same(left: readonly string[], right: readonly string[]): boolean { return left.length === right.length && left.every((value, index) => value === right[index]); }
function subset(candidate: readonly string[], parent: readonly string[]): boolean { const allowed = new Set(parent); return candidate.every(value => allowed.has(value)); }
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
