import { authorityDigest } from "../../authority/wire.js";
import type { PackReconciliationResult, ProviderResponse } from "../types.js";
import type { CloudflareTokenRollPolicy } from "./compile.js";
import type { CloudflareTokenProjection } from "./manifest.js";
import { cloudflareTokenRollRecipeId } from "./manifest.js";
export function reconcileCloudflareTokenRoll(input: Readonly<{ expected: CloudflareTokenProjection; policy: CloudflareTokenRollPolicy; response: ProviderResponse | unknown }>): PackReconciliationResult { const response = input.response && typeof input.response === "object" && "body" in input.response ? input.response as ProviderResponse : { body: input.response }; if (response.status === 404) return result("not-applied", "cloudflare-token-not-found", null); if (response.status !== undefined && response.status >= 500) return result("unavailable", "cloudflare-provider-error", null); if (response.status !== undefined && response.status >= 400) return result("unavailable", "cloudflare-provider-refused", null); const root = response.body && typeof response.body === "object" && !Array.isArray(response.body) ? response.body as Record<string, unknown> : {}; const record = root.result && typeof root.result === "object" && !Array.isArray(root.result) ? root.result as Record<string, unknown> : root; const actual = { accountId: String(record.accountId ?? ""), tokenId: String(record.id ?? ""), tokenName: String(record.name ?? ""), scopes: Array.isArray(record.scopes) ? record.scopes.filter((item): item is string => typeof item === "string").sort(compareText) : [], resources: Array.isArray(record.resources) ? record.resources.filter((item): item is string => typeof item === "string").sort(compareText) : [], expiresAt: String(record.expiresAt ?? ""), status: String(record.status ?? "") }; if (!actual.accountId || !actual.tokenId || !actual.tokenName || actual.scopes.length === 0 || actual.resources.length === 0 || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(actual.expiresAt) || !["active", "disabled", "revoked"].includes(actual.status)) return result("unavailable", "malformed-provider-state", null); const digest = authorityDigest({ v: "reelier.cloudflare-token-metadata-projection/v1", ...actual }); const matched = actual.accountId === input.expected.accountId && actual.tokenId === input.expected.tokenId && actual.tokenName === input.policy.tokenName && same(actual.scopes, input.policy.scopes) && same(actual.resources, input.policy.resources) && actual.expiresAt === input.policy.expiresAt && actual.status === "active"; return result(matched ? "matched" : "conflict", matched ? "cloudflare-token-metadata-match" : "cloudflare-token-metadata-conflict", digest); }
function result(status: PackReconciliationResult["status"], reasonCode: string, projectionDigest: string | null): PackReconciliationResult { return Object.freeze({ status, recipeId: cloudflareTokenRollRecipeId, projectionDigest, reasonCode }); }
function same(left: readonly string[], right: readonly string[]): boolean { return left.length === right.length && left.every((value, index) => value === right[index]); }
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
