import type { RegisteredSourceResolver, SourceProjection, ResolverSourceObservation, PlannedSourceRead } from "../../authority/source.js";
import { authorityDigest } from "../../authority/wire.js";
import { cloudflareTokenRollDefinitionDigest, cloudflareTokenRollProjectionSchemaId, cloudflareTokenRollReadEndpointId, cloudflareTokenRollResolverId } from "./manifest.js";
import type { CloudflareTokenProjection } from "./manifest.js";
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Cloudflare token response must be an object"); return value as Record<string, unknown>; }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) throw new TypeError(`Cloudflare token ${label} is invalid`); return value; }
function list(value: unknown, label: string): readonly string[] { if (!Array.isArray(value) || value.length === 0 || value.length > 128 || value.some(item => typeof item !== "string" || item.length === 0 || item.length > 256)) throw new TypeError(`Cloudflare token ${label} is invalid`); const result = [...value] as string[]; if (new Set(result).size !== result.length) throw new TypeError(`Cloudflare token ${label} must be unique`); return Object.freeze(result.sort(compareText)); }
function expires(value: unknown): string { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) || !Number.isFinite(Date.parse(value))) throw new TypeError("Cloudflare token expiry is invalid"); return value; }
function normalize(rawBytes: Uint8Array): CloudflareTokenProjection { let parsed: unknown; try { parsed = JSON.parse(Buffer.from(rawBytes).toString("utf8")); } catch { throw new TypeError("Cloudflare token response is not JSON"); } const root = object(parsed); const record = root.result && typeof root.result === "object" && !Array.isArray(root.result) ? object(root.result) : root; const forbidden = ["value", "token", "secret", "apiToken", "bearer"]; if (Object.keys(record).some(key => forbidden.includes(key))) throw new TypeError("Cloudflare token secret material cannot enter the authority source"); const status = record.status; if (status !== "active" && status !== "disabled" && status !== "revoked") throw new TypeError("Cloudflare token status is invalid"); return Object.freeze({ accountId: id(root.accountId ?? record.accountId, "accountId"), tokenId: id(record.id, "tokenId"), tokenName: id(record.name, "tokenName"), scopes: list(record.scopes, "scopes"), resources: list(record.resources, "resources"), expiresAt: expires(record.expiresAt), status }); }
export function createCloudflareTokenRollSourceResolver(tenant: string = "*"): RegisteredSourceResolver { return Object.freeze({ tenant, resolverId: cloudflareTokenRollResolverId, definitionDigest: cloudflareTokenRollDefinitionDigest, projectionSchemaId: cloudflareTokenRollProjectionSchemaId, readEndpointIds: [cloudflareTokenRollReadEndpointId], maxFreshnessSeconds: 60, plan: (refs: Readonly<Record<string, string>>) => [{ endpointId: cloudflareTokenRollReadEndpointId, opaqueHandle: refs.token }], project: (input: Readonly<{ plans: readonly PlannedSourceRead[]; observations: readonly ResolverSourceObservation[]; observedAt: string }>) => { if (input.observations.length !== 1) throw new TypeError("Cloudflare token source requires one observation"); const projection = normalize(Buffer.from(input.observations[0].bodyBase64, "base64")); const sourceIdentity = `cloudflare.token.${projection.accountId}.${projection.tokenId}`; const triggerIdentity = authorityDigest({ v: "reelier.cloudflare-token-trigger/v1", sourceIdentity, scopes: projection.scopes, resources: projection.resources, expiresAt: projection.expiresAt, status: projection.status }).replace(":", "."); const claims = Object.keys(projection).map(key => ({ claimId: `cloudflare-token-${key}`, projectionPointer: `/${key}` })); return Object.freeze({ sourceIdentity, triggerIdentity, projection, claims: Object.freeze({ grounded: Object.freeze(claims), authored: Object.freeze([]), unresolved: Object.freeze([]) }) }) satisfies SourceProjection; } }); }
function compareText(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
